import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { scrubPublicArtifactText, scrubPublicArtifactValue } from './product-report-sanitizer'

type PackageJson = {
  scripts: Record<string, string>
}

type DoctorResult = {
  ok: boolean
  label: string
  detail?: string
}

type DoctorPayload = {
  timestamp: string
  cwd: string
  summary: {
    total: number
    passed: number
    failed: number
  }
  env: unknown
  results: DoctorResult[]
}

type DoctorCommand = {
  name: string
  command: string[]
  exitCode: number | null
  passed: boolean
  stdoutPreview: string[]
  stderrPreview: string[]
  parsedSummary: DoctorPayload['summary'] | null
}

type DoctorCheck = {
  label: string
  ok: boolean
  detail: string
}

type RuntimeDoctorRegressionReport = {
  generatedAt: string
  mode: 'local_no_provider_runtime_doctor_regression'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  doctorCommands: DoctorCommand[]
  doctorChecks: DoctorCheck[]
  runtimeDoctorSurfaces: string[]
  safeRuntimeEnvironment: Record<string, string>
  temporaryOutReportWritten: boolean
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const tempDir = resolve(root, '.tmp-product-runtime-doctor-regression')
const tempOutPath = resolve(tempDir, 'system-check-report.json')

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function readJson<T>(path: string): T {
  return JSON.parse(readText(path)) as T
}

function preview(text: string): string[] {
  return text
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .slice(0, 80)
}

function parseJsonFromStdout(stdout: string): DoctorPayload | null {
  const start = stdout.indexOf('{')
  const end = stdout.lastIndexOf('}')
  if (start < 0 || end < start) {
    return null
  }
  try {
    return JSON.parse(stdout.slice(start, end + 1)) as DoctorPayload
  } catch {
    return null
  }
}

function safeDoctorEnv(): NodeJS.ProcessEnv {
  return {
    ...process.env,
    CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST: '1',
    CLAUDE_CODE_USE_OPENAI: '0',
    CLAUDE_CODE_USE_GEMINI: '0',
    CLAUDE_CODE_USE_GITHUB: '0',
    CLAUDE_CODE_USE_MISTRAL: '0',
    OPENAI_MODEL: 'product-runtime-doctor-local-no-provider',
    OPENAI_BASE_URL: 'http://127.0.0.1:9/v1',
    OPENAI_API_KEY: '',
    CODEX_API_KEY: '',
    GEMINI_API_KEY: '',
    GOOGLE_API_KEY: '',
    MISTRAL_API_KEY: '',
    GITHUB_TOKEN: '',
    GH_TOKEN: '',
    ANTHROPIC_API_KEY: '',
    OPENCLAUDE_PRODUCT_RUNTIME_DOCTOR_NO_PROVIDER: '1',
  }
}

function runDoctor(name: string, args: string[]): { command: DoctorCommand; payload: DoctorPayload | null } {
  const command = [process.execPath, 'run', 'scripts/system-check.ts', ...args]
  const result = spawnSync(process.execPath, ['run', 'scripts/system-check.ts', ...args], {
    cwd: root,
    encoding: 'utf8',
    env: safeDoctorEnv(),
  })
  const stdout = String(result.stdout ?? '')
  const stderr = String(result.stderr ?? '')
  const payload = parseJsonFromStdout(stdout)
  const passed =
    result.status === 0 &&
    payload !== null &&
    payload.summary.failed === 0 &&
    payload.results.every((item) => item.ok)

  return {
    command: {
      name,
      command,
      exitCode: result.status,
      passed,
      stdoutPreview: preview(stdout),
      stderrPreview: preview(stderr),
      parsedSummary: payload?.summary ?? null,
    },
    payload,
  }
}

function check(label: string, ok: boolean, detail: string): DoctorCheck {
  return { label, ok, detail }
}

function labels(payload: DoctorPayload | null): Set<string> {
  return new Set(payload?.results.map((item) => item.label) ?? [])
}

function resultDetail(payload: DoctorPayload | null, label: string): string {
  return payload?.results.find((item) => item.label === label)?.detail ?? ''
}

function writeReports(report: RuntimeDoctorRegressionReport): void {
  mkdirSync(docsDir, { recursive: true })
  const publicReport = scrubPublicArtifactValue(report)
  writeFileSync(
    resolve(docsDir, 'runtime-doctor-regression-fixtures.json'),
    `${JSON.stringify(publicReport, null, 2)}\n`,
  )

  const lines = [
    '# Runtime Doctor Regression Fixtures',
    '',
    'Generated by: `bun run product:runtime-doctor`',
    '',
    '## Claim Boundary',
    '',
    '- These fixtures verify local runtime doctor behavior only.',
    '- They run the doctor with provider modes explicitly disabled.',
    '- They do not call providers, live models, or external services.',
    '- They do not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- doctor_command_count: \`${report.doctorCommands.length}\``,
    `- doctor_check_count: \`${report.doctorChecks.length}\``,
    `- all_doctor_commands_passed: \`${report.doctorCommands.every((item) => item.passed)}\``,
    `- all_doctor_checks_passed: \`${report.doctorChecks.every((item) => item.ok)}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    `- temporary_out_report_written: \`${report.temporaryOutReportWritten}\``,
    '',
    '## Runtime Doctor Surfaces',
    '',
    ...report.runtimeDoctorSurfaces.map((surface) => `- ${surface}`),
    '',
    '## Commands',
    '',
    '| Command | Exit | Passed | Parsed Summary |',
    '| --- | ---: | --- | --- |',
    ...report.doctorCommands.map((item) => (
      `| \`${item.command.join(' ')}\` | ${item.exitCode ?? 'null'} | \`${item.passed}\` | \`${JSON.stringify(item.parsedSummary)}\` |`
    )),
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.doctorChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'runtime-doctor-regression-fixtures.md'), `${scrubPublicArtifactText(lines.join('\n'))}\n`)
}

function main(): void {
  rmSync(tempDir, { recursive: true, force: true })
  mkdirSync(dirname(tempOutPath), { recursive: true })

  const pkg = readJson<PackageJson>('package.json')
  const systemCheckSource = readText('scripts/system-check.ts')
  const jsonRun = runDoctor('json_stdout', ['--json'])
  const outRun = runDoctor('json_stdout_and_out_file', ['--json', '--out', tempOutPath])
  const outReportWritten = existsSync(tempOutPath)
  const outPayload = outReportWritten ? readJson<DoctorPayload>(tempOutPath) : null
  const jsonLabels = labels(jsonRun.payload)
  const outLabels = labels(outRun.payload)
  const expectedLabels = [
    'Node.js version',
    'Bun runtime',
    'Build artifacts',
    'Provider mode',
    'Provider reachability',
    'Provider generation readiness',
    'Ollama processor mode',
  ]
  const runtimeDoctorSurfaces = [
    'Node.js version check',
    'Bun runtime check',
    'build artifact presence check',
    'provider mode summary',
    'provider reachability skip when provider mode is disabled',
    'provider generation readiness skip when provider mode is disabled',
    'Ollama processor mode skip when OpenAI-compatible mode is disabled',
    'console JSON output with redacted environment summary',
    'JSON report write through --out',
  ]
  const doctorChecks = [
    check('package exposes doctor:runtime', typeof pkg.scripts['doctor:runtime'] === 'string', pkg.scripts['doctor:runtime'] ?? 'missing'),
    check('package exposes doctor:runtime:json', typeof pkg.scripts['doctor:runtime:json'] === 'string', pkg.scripts['doctor:runtime:json'] ?? 'missing'),
    check('package exposes doctor:report', typeof pkg.scripts['doctor:report'] === 'string', pkg.scripts['doctor:report'] ?? 'missing'),
    check('system-check parses --json', systemCheckSource.includes("arg === '--json'"), 'parseOptions recognizes --json'),
    check('system-check parses --out', systemCheckSource.includes("arg === '--out'"), 'parseOptions recognizes --out'),
    check('json stdout command passed', jsonRun.command.passed, `exit=${jsonRun.command.exitCode}`),
    check('json out command passed', outRun.command.passed, `exit=${outRun.command.exitCode}`),
    check('out report was written', outReportWritten, tempOutPath),
    check('out report summary has no failures', outPayload?.summary.failed === 0, JSON.stringify(outPayload?.summary ?? null)),
    check('json stdout labels are complete', expectedLabels.every((label) => jsonLabels.has(label)), [...jsonLabels].join(', ')),
    check('out stdout labels are complete', expectedLabels.every((label) => outLabels.has(label)), [...outLabels].join(', ')),
    check('provider reachability stayed skipped', /Skipped/.test(resultDetail(jsonRun.payload, 'Provider reachability')), resultDetail(jsonRun.payload, 'Provider reachability')),
    check('provider generation readiness stayed skipped', /Skipped/.test(resultDetail(jsonRun.payload, 'Provider generation readiness')), resultDetail(jsonRun.payload, 'Provider generation readiness')),
    check('console JSON redacts environment summary', jsonRun.payload?.env === '[redacted in console JSON output; use --out-file for the full report]', String(jsonRun.payload?.env)),
    check('safe runtime surface count is high enough', runtimeDoctorSurfaces.length >= 6, String(runtimeDoctorSurfaces.length)),
  ]

  const report: RuntimeDoctorRegressionReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_runtime_doctor_regression',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    doctorCommands: [jsonRun.command, outRun.command],
    doctorChecks,
    runtimeDoctorSurfaces,
    safeRuntimeEnvironment: {
      CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST: '1',
      CLAUDE_CODE_USE_OPENAI: '0',
      CLAUDE_CODE_USE_GEMINI: '0',
      CLAUDE_CODE_USE_GITHUB: '0',
      CLAUDE_CODE_USE_MISTRAL: '0',
      OPENAI_MODEL: 'product-runtime-doctor-local-no-provider',
      OPENAI_BASE_URL: 'http://127.0.0.1:9/v1',
    },
    temporaryOutReportWritten: outReportWritten,
    claimBoundary: 'Runtime doctor regression fixtures are local no-provider runtime diagnostics only, not provider-backed execution, external validation, release readiness, production readiness, public readiness, or autonomous reliability.',
  }

  writeReports(report)
  rmSync(tempDir, { recursive: true, force: true })

  for (const item of report.doctorChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!report.doctorCommands.every((item) => item.passed) || !report.doctorChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`doctor_command_count=${report.doctorCommands.length}`)
  console.log(`doctor_check_count=${report.doctorChecks.length}`)
  console.log(`runtime_doctor_surfaces=${report.runtimeDoctorSurfaces.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
