import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { scrubPublicArtifactText, scrubPublicArtifactValue } from './product-report-sanitizer'

type PackageJson = {
  version: string
}

type TranscriptCheck = {
  name: string
  command: string[]
  exitCode: number | null
  passed: boolean
  requiredSubstrings: string[]
  missingSubstrings: string[]
  stdoutPreview: string[]
  stderrPreview: string[]
}

type GoldenTranscriptReport = {
  generatedAt: string
  mode: 'local_no_provider_cli_surface'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  transcripts: TranscriptCheck[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const cliPath = resolve(root, 'dist/cli.mjs')
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')) as PackageJson

function normalize(text: string | Buffer | null | undefined): string {
  return String(text ?? '').replace(/\r\n/g, '\n')
}

function preview(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .slice(0, 80)
}

function runTranscript(name: string, args: string[], requiredSubstrings: string[]): TranscriptCheck {
  const command = [process.execPath, cliPath, ...args]
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    cwd: root,
    encoding: 'utf8',
    env: {
      ...process.env,
      OPENCLAUDE_PRODUCT_TRANSCRIPT_NO_PROVIDER: '1',
    },
  })
  const stdout = normalize(result.stdout)
  const stderr = normalize(result.stderr)
  const combined = `${stdout}\n${stderr}`
  const missingSubstrings = requiredSubstrings.filter((substring) => !combined.includes(substring))
  return {
    name,
    command,
    exitCode: result.status,
    passed: result.status === 0 && missingSubstrings.length === 0,
    requiredSubstrings,
    missingSubstrings,
    stdoutPreview: preview(stdout),
    stderrPreview: preview(stderr),
  }
}

function writeReports(report: GoldenTranscriptReport): void {
  mkdirSync(docsDir, { recursive: true })
  const publicReport = scrubPublicArtifactValue(report)
  writeFileSync(
    resolve(docsDir, 'golden-path-terminal-transcripts.json'),
    `${JSON.stringify(publicReport, null, 2)}\n`,
  )

  const lines = [
    '# Golden Path Terminal Transcripts',
    '',
    'Generated by: `bun run product:golden-transcripts`',
    '',
    '## Claim Boundary',
    '',
    '- These transcripts verify local CLI surface behavior only.',
    '- They do not call providers, live models, or external services.',
    '- They do not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    `- transcript_count: \`${report.transcripts.length}\``,
    `- all_transcripts_passed: \`${report.transcripts.every((transcript) => transcript.passed)}\``,
    '',
    '## Transcripts',
    '',
  ]

  for (const transcript of report.transcripts) {
    lines.push(`### ${transcript.name}`)
    lines.push('')
    lines.push(`- command: \`${transcript.command.join(' ')}\``)
    lines.push(`- exit_code: \`${transcript.exitCode}\``)
    lines.push(`- passed: \`${transcript.passed}\``)
    if (transcript.missingSubstrings.length > 0) {
      lines.push(`- missing_substrings: \`${transcript.missingSubstrings.join(', ')}\``)
    }
    lines.push('')
    lines.push('```text')
    lines.push(...transcript.stdoutPreview)
    if (transcript.stderrPreview.length > 0) {
      lines.push('--- stderr ---')
      lines.push(...transcript.stderrPreview)
    }
    lines.push('```')
    lines.push('')
  }

  writeFileSync(resolve(docsDir, 'golden-path-terminal-transcripts.md'), `${scrubPublicArtifactText(lines.join('\n'))}\n`)
}

function main(): void {
  if (!existsSync(cliPath)) {
    console.error(`RESULT: FAIL`)
    console.error(`missing built CLI: ${cliPath}`)
    console.error('Run `bun run smoke` or `bun run build` before `bun run product:golden-transcripts`.')
    process.exit(1)
  }

  const report: GoldenTranscriptReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_cli_surface',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    transcripts: [
      runTranscript('version', ['--version'], [`${pkg.version} (Open Claude)`]),
      runTranscript('help', ['--help'], [
        'Usage: claude',
        '--provider <provider>',
        '--model <model>',
        '--permission-mode <mode>',
        'doctor',
        'mcp',
        'plugin|plugins',
      ]),
    ],
  }

  writeReports(report)

  for (const transcript of report.transcripts) {
    const prefix = transcript.passed ? 'PASS' : 'FAIL'
    console.log(`${prefix}: transcript ${transcript.name} exit=${transcript.exitCode}`)
    if (transcript.missingSubstrings.length > 0) {
      console.log(`missing=${transcript.missingSubstrings.join(', ')}`)
    }
  }

  console.log('')
  if (!report.transcripts.every((transcript) => transcript.passed)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`transcript_count=${report.transcripts.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
