import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type SourceControlledCheck = {
  label: string
  ok: boolean
  detail: string
}

type SourceControlledChecksReport = {
  generatedAt: string
  mode: 'local_no_provider_source_controlled_product_checks'
  workflowPath: string
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  productQualityCommandPresent: boolean
  pullRequestTriggerPresent: boolean
  pushMainTriggerPresent: boolean
  releaseActionsAbsent: boolean
  actionReferencesPinned: boolean
  sourceControlledChecks: SourceControlledCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const workflowPath = '.github/workflows/pr-checks.yml'

function check(label: string, ok: boolean, detail: string): SourceControlledCheck {
  return { label, ok, detail }
}

function hasLine(text: string, pattern: RegExp): boolean {
  return text.split(/\r?\n/).some((line) => pattern.test(line))
}

function actionReferencesArePinned(text: string): boolean {
  const usesLines = text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('uses: '))

  return usesLines.length > 0 && usesLines.every((line) => /@[a-f0-9]{40}(?:\s|$)/i.test(line))
}

function writeReports(report: SourceControlledChecksReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'source-controlled-checks-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const lines = [
    '# Source-Controlled Checks Report',
    '',
    'Generated by: `bun run product:source-controlled-checks`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies that the product-quality gate is wired into source-controlled PR/push checks.',
    '- It does not run GitHub Actions, publish, deploy, launch, call providers, call live models, or call external services.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- workflow_path: \`${report.workflowPath}\``,
    `- product_quality_command_present: \`${report.productQualityCommandPresent}\``,
    `- pull_request_trigger_present: \`${report.pullRequestTriggerPresent}\``,
    `- push_main_trigger_present: \`${report.pushMainTriggerPresent}\``,
    `- release_actions_absent: \`${report.releaseActionsAbsent}\``,
    `- action_references_pinned: \`${report.actionReferencesPinned}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.sourceControlledChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'source-controlled-checks-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const workflow = readFileSync(resolve(root, workflowPath), 'utf8')
  const productQualityCommandPresent = workflow.includes('bun run product:quality')
  const pullRequestTriggerPresent = hasLine(workflow, /^\s*pull_request:\s*$/)
  const pushMainTriggerPresent =
    hasLine(workflow, /^\s*push:\s*$/) &&
    hasLine(workflow, /^\s*-\s*main\s*$/)
  const releaseActionsAbsent = !/(npm\s+publish|docker\/build-push-action|release-please|deploy|launch)/i.test(workflow)
  const actionReferencesPinned = actionReferencesArePinned(workflow)

  const sourceControlledChecks = [
    check('workflow exists in source control path', workflow.trim().length > 0, workflowPath),
    check('product-quality gate command is present', productQualityCommandPresent, 'bun run product:quality'),
    check('pull request trigger is present', pullRequestTriggerPresent, 'pull_request'),
    check('main push trigger is present', pushMainTriggerPresent, 'push branches main'),
    check('release actions are absent from PR checks', releaseActionsAbsent, 'no publish/deploy/launch/release action in pr-checks workflow'),
    check('GitHub action references are pinned by SHA', actionReferencesPinned, 'uses: entries must pin 40-character SHAs'),
  ]

  const report: SourceControlledChecksReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_source_controlled_product_checks',
    workflowPath,
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    productQualityCommandPresent,
    pullRequestTriggerPresent,
    pushMainTriggerPresent,
    releaseActionsAbsent,
    actionReferencesPinned,
    sourceControlledChecks,
    claimBoundary: 'Source-controlled product checks prove local workflow wiring only. They do not prove GitHub-hosted execution, release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
  }

  writeReports(report)

  for (const item of sourceControlledChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!sourceControlledChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`workflow_path=${workflowPath}`)
  console.log(`product_quality_command_present=${productQualityCommandPresent}`)
  console.log(`pull_request_trigger_present=${pullRequestTriggerPresent}`)
  console.log(`push_main_trigger_present=${pushMainTriggerPresent}`)
  console.log(`release_actions_absent=${releaseActionsAbsent}`)
  console.log(`action_references_pinned=${actionReferencesPinned}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
