import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { resolve } from 'node:path'

type PostureCheck = {
  label: string
  ok: boolean
  detail: string
}

type ClassifiedGap = {
  id: string
  status: 'classified_unresolved'
  protectedActionRequired: boolean
  reason: string
}

type OpenSsfSecurityPostureReport = {
  generatedAt: string
  mode: 'local_no_provider_openssf_security_posture'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  securityPolicyPath: string
  securityPolicySha256: string
  prWorkflowPath: string
  prWorkflowSha256: string
  releaseWorkflowPath: string
  releaseWorkflowSha256: string
  codeqlWorkflowPath: string
  codeqlWorkflowSha256: string | null
  scorecardWorkflowPath: string
  scorecardWorkflowSha256: string | null
  dependabotConfigPath: string
  dependabotConfigSha256: string | null
  primarySourceInputs: Array<{
    sourceProject: string
    sourceUrl: string
    appliedPattern: string
  }>
  securityPolicyPresent: boolean
  privateReportingGuidancePresent: boolean
  responseTimelinePresent: boolean
  allWorkflowActionReferencesPinned: boolean
  prWorkflowTokenPermissionsReadOnly: boolean
  releaseWorkflowBoundaryOnly: boolean
  releaseWorkflowPermissionsScoped: boolean
  pullRequestTargetAbsent: boolean
  dependabotConfigPresent: boolean
  dependabotCoversNpm: boolean
  dependabotCoversGitHubActions: boolean
  dependabotSchedulesPresent: boolean
  codeqlWorkflowPresent: boolean
  codeqlActionsPinned: boolean
  codeqlPermissionsScoped: boolean
  codeqlAnalyzesJavaScriptTypeScript: boolean
  codeqlSecurityExtendedQueriesConfigured: boolean
  codeqlScheduledScanConfigured: boolean
  codeqlHostedExecutionPerformed: false
  scorecardWorkflowPresent: boolean
  scorecardWorkflowActionsPinned: boolean
  scorecardWorkflowPermissionsScoped: boolean
  scorecardScheduledScanConfigured: boolean
  scorecardSarifUploadConfigured: boolean
  scorecardWorkflowPublishRestrictionsCompliant: boolean
  scorecardHostedExecutionPerformed: false
  productQualityWorkflowPresent: boolean
  frozenDependencyInstallPresent: boolean
  npmProvenanceConfigured: boolean
  npmTrustedPublishingBoundaryPresent: boolean
  releaseEnvironmentPresent: boolean
  dockerPackageWriteScoped: boolean
  realScorecardRunPerformed: false
  scorecardExternalClaimAllowed: false
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  classifiedUnresolvedGaps: ClassifiedGap[]
  postureChecks: PostureCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const securityPolicyPath = 'SECURITY.md'
const prWorkflowPath = '.github/workflows/pr-checks.yml'
const releaseWorkflowPath = '.github/workflows/release.yml'
const codeqlWorkflowPath = '.github/workflows/codeql.yml'
const scorecardWorkflowPath = '.github/workflows/scorecard.yml'
const dependabotConfigPath = '.github/dependabot.yml'

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex')
}

function check(label: string, ok: boolean, detail: string): PostureCheck {
  return { label, ok, detail }
}

function usesLines(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.startsWith('uses: '))
}

function allActionsPinned(texts: string[]): boolean {
  const lines = texts.flatMap(usesLines)
  return lines.length > 0 && lines.every((line) => /@[a-f0-9]{40}(?:\s|$)/i.test(line))
}

function sectionContains(text: string, sectionHeader: string, expected: string[]): boolean {
  const lines = text.split(/\r?\n/)
  const headerIndex = lines.findIndex((line) => line.trim() === sectionHeader)
  if (headerIndex < 0) {
    return false
  }

  const nextHeaderIndex = lines.findIndex((line, index) => index > headerIndex && /^\s{0,4}[A-Za-z0-9_-]+:\s*$/.test(line))
  const section = lines.slice(headerIndex, nextHeaderIndex < 0 ? lines.length : nextHeaderIndex).join('\n')
  return expected.every((needle) => section.includes(needle))
}

function writeReports(report: OpenSsfSecurityPostureReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(resolve(docsDir, 'openssf-security-posture-report.json'), `${JSON.stringify(report, null, 2)}\n`)

  const lines = [
    '# OpenSSF Security Posture Report',
    '',
    'Generated by: `bun run product:openssf-security-posture`',
    '',
    '## Claim Boundary',
    '',
    '- This is a local, no-provider, no-network posture inspection against OpenSSF Scorecard, SLSA, GitHub Actions, and npm provenance criteria.',
    '- It does not run OpenSSF Scorecard, GitHub-hosted CI, publish, deploy, launch, call providers, call live models, call external services, or install dependencies.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, external Scorecard results, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- security_policy_present: \`${report.securityPolicyPresent}\``,
    `- private_reporting_guidance_present: \`${report.privateReportingGuidancePresent}\``,
    `- response_timeline_present: \`${report.responseTimelinePresent}\``,
    `- all_workflow_action_references_pinned: \`${report.allWorkflowActionReferencesPinned}\``,
    `- pr_workflow_token_permissions_read_only: \`${report.prWorkflowTokenPermissionsReadOnly}\``,
    `- release_workflow_boundary_only: \`${report.releaseWorkflowBoundaryOnly}\``,
    `- release_workflow_permissions_scoped: \`${report.releaseWorkflowPermissionsScoped}\``,
    `- pull_request_target_absent: \`${report.pullRequestTargetAbsent}\``,
    `- dependabot_config_present: \`${report.dependabotConfigPresent}\``,
    `- dependabot_covers_npm: \`${report.dependabotCoversNpm}\``,
    `- dependabot_covers_github_actions: \`${report.dependabotCoversGitHubActions}\``,
    `- dependabot_schedules_present: \`${report.dependabotSchedulesPresent}\``,
    `- codeql_workflow_present: \`${report.codeqlWorkflowPresent}\``,
    `- codeql_actions_pinned: \`${report.codeqlActionsPinned}\``,
    `- codeql_permissions_scoped: \`${report.codeqlPermissionsScoped}\``,
    `- codeql_analyzes_javascript_typescript: \`${report.codeqlAnalyzesJavaScriptTypeScript}\``,
    `- codeql_security_extended_queries_configured: \`${report.codeqlSecurityExtendedQueriesConfigured}\``,
    `- codeql_scheduled_scan_configured: \`${report.codeqlScheduledScanConfigured}\``,
    `- codeql_hosted_execution_performed: \`${report.codeqlHostedExecutionPerformed}\``,
    `- scorecard_workflow_present: \`${report.scorecardWorkflowPresent}\``,
    `- scorecard_workflow_actions_pinned: \`${report.scorecardWorkflowActionsPinned}\``,
    `- scorecard_workflow_permissions_scoped: \`${report.scorecardWorkflowPermissionsScoped}\``,
    `- scorecard_scheduled_scan_configured: \`${report.scorecardScheduledScanConfigured}\``,
    `- scorecard_sarif_upload_configured: \`${report.scorecardSarifUploadConfigured}\``,
    `- scorecard_workflow_publish_restrictions_compliant: \`${report.scorecardWorkflowPublishRestrictionsCompliant}\``,
    `- scorecard_hosted_execution_performed: \`${report.scorecardHostedExecutionPerformed}\``,
    `- product_quality_workflow_present: \`${report.productQualityWorkflowPresent}\``,
    `- frozen_dependency_install_present: \`${report.frozenDependencyInstallPresent}\``,
    `- npm_provenance_configured: \`${report.npmProvenanceConfigured}\``,
    `- npm_trusted_publishing_boundary_present: \`${report.npmTrustedPublishingBoundaryPresent}\``,
    `- release_environment_present: \`${report.releaseEnvironmentPresent}\``,
    `- docker_package_write_scoped: \`${report.dockerPackageWriteScoped}\``,
    `- real_scorecard_run_performed: \`${report.realScorecardRunPerformed}\``,
    `- scorecard_external_claim_allowed: \`${report.scorecardExternalClaimAllowed}\``,
    '',
    '## Primary Sources',
    '',
    '| Source | Pattern applied |',
    '| --- | --- |',
    ...report.primarySourceInputs.map((source) => `| [${source.sourceProject}](${source.sourceUrl}) | ${source.appliedPattern} |`),
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.postureChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
    '## Classified Unresolved Gaps',
    '',
    '| Gap | Status | Protected action required | Reason |',
    '| --- | --- | --- | --- |',
    ...report.classifiedUnresolvedGaps.map((gap) => `| ${gap.id} | \`${gap.status}\` | \`${gap.protectedActionRequired}\` | ${gap.reason} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'openssf-security-posture-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const securityPolicy = readText(securityPolicyPath)
  const prWorkflow = readText(prWorkflowPath)
  const releaseWorkflow = readText(releaseWorkflowPath)
  const codeqlWorkflowExists = existsSync(resolve(root, codeqlWorkflowPath))
  const codeqlWorkflow = codeqlWorkflowExists ? readText(codeqlWorkflowPath) : ''
  const scorecardWorkflowExists = existsSync(resolve(root, scorecardWorkflowPath))
  const scorecardWorkflow = scorecardWorkflowExists ? readText(scorecardWorkflowPath) : ''
  const dependabotConfigExists = existsSync(resolve(root, dependabotConfigPath))
  const dependabotConfig = dependabotConfigExists ? readText(dependabotConfigPath) : ''
  const combinedWorkflows = `${prWorkflow}\n${releaseWorkflow}\n${codeqlWorkflow}\n${scorecardWorkflow}`

  const securityPolicyPresent = securityPolicy.trim().length > 0 && /Reporting a Vulnerability/i.test(securityPolicy)
  const privateReportingGuidancePresent = /report it privately/i.test(securityPolicy) && /GitHub Security Advisories/i.test(securityPolicy)
  const responseTimelinePresent = /within 7 days/i.test(securityPolicy)
  const allWorkflowActionReferencesPinned = allActionsPinned([prWorkflow, releaseWorkflow])
  const prWorkflowTokenPermissionsReadOnly = /permissions:\s*\r?\n\s+contents:\s+read/i.test(prWorkflow) && !/\b(write-all|contents:\s+write|packages:\s+write|id-token:\s+write)\b/i.test(prWorkflow)
  const releaseWorkflowBoundaryOnly =
    /name:\s+Release Boundary/i.test(releaseWorkflow) &&
    /No npm publish, Docker push, or release creation is authorized/.test(releaseWorkflow) &&
    !/^\s*run:\s*npm publish\b/im.test(releaseWorkflow) &&
    !/docker\/build-push-action/i.test(releaseWorkflow) &&
    !/release-please-action/i.test(releaseWorkflow)
  const releaseBoundaryPermissionsScoped =
    releaseWorkflowBoundaryOnly &&
    /permissions:\s*\r?\n\s+contents:\s+read/i.test(releaseWorkflow) &&
    !/\b(write-all|contents:\s+write|pull-requests:\s+write|packages:\s+write|id-token:\s+write)\b/i.test(releaseWorkflow)
  const releasePipelinePermissionsScoped =
    sectionContains(releaseWorkflow, 'permissions:', ['contents: write', 'pull-requests: write']) &&
    releaseWorkflow.includes('contents: read') &&
    releaseWorkflow.includes('id-token: write') &&
    releaseWorkflow.includes('packages: write') &&
    !/\bwrite-all\b/i.test(releaseWorkflow)
  const releaseWorkflowPermissionsScoped = releaseBoundaryPermissionsScoped || releasePipelinePermissionsScoped
  const pullRequestTargetAbsent = !/\bpull_request_target\b/i.test(combinedWorkflows)
  const dependabotConfigPresent = dependabotConfig.trim().length > 0 && /version:\s*2/.test(dependabotConfig)
  const dependabotCoversNpm = /package-ecosystem:\s*["']?npm["']?/i.test(dependabotConfig) && /directory:\s*["']?\/["']?/i.test(dependabotConfig)
  const dependabotCoversGitHubActions = /package-ecosystem:\s*["']?github-actions["']?/i.test(dependabotConfig)
  const dependabotSchedulesPresent = (dependabotConfig.match(/interval:\s*["']?weekly["']?/gi) ?? []).length >= 2
  const codeqlWorkflowPresent = codeqlWorkflowExists && /github\/codeql-action\/init@/i.test(codeqlWorkflow) && /github\/codeql-action\/analyze@/i.test(codeqlWorkflow)
  const codeqlActionsPinned = codeqlWorkflowPresent && allActionsPinned([codeqlWorkflow])
  const codeqlPermissionsScoped = /security-events:\s+write/.test(codeqlWorkflow) && /contents:\s+read/.test(codeqlWorkflow) && !/\bwrite-all\b/i.test(codeqlWorkflow)
  const codeqlAnalyzesJavaScriptTypeScript = /javascript-typescript/.test(codeqlWorkflow)
  const codeqlSecurityExtendedQueriesConfigured = /security-extended/.test(codeqlWorkflow) && /security-and-quality/.test(codeqlWorkflow)
  const codeqlScheduledScanConfigured = /schedule:/.test(codeqlWorkflow) && /cron:/.test(codeqlWorkflow)
  const scorecardWorkflowPresent = scorecardWorkflowExists && /ossf\/scorecard-action@/i.test(scorecardWorkflow)
  const scorecardWorkflowActionsPinned = scorecardWorkflowPresent && allActionsPinned([scorecardWorkflow])
  const scorecardWorkflowPermissionsScoped =
    /permissions:\s*\r?\n\s+contents:\s+read\s*\r?\n\s+security-events:\s+write\s*\r?\n\s+id-token:\s+write/i.test(scorecardWorkflow) &&
    !/\b(write-all|contents:\s+write|pull-requests:\s+write|packages:\s+write)\b/i.test(scorecardWorkflow)
  const scorecardScheduledScanConfigured = /schedule:/.test(scorecardWorkflow) && /cron:/.test(scorecardWorkflow)
  const scorecardSarifUploadConfigured =
    /results_file:\s+results\.sarif/.test(scorecardWorkflow) &&
    /results_format:\s+sarif/.test(scorecardWorkflow) &&
    /publish_results:\s+true/.test(scorecardWorkflow)
  const scorecardWorkflowPublishRestrictionsCompliant =
    scorecardWorkflowPresent &&
    !/^\s*env:\s*$/m.test(scorecardWorkflow) &&
    !/^\s*defaults:\s*$/m.test(scorecardWorkflow)
  const productQualityWorkflowPresent = /bun run product:quality/.test(prWorkflow)
  const frozenDependencyInstallPresent = /bun install --frozen-lockfile/.test(prWorkflow) && /bun install --frozen-lockfile/.test(releaseWorkflow)
  const npmProvenanceConfigured = /npm publish --access public --provenance/.test(releaseWorkflow)
  const npmTrustedPublishingBoundaryPresent = /id-token:\s+write/.test(releaseWorkflow) && /unset NODE_AUTH_TOKEN/.test(releaseWorkflow)
  const releaseEnvironmentPresent = /environment:\s+release/.test(releaseWorkflow)
  const dockerPackageWriteScoped = /name:\s+Build & Push Docker Image/.test(releaseWorkflow) && /packages:\s+write/.test(releaseWorkflow) && !/packages:\s+write/.test(prWorkflow)

  const classifiedUnresolvedGaps: ClassifiedGap[] = [
    {
      id: 'external_openssf_scorecard_run',
      status: 'classified_unresolved',
      protectedActionRequired: true,
      reason: 'A real Scorecard run requires external repository/API access or a container/tool invocation, so this local gate records posture evidence only.',
    },
    {
      id: 'hosted_ci_scorecard_evidence',
      status: 'classified_unresolved',
      protectedActionRequired: true,
      reason: 'Hosted CI evidence requires a real GitHub repository/remote workflow run; this workspace is not currently a Git repository root.',
    },
    {
      id: 'hosted_codeql_analysis_evidence',
      status: 'classified_unresolved',
      protectedActionRequired: true,
      reason: 'The local CodeQL workflow file is configured, but hosted CodeQL analysis evidence requires a GitHub Actions run on a real GitHub repository boundary.',
    },
    {
      id: 'signed_artifact_attestation_verification',
      status: 'classified_unresolved',
      protectedActionRequired: true,
      reason: 'Signed attestation verification requires a real release artifact and external registry/provenance boundary.',
    },
  ]

  const postureChecks = [
    check('security policy exists', securityPolicyPresent, securityPolicyPath),
    check('private vulnerability reporting guidance exists', privateReportingGuidancePresent, 'GitHub Security Advisories / private reporting'),
    check('response timeline exists', responseTimelinePresent, 'initial triage acknowledgment within 7 days'),
    check('workflow action references are pinned by full SHA', allWorkflowActionReferencesPinned, usesLines(combinedWorkflows).join(', ')),
    check('PR workflow token permissions are read-only', prWorkflowTokenPermissionsReadOnly, 'permissions: contents: read'),
    check('release workflow is boundary-only or has scoped release permissions', releaseWorkflowPermissionsScoped, releaseWorkflowBoundaryOnly ? 'boundary workflow uses contents: read only' : 'release-please/publish-npm/docker job permissions'),
    check('pull_request_target is absent', pullRequestTargetAbsent, 'no pull_request_target trigger'),
    check('Dependabot configuration exists', dependabotConfigPresent, dependabotConfigPath),
    check('Dependabot covers npm dependencies', dependabotCoversNpm, 'package-ecosystem: npm at /'),
    check('Dependabot covers GitHub Actions', dependabotCoversGitHubActions, 'package-ecosystem: github-actions'),
    check('Dependabot schedules are present', dependabotSchedulesPresent, 'weekly schedules for npm and github-actions'),
    check('CodeQL workflow exists', codeqlWorkflowPresent, codeqlWorkflowPath),
    check('CodeQL workflow actions are pinned by full SHA', codeqlActionsPinned, usesLines(codeqlWorkflow).join(', ')),
    check('CodeQL workflow permissions are scoped', codeqlPermissionsScoped, 'security-events: write plus contents: read'),
    check('CodeQL workflow analyzes JavaScript/TypeScript', codeqlAnalyzesJavaScriptTypeScript, 'javascript-typescript'),
    check('CodeQL workflow uses extended security query suites', codeqlSecurityExtendedQueriesConfigured, 'security-extended, security-and-quality'),
    check('CodeQL workflow has scheduled scanning', codeqlScheduledScanConfigured, 'schedule cron'),
    check('Scorecard workflow exists', scorecardWorkflowPresent, scorecardWorkflowPath),
    check('Scorecard workflow action is pinned by full SHA', scorecardWorkflowActionsPinned, usesLines(scorecardWorkflow).join(', ')),
    check('Scorecard workflow permissions are scoped', scorecardWorkflowPermissionsScoped, 'contents: read, security-events: write, id-token: write'),
    check('Scorecard workflow has scheduled scanning', scorecardScheduledScanConfigured, 'schedule cron'),
    check('Scorecard workflow publishes SARIF results', scorecardSarifUploadConfigured, 'results.sarif / sarif / publish_results'),
    check('Scorecard workflow follows publish_results restrictions', scorecardWorkflowPublishRestrictionsCompliant, 'no env/defaults in Scorecard workflow'),
    check('product-quality workflow is present', productQualityWorkflowPresent, 'bun run product:quality'),
    check('dependency install uses frozen lockfile', frozenDependencyInstallPresent, 'bun install --frozen-lockfile'),
    check('npm provenance publish flag is configured or release is boundary-only', releaseWorkflowBoundaryOnly || npmProvenanceConfigured, releaseWorkflowBoundaryOnly ? 'release boundary disables npm publish' : 'npm publish --access public --provenance'),
    check('npm OIDC/trusted publishing boundary is present or release is boundary-only', releaseWorkflowBoundaryOnly || npmTrustedPublishingBoundaryPresent, releaseWorkflowBoundaryOnly ? 'release boundary disables trusted publishing' : 'id-token: write plus NODE_AUTH_TOKEN clearing'),
    check('release environment gate is present or release is boundary-only', releaseWorkflowBoundaryOnly || releaseEnvironmentPresent, releaseWorkflowBoundaryOnly ? 'release boundary has no release environment' : 'environment: release'),
    check('Docker package write permission is scoped or release is boundary-only', releaseWorkflowBoundaryOnly || dockerPackageWriteScoped, releaseWorkflowBoundaryOnly ? 'release boundary disables Docker package writes' : 'packages: write only in release docker job'),
    check('external Scorecard run remains blocked', true, 'realScorecardRunPerformed=false'),
    check('release/public/production/external/autonomous claims remain blocked', true, 'all claim booleans false'),
    check('protected gaps are classified unresolved', classifiedUnresolvedGaps.every((gap) => gap.status === 'classified_unresolved'), classifiedUnresolvedGaps.map((gap) => gap.id).join(', ')),
  ]

  const report: OpenSsfSecurityPostureReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_openssf_security_posture',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    securityPolicyPath,
    securityPolicySha256: sha256(securityPolicy),
    prWorkflowPath,
    prWorkflowSha256: sha256(prWorkflow),
    releaseWorkflowPath,
    releaseWorkflowSha256: sha256(releaseWorkflow),
    codeqlWorkflowPath,
    codeqlWorkflowSha256: codeqlWorkflowExists ? sha256(codeqlWorkflow) : null,
    scorecardWorkflowPath,
    scorecardWorkflowSha256: scorecardWorkflowExists ? sha256(scorecardWorkflow) : null,
    dependabotConfigPath,
    dependabotConfigSha256: dependabotConfigExists ? sha256(dependabotConfig) : null,
    primarySourceInputs: [
      {
        sourceProject: 'ossf/scorecard',
        sourceUrl: 'https://github.com/ossf/scorecard',
        appliedPattern: 'Track Security-Policy, Dependency-Update-Tool, Pinned-Dependencies, Token-Permissions, Dangerous-Workflow, SAST, Signed-Releases, Packaging, and CI posture as explicit evidence.',
      },
      {
        sourceProject: 'slsa-framework/slsa',
        sourceUrl: 'https://github.com/slsa-framework/slsa',
        appliedPattern: 'Separate local provenance configuration from real provenance existence, authenticity, isolation, and attestation verification.',
      },
      {
        sourceProject: 'github/docs',
        sourceUrl: 'https://github.com/github/docs',
        appliedPattern: 'Pin actions to full-length commit SHAs, minimize GITHUB_TOKEN permissions, configure Dependabot update ecosystems, configure CodeQL advanced setup, and use artifact/provenance boundaries without claiming hosted execution locally.',
      },
      {
        sourceProject: 'npm/documentation',
        sourceUrl: 'https://github.com/npm/documentation',
        appliedPattern: 'Treat npm provenance as a verifiable link to source/build instructions, not as proof that the package is safe or release-ready.',
      },
    ],
    securityPolicyPresent,
    privateReportingGuidancePresent,
    responseTimelinePresent,
    allWorkflowActionReferencesPinned,
    prWorkflowTokenPermissionsReadOnly,
    releaseWorkflowBoundaryOnly,
    releaseWorkflowPermissionsScoped,
    pullRequestTargetAbsent,
    dependabotConfigPresent,
    dependabotCoversNpm,
    dependabotCoversGitHubActions,
    dependabotSchedulesPresent,
    codeqlWorkflowPresent,
    codeqlActionsPinned,
    codeqlPermissionsScoped,
    codeqlAnalyzesJavaScriptTypeScript,
    codeqlSecurityExtendedQueriesConfigured,
    codeqlScheduledScanConfigured,
    codeqlHostedExecutionPerformed: false,
    scorecardWorkflowPresent,
    scorecardWorkflowActionsPinned,
    scorecardWorkflowPermissionsScoped,
    scorecardScheduledScanConfigured,
    scorecardSarifUploadConfigured,
    scorecardWorkflowPublishRestrictionsCompliant,
    scorecardHostedExecutionPerformed: false,
    productQualityWorkflowPresent,
    frozenDependencyInstallPresent,
    npmProvenanceConfigured,
    npmTrustedPublishingBoundaryPresent,
    releaseEnvironmentPresent,
    dockerPackageWriteScoped,
    realScorecardRunPerformed: false,
    scorecardExternalClaimAllowed: false,
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    classifiedUnresolvedGaps,
    postureChecks,
    claimBoundary: 'This local OpenSSF/SLSA posture report verifies repository files only; it does not run external Scorecard, hosted CI, registry attestation verification, release, publish, deploy, provider, live-model, or external-service actions.',
  }

  writeReports(report)

  for (const item of postureChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!postureChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`security_policy_present=${securityPolicyPresent}`)
  console.log(`all_workflow_action_references_pinned=${allWorkflowActionReferencesPinned}`)
  console.log(`pr_workflow_token_permissions_read_only=${prWorkflowTokenPermissionsReadOnly}`)
  console.log(`release_workflow_boundary_only=${releaseWorkflowBoundaryOnly}`)
  console.log(`release_workflow_permissions_scoped=${releaseWorkflowPermissionsScoped}`)
  console.log(`dependabot_config_present=${dependabotConfigPresent}`)
  console.log(`dependabot_covers_npm=${dependabotCoversNpm}`)
  console.log(`dependabot_covers_github_actions=${dependabotCoversGitHubActions}`)
  console.log(`codeql_workflow_present=${codeqlWorkflowPresent}`)
  console.log(`codeql_actions_pinned=${codeqlActionsPinned}`)
  console.log(`codeql_hosted_execution_performed=${report.codeqlHostedExecutionPerformed}`)
  console.log(`scorecard_workflow_present=${scorecardWorkflowPresent}`)
  console.log(`scorecard_workflow_actions_pinned=${scorecardWorkflowActionsPinned}`)
  console.log(`scorecard_hosted_execution_performed=${report.scorecardHostedExecutionPerformed}`)
  console.log(`npm_provenance_configured=${npmProvenanceConfigured}`)
  console.log(`real_scorecard_run_performed=${report.realScorecardRunPerformed}`)
  console.log(`classified_unresolved_gaps=${classifiedUnresolvedGaps.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
