import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type PackageJson = {
  name: string
  version: string
  dependencies?: Record<string, string>
  devDependencies?: Record<string, string>
  engines?: Record<string, string>
}

type ReleaseArtifactFileListReport = {
  mode: string
  providerCallsPerformed: unknown[]
  liveModelCallsPerformed: unknown[]
  externalCallsPerformed: unknown[]
  packDryRunExitCode: number | null
  publishAttempted: boolean
  deployAttempted: boolean
  launchAttempted: boolean
  expectedPackageFiles: string[]
  actualPackageFiles: string[]
  forbiddenPackageFiles: string[]
  releaseArtifactChecks: Array<{
    label: string
    ok: boolean
  }>
}

type PackageFileProvenance = {
  path: string
  exists: boolean
  sizeBytes: number
  sha256: string | null
}

type SbomComponent = {
  name: string
  versionRange: string
  scope: 'runtime' | 'development'
  source: 'package.json.dependencies' | 'package.json.devDependencies'
}

type ProvenanceCheck = {
  label: string
  ok: boolean
  detail: string
}

type ReleaseArtifactProvenanceReport = {
  generatedAt: string
  mode: 'local_no_provider_release_artifact_hash_sbom_provenance'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  publishAttempted: false
  deployAttempted: false
  launchAttempted: false
  sourceReleaseArtifactReport: string
  packageName: string
  packageVersion: string
  packageFileHashes: PackageFileProvenance[]
  sbomFormat: 'local_package_json_component_inventory'
  sbomComponents: SbomComponent[]
  engineRequirements: Record<string, string>
  provenanceChecks: ProvenanceCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const releaseArtifactReportPath = 'docs/product-quality/release-artifact-file-list-report.json'

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function sha256File(path: string): string {
  return createHash('sha256').update(readFileSync(resolve(root, path))).digest('hex')
}

function check(label: string, ok: boolean, detail: string): ProvenanceCheck {
  return { label, ok, detail }
}

function buildSbomComponents(pkg: PackageJson): SbomComponent[] {
  const runtime = Object.entries(pkg.dependencies ?? {}).map(([name, versionRange]) => ({
    name,
    versionRange,
    scope: 'runtime' as const,
    source: 'package.json.dependencies' as const,
  }))
  const development = Object.entries(pkg.devDependencies ?? {}).map(([name, versionRange]) => ({
    name,
    versionRange,
    scope: 'development' as const,
    source: 'package.json.devDependencies' as const,
  }))
  return [...runtime, ...development].sort((left, right) => {
    if (left.scope !== right.scope) {
      return left.scope.localeCompare(right.scope)
    }
    return left.name.localeCompare(right.name)
  })
}

function buildFileHashes(paths: string[]): PackageFileProvenance[] {
  return paths.map((path) => {
    const absolutePath = resolve(root, path)
    if (!existsSync(absolutePath)) {
      return {
        path,
        exists: false,
        sizeBytes: 0,
        sha256: null,
      }
    }
    return {
      path,
      exists: true,
      sizeBytes: statSync(absolutePath).size,
      sha256: sha256File(path),
    }
  })
}

function writeReports(report: ReleaseArtifactProvenanceReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'release-artifact-provenance-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const runtimeCount = report.sbomComponents.filter((component) => component.scope === 'runtime').length
  const developmentCount = report.sbomComponents.filter((component) => component.scope === 'development').length
  const lines = [
    '# Release Artifact Provenance Report',
    '',
    'Generated by: `bun run product:release-provenance`',
    '',
    '## Claim Boundary',
    '',
    '- This report computes local package-file hashes and a package.json component inventory only.',
    '- It does not publish, deploy, launch, commit, push, call providers, call live models, or call external services.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- package: \`${report.packageName}@${report.packageVersion}\``,
    `- package_file_hashes: \`${report.packageFileHashes.length}\``,
    `- sbom_format: \`${report.sbomFormat}\``,
    `- sbom_component_count: \`${report.sbomComponents.length}\``,
    `- runtime_component_count: \`${runtimeCount}\``,
    `- development_component_count: \`${developmentCount}\``,
    `- publish_attempted: \`${report.publishAttempted}\``,
    `- deploy_attempted: \`${report.deployAttempted}\``,
    `- launch_attempted: \`${report.launchAttempted}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Package File Hashes',
    '',
    '| Path | Size Bytes | SHA-256 |',
    '| --- | ---: | --- |',
    ...report.packageFileHashes.map((file) => `| \`${file.path}\` | ${file.sizeBytes} | \`${file.sha256 ?? 'missing'}\` |`),
    '',
    '## SBOM-Style Component Inventory',
    '',
    `- runtime_components: \`${runtimeCount}\``,
    `- development_components: \`${developmentCount}\``,
    '- Full component inventory is recorded in the JSON report.',
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.provenanceChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'release-artifact-provenance-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const pkg = readJson<PackageJson>('package.json')
  const artifactReport = readJson<ReleaseArtifactFileListReport>(releaseArtifactReportPath)
  const packageFileHashes = buildFileHashes(artifactReport.actualPackageFiles)
  const sbomComponents = buildSbomComponents(pkg)
  const uniqueHashCount = new Set(packageFileHashes.map((file) => file.sha256).filter(Boolean)).size
  const runtimeCount = sbomComponents.filter((component) => component.scope === 'runtime').length
  const developmentCount = sbomComponents.filter((component) => component.scope === 'development').length

  const provenanceChecks = [
    check('source release artifact report is local no-provider', artifactReport.mode === 'local_no_provider_release_artifact_file_list', artifactReport.mode),
    check('source pack dry-run passed', artifactReport.packDryRunExitCode === 0, String(artifactReport.packDryRunExitCode)),
    check('source release artifact checks passed', artifactReport.releaseArtifactChecks.every((item) => item.ok), `${artifactReport.releaseArtifactChecks.filter((item) => !item.ok).length} failed`),
    check('forbidden package files absent', artifactReport.forbiddenPackageFiles.length === 0, String(artifactReport.forbiddenPackageFiles.length)),
    check('package files have local hashes', packageFileHashes.every((file) => file.exists && typeof file.sha256 === 'string' && file.sha256.length === 64), `${packageFileHashes.length} files`),
    check('package file hash set is non-empty and unique', uniqueHashCount === packageFileHashes.length && uniqueHashCount > 0, String(uniqueHashCount)),
    check('manifest hash is included', packageFileHashes.some((file) => file.path === 'package.json' && file.sha256), 'package.json'),
    check('bundle hash is included', packageFileHashes.some((file) => file.path === 'dist/cli.mjs' && file.sha256), 'dist/cli.mjs'),
    check('SBOM inventory includes runtime components', runtimeCount > 0, String(runtimeCount)),
    check('SBOM inventory includes development components', developmentCount > 0, String(developmentCount)),
    check('provider calls were not performed', artifactReport.providerCallsPerformed.length === 0, String(artifactReport.providerCallsPerformed.length)),
    check('live model calls were not performed', artifactReport.liveModelCallsPerformed.length === 0, String(artifactReport.liveModelCallsPerformed.length)),
    check('external calls were not performed', artifactReport.externalCallsPerformed.length === 0, String(artifactReport.externalCallsPerformed.length)),
    check('publish was not attempted', artifactReport.publishAttempted === false, String(artifactReport.publishAttempted)),
    check('deploy was not attempted', artifactReport.deployAttempted === false, String(artifactReport.deployAttempted)),
    check('launch was not attempted', artifactReport.launchAttempted === false, String(artifactReport.launchAttempted)),
  ]

  const report: ReleaseArtifactProvenanceReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_release_artifact_hash_sbom_provenance',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    publishAttempted: false,
    deployAttempted: false,
    launchAttempted: false,
    sourceReleaseArtifactReport: releaseArtifactReportPath,
    packageName: pkg.name,
    packageVersion: pkg.version,
    packageFileHashes,
    sbomFormat: 'local_package_json_component_inventory',
    sbomComponents,
    engineRequirements: pkg.engines ?? {},
    provenanceChecks,
    claimBoundary: 'Release artifact provenance is local hash and package.json component inventory evidence only. It does not publish, deploy, launch, call providers, or claim release readiness.',
  }

  writeReports(report)

  for (const item of provenanceChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!provenanceChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`package_file_hashes=${packageFileHashes.length}`)
  console.log(`sbom_component_count=${sbomComponents.length}`)
  console.log(`runtime_component_count=${runtimeCount}`)
  console.log(`development_component_count=${developmentCount}`)
  console.log(`publish_attempted=${report.publishAttempted}`)
  console.log(`deploy_attempted=${report.deployAttempted}`)
  console.log(`launch_attempted=${report.launchAttempted}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
