import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type PackageJson = {
  name: string
  contributes?: unknown
  activationEvents?: unknown
  main?: string
  engines?: Record<string, string>
  scripts?: Record<string, string>
}

type CandidateManifest = {
  path: string
  exists: boolean
  hasVsCodeExtensionFields: boolean
}

type IdeExtensionCheck = {
  label: string
  ok: boolean
  detail: string
}

type IdeExtensionSurfaceReport = {
  generatedAt: string
  mode: 'local_no_provider_ide_extension_surface'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  workspaceIdeExtensionStatus: 'extension_manifest_found' | 'extension_manifest_missing'
  packagingAttempted: false
  installAttempted: false
  candidateManifests: CandidateManifest[]
  packageLevelVsCodeExtensionFields: string[]
  ideExtensionChecks: IdeExtensionCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const candidateManifestPaths = [
  'package.json',
  '.vscode/package.json',
  '.vscode/extensions/package.json',
  'extensions/openclaude/package.json',
  'packages/vscode-extension/package.json',
  'packages/openclaude-vscode/package.json',
]

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function manifestHasVsCodeFields(path: string): boolean {
  if (!existsSync(resolve(root, path))) {
    return false
  }
  const manifest = readJson<PackageJson>(path)
  return Boolean(
    manifest.engines?.vscode ||
      manifest.contributes ||
      manifest.activationEvents ||
      (typeof manifest.main === 'string' && manifest.main.includes('extension')),
  )
}

function check(label: string, ok: boolean, detail: string): IdeExtensionCheck {
  return { label, ok, detail }
}

function writeReports(report: IdeExtensionSurfaceReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'ide-extension-surface-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const lines = [
    '# IDE Extension Surface Report',
    '',
    'Generated by: `bun run product:ide-extension-surface`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies local IDE/extension manifest surfaces only.',
    '- It does not package, install, publish, deploy, or launch an extension.',
    '- It does not call providers, live models, or external services.',
    '- It does not claim VS Code extension availability, release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- workspace_ide_extension_status: \`${report.workspaceIdeExtensionStatus}\``,
    `- packaging_attempted: \`${report.packagingAttempted}\``,
    `- install_attempted: \`${report.installAttempted}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Candidate Manifests',
    '',
    '| Path | Exists | VS Code Extension Fields |',
    '| --- | --- | --- |',
    ...report.candidateManifests.map((item) => (
      `| \`${item.path}\` | \`${item.exists}\` | \`${item.hasVsCodeExtensionFields}\` |`
    )),
    '',
    '## Package-Level VS Code Fields',
    '',
    report.packageLevelVsCodeExtensionFields.length > 0
      ? report.packageLevelVsCodeExtensionFields.map((field) => `- \`${field}\``).join('\n')
      : '- `none`',
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.ideExtensionChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'ide-extension-surface-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const rootPackage = readJson<PackageJson>('package.json')
  const candidateManifests = candidateManifestPaths.map((path) => ({
    path,
    exists: existsSync(resolve(root, path)),
    hasVsCodeExtensionFields: manifestHasVsCodeFields(path),
  }))
  const packageLevelVsCodeExtensionFields = [
    rootPackage.engines?.vscode ? 'engines.vscode' : '',
    rootPackage.contributes ? 'contributes' : '',
    rootPackage.activationEvents ? 'activationEvents' : '',
    typeof rootPackage.main === 'string' && rootPackage.main.includes('extension') ? 'main' : '',
  ].filter(Boolean)
  const extensionManifestFound = candidateManifests.some((item) => item.hasVsCodeExtensionFields)
  const workspaceIdeExtensionStatus = extensionManifestFound
    ? 'extension_manifest_found'
    : 'extension_manifest_missing'
  const ideExtensionChecks = [
    check('candidate manifest scan is bounded', candidateManifests.length === candidateManifestPaths.length, `${candidateManifests.length} candidates`),
    check('workspace IDE extension status is classified', ['extension_manifest_found', 'extension_manifest_missing'].includes(workspaceIdeExtensionStatus), workspaceIdeExtensionStatus),
    check('missing extension is treated as product gap, not as availability claim', workspaceIdeExtensionStatus === 'extension_manifest_missing' || extensionManifestFound, workspaceIdeExtensionStatus),
    check('root package does not silently claim VS Code extension fields', packageLevelVsCodeExtensionFields.length === 0 || extensionManifestFound, packageLevelVsCodeExtensionFields.join(', ') || 'none'),
    check('no extension packaging was attempted', true, 'script only reads package manifests'),
    check('no extension install was attempted', true, 'script only reads package manifests'),
  ]

  const report: IdeExtensionSurfaceReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_ide_extension_surface',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    workspaceIdeExtensionStatus,
    packagingAttempted: false,
    installAttempted: false,
    candidateManifests,
    packageLevelVsCodeExtensionFields,
    ideExtensionChecks,
    claimBoundary: 'IDE extension surface verification classifies local manifest availability only. It does not package, install, publish, launch, or claim VS Code extension availability.',
  }

  writeReports(report)

  for (const item of ideExtensionChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!ideExtensionChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`workspace_ide_extension_status=${workspaceIdeExtensionStatus}`)
  console.log(`packaging_attempted=${report.packagingAttempted}`)
  console.log(`install_attempted=${report.installAttempted}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
