import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type PackageJson = {
  version: string
}

type TranscriptKind = 'local_failure' | 'recovery_guidance' | 'recovery_verification'

type TerminalFailureRecoveryTranscript = {
  name: string
  kind: TranscriptKind
  command: string[]
  expectedExitCode: number
  exitCode: number | null
  stdoutSha256: string
  stderrSha256: string
  stdoutByteLength: number
  stderrByteLength: number
  requiredSubstrings: string[]
  missingSubstrings: string[]
  passed: boolean
}

type PrimarySourceInput = {
  sourceProject: string
  sourceUrl: string
  observedPattern: string
  localAbsorption: string
}

type TranscriptCheck = {
  label: string
  ok: boolean
  detail: string
}

type TerminalFailureRecoveryReport = {
  generatedAt: string
  mode: 'local_no_provider_terminal_failure_recovery_transcripts'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  capturePerformed: true
  rawOutputStored: false
  transcriptCount: number
  failureStepDetected: boolean
  recoveryGuidanceProvided: boolean
  recoveryVerificationPassed: boolean
  commandTimeoutMs: number
  transcripts: TerminalFailureRecoveryTranscript[]
  primarySourceInputs: PrimarySourceInput[]
  transcriptChecks: TranscriptCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const cliPath = resolve(root, 'dist/cli.mjs')
const packageJson = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')) as PackageJson
const commandTimeoutMs = 15_000

function normalize(text: string | Buffer | null | undefined): string {
  return String(text ?? '').replace(/\r\n/g, '\n')
}

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex')
}

function transcriptCheck(label: string, ok: boolean, detail: string): TranscriptCheck {
  return { label, ok, detail }
}

function runTranscript(
  name: string,
  kind: TranscriptKind,
  args: string[],
  expectedExitCode: number,
  requiredSubstrings: string[],
): TerminalFailureRecoveryTranscript {
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    cwd: root,
    encoding: 'utf8',
    timeout: commandTimeoutMs,
    windowsHide: true,
    env: {
      ...process.env,
      OPENCLAUDE_PRODUCT_TERMINAL_FAILURE_RECOVERY_NO_PROVIDER: '1',
      OPENCLAUDE_DISABLE_AUTO_PROVIDER_CALLS: '1',
    },
  })
  const stdout = normalize(result.stdout)
  const stderr = normalize(result.stderr)
  const combined = `${stdout}\n${stderr}`
  const missingSubstrings = requiredSubstrings.filter((substring) => !combined.includes(substring))

  return {
    name,
    kind,
    command: ['node', 'dist/cli.mjs', ...args],
    expectedExitCode,
    exitCode: result.status,
    stdoutSha256: sha256(stdout),
    stderrSha256: sha256(stderr),
    stdoutByteLength: Buffer.byteLength(stdout, 'utf8'),
    stderrByteLength: Buffer.byteLength(stderr, 'utf8'),
    requiredSubstrings,
    missingSubstrings,
    passed: result.status === expectedExitCode && missingSubstrings.length === 0 && !result.error,
  }
}

function writeReports(report: TerminalFailureRecoveryReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'terminal-failure-recovery-transcripts-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const transcriptRows = report.transcripts
    .map((transcript) => (
      `| \`${transcript.name}\` | \`${transcript.kind}\` | \`${transcript.command.join(' ')}\` | \`${transcript.exitCode}\` | \`${transcript.expectedExitCode}\` | \`${transcript.passed}\` | \`${transcript.stdoutSha256}\` | \`${transcript.stderrSha256}\` |`
    ))
    .join('\n')
  const sourceRows = report.primarySourceInputs
    .map((source) => `| ${source.sourceProject} | ${source.sourceUrl} | ${source.observedPattern} | ${source.localAbsorption} |`)
    .join('\n')
  const checkRows = report.transcriptChecks
    .map((check) => `| ${check.label} | \`${check.ok}\` | ${check.detail} |`)
    .join('\n')

  const markdown = `# Terminal Failure Recovery Transcripts

Generated by: \`bun run product:terminal-failure-recovery-transcripts\`

## Claim Boundary

- This report records local CLI failure and recovery transcript evidence only.
- It stores stdout and stderr as SHA-256 hashes and byte counts, not raw command output.
- It does not call providers, live models, external services, dependency installers, VS Code repair flows, or protected systems.
- It does not claim release readiness, production readiness, public readiness, external validation, benchmark superiority, or autonomous reliability.

## Summary

- capture_performed: \`${report.capturePerformed}\`
- raw_output_stored: \`${report.rawOutputStored}\`
- transcript_count: \`${report.transcriptCount}\`
- failure_step_detected: \`${report.failureStepDetected}\`
- recovery_guidance_provided: \`${report.recoveryGuidanceProvided}\`
- recovery_verification_passed: \`${report.recoveryVerificationPassed}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`

## Primary Source Inputs

| Source | URL | Observed Pattern | Local Absorption |
| --- | --- | --- | --- |
${sourceRows}

## Transcript Hashes

| Name | Kind | Command | Exit | Expected Exit | Passed | Stdout SHA-256 | Stderr SHA-256 |
| --- | --- | --- | ---: | ---: | --- | --- | --- |
${transcriptRows}

## Checks

| Check | OK | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'terminal-failure-recovery-transcripts-report.md'), markdown)
}

function main(): void {
  if (!existsSync(cliPath)) {
    console.error('RESULT: FAIL')
    console.error(`missing built CLI: ${cliPath}`)
    console.error('Run `bun run smoke` or `bun run build` before terminal failure recovery transcripts.')
    process.exit(1)
  }

  const transcripts = [
    runTranscript(
      'unknown_flag_local_failure',
      'local_failure',
      ['--unknown-openclaude-flag'],
      1,
      ['unknown option'],
    ),
    runTranscript(
      'help_recovery_guidance',
      'recovery_guidance',
      ['--help'],
      0,
      ['Usage: claude', '--provider <provider>', '--permission-mode <mode>', 'doctor'],
    ),
    runTranscript(
      'doctor_help_recovery_guidance',
      'recovery_guidance',
      ['doctor', '--help'],
      0,
      ['Usage: claude doctor', 'Display help for command'],
    ),
    runTranscript(
      'version_recovery_verification',
      'recovery_verification',
      ['--version'],
      0,
      [`${packageJson.version} (Open Claude)`],
    ),
  ]

  const failureStepDetected = transcripts.some((transcript) => transcript.kind === 'local_failure' && transcript.passed)
  const recoveryGuidanceProvided = transcripts
    .filter((transcript) => transcript.kind === 'recovery_guidance')
    .every((transcript) => transcript.passed)
  const recoveryVerificationPassed = transcripts.some((transcript) => transcript.kind === 'recovery_verification' && transcript.passed)

  const transcriptChecks = [
    transcriptCheck('expected local failure is captured', failureStepDetected, transcripts.map((item) => `${item.name}:${item.exitCode}`).join(',')),
    transcriptCheck('help and doctor recovery commands pass', recoveryGuidanceProvided, transcripts.filter((item) => item.kind === 'recovery_guidance').map((item) => item.name).join(',')),
    transcriptCheck('version recovery verification passes', recoveryVerificationPassed, transcripts.filter((item) => item.kind === 'recovery_verification').map((item) => item.name).join(',')),
    transcriptCheck('raw output is hash-only in report', true, 'stdout/stderr stored as SHA-256 and byte counts only'),
    transcriptCheck('all transcript commands avoid provider prompt path', transcripts.every((item) => item.command.includes('--unknown-openclaude-flag') || item.command.includes('--help') || item.command.includes('--version')), transcripts.map((item) => item.command.join(' ')).join(' | ')),
    transcriptCheck('provider live external and protected action counts are zero', true, 'no provider/live/external/protected actions are performed by this script'),
  ]

  const report: TerminalFailureRecoveryReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_terminal_failure_recovery_transcripts',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    capturePerformed: true,
    rawOutputStored: false,
    transcriptCount: transcripts.length,
    failureStepDetected,
    recoveryGuidanceProvided,
    recoveryVerificationPassed,
    commandTimeoutMs,
    transcripts,
    primarySourceInputs: [
      {
        sourceProject: 'anomalyco/opencode',
        sourceUrl: 'https://github.com/anomalyco/opencode',
        observedPattern: 'OpenCode separates read-only planning from full-access build behavior and asks before risky command execution.',
        localAbsorption: 'OpenClaude records local failure and recovery transcript evidence without escalating into provider prompts or protected actions.',
      },
      {
        sourceProject: 'warpdotdev/warp',
        sourceUrl: 'https://github.com/warpdotdev/warp',
        observedPattern: 'Warp positions the terminal as an agentic development surface with auditable command workflows.',
        localAbsorption: 'OpenClaude keeps terminal failure and recovery flows hash-addressed and auditable in product-quality evidence.',
      },
      {
        sourceProject: 'openai/codex',
        sourceUrl: 'https://github.com/openai/codex',
        observedPattern: 'Codex CLI emphasizes local terminal operation, quickstart commands, approval boundaries, and inspectable command logs.',
        localAbsorption: 'OpenClaude verifies a local failed command, help recovery, doctor handoff, and version recovery without external validation claims.',
      },
    ],
    transcriptChecks,
    claimBoundary: 'Terminal failure recovery transcripts are local no-provider product-quality evidence only. They do not prove release readiness, public readiness, production readiness, external validation, benchmark superiority, or autonomous reliability.',
  }

  writeReports(report)

  for (const check of transcriptChecks) {
    console.log(`${check.ok ? 'PASS' : 'FAIL'}: ${check.label} (${check.detail})`)
  }

  console.log('')
  if (!transcriptChecks.every((check) => check.ok) || !transcripts.every((transcript) => transcript.passed)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`terminal_failure_recovery_transcript_count=${report.transcriptCount}`)
  console.log(`failure_step_detected=${report.failureStepDetected}`)
  console.log(`recovery_guidance_provided=${report.recoveryGuidanceProvided}`)
  console.log(`recovery_verification_passed=${report.recoveryVerificationPassed}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
  console.log(`protected_actions_executed=${report.protectedActionsExecuted.length}`)
}

main()
