import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type IdeExtensionSurfaceReport = {
  workspaceIdeExtensionStatus: 'extension_manifest_found' | 'extension_manifest_missing'
  packagingAttempted: boolean
  installAttempted: boolean
}

type ScopeCheck = {
  label: string
  ok: boolean
  detail: string
}

type IdeExtensionScopeReport = {
  generatedAt: string
  mode: 'local_no_provider_ide_extension_scope'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  sourceSurfaceStatus: IdeExtensionSurfaceReport['workspaceIdeExtensionStatus']
  scopeDecision: 'scope_extension_before_implementation_no_availability_claim' | 'manifest_surface_detected_availability_claim_blocked_until_smoke'
  proposedManifestPath: 'packages/openclaude-vscode/package.json'
  primarySourceInputs: Array<{
    sourceProject: string
    sourceUrl: string
    observedPattern: string
  }>
  minimumManifestRequirements: string[]
  contributionPlan: {
    commands: string[]
    views: string[]
    configurationKeys: string[]
    activationEvents: string[]
  }
  validationRequiredBeforeAvailabilityClaim: string[]
  protectedActions: {
    packagingAttempted: false
    installAttempted: false
    publishAttempted: false
    providerCallsAllowed: false
    externalCallsAllowed: false
  }
  scopeChecks: ScopeCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const surfaceReportPath = 'docs/product-quality/ide-extension-surface-report.json'

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function check(label: string, ok: boolean, detail: string): ScopeCheck {
  return { label, ok, detail }
}

function writeReports(report: IdeExtensionScopeReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(resolve(docsDir, 'ide-extension-scope-report.json'), `${JSON.stringify(report, null, 2)}\n`)

  const lines = [
    '# IDE Extension Scope Report',
    '',
    'Generated by: `bun run product:ide-extension-scope`',
    '',
    '## Claim Boundary',
    '',
    '- This report scopes a future VS Code extension surface only.',
    '- It does not create, package, install, publish, deploy, or launch an extension.',
    '- It does not call providers, live models, or external services.',
    '- It does not claim VS Code extension availability, release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- source_surface_status: \`${report.sourceSurfaceStatus}\``,
    `- scope_decision: \`${report.scopeDecision}\``,
    `- proposed_manifest_path: \`${report.proposedManifestPath}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Primary Source Inputs',
    '',
    '| Source | URL | Observed Pattern |',
    '| --- | --- | --- |',
    ...report.primarySourceInputs.map((item) => (
      `| ${item.sourceProject} | ${item.sourceUrl} | ${item.observedPattern} |`
    )),
    '',
    '## Minimum Manifest Requirements',
    '',
    ...report.minimumManifestRequirements.map((item) => `- \`${item}\``),
    '',
    '## Contribution Plan',
    '',
    `- commands: ${report.contributionPlan.commands.map((item) => `\`${item}\``).join(', ')}`,
    `- views: ${report.contributionPlan.views.map((item) => `\`${item}\``).join(', ')}`,
    `- configuration_keys: ${report.contributionPlan.configurationKeys.map((item) => `\`${item}\``).join(', ')}`,
    `- activation_events: ${report.contributionPlan.activationEvents.map((item) => `\`${item}\``).join(', ')}`,
    '',
    '## Validation Required Before Availability Claim',
    '',
    ...report.validationRequiredBeforeAvailabilityClaim.map((item) => `- ${item}`),
    '',
    '## Protected Actions',
    '',
    `- packaging_attempted: \`${report.protectedActions.packagingAttempted}\``,
    `- install_attempted: \`${report.protectedActions.installAttempted}\``,
    `- publish_attempted: \`${report.protectedActions.publishAttempted}\``,
    `- provider_calls_allowed: \`${report.protectedActions.providerCallsAllowed}\``,
    `- external_calls_allowed: \`${report.protectedActions.externalCallsAllowed}\``,
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.scopeChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'ide-extension-scope-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const surface = readJson<IdeExtensionSurfaceReport>(surfaceReportPath)
  const scopeDecision = surface.workspaceIdeExtensionStatus === 'extension_manifest_found'
    ? 'manifest_surface_detected_availability_claim_blocked_until_smoke'
    : 'scope_extension_before_implementation_no_availability_claim'
  const primarySourceInputs = [
    {
      sourceProject: 'continuedev/continue',
      sourceUrl: 'https://github.com/continuedev/continue/blob/main/extensions/vscode/package.json',
      observedPattern: 'Dedicated VS Code extension manifest with engines.vscode, extensionKind, activationEvents, main entry point, commands, configuration, and view contributions.',
    },
    {
      sourceProject: 'cline/cline',
      sourceUrl: 'https://github.com/cline/cline/blob/main/package.json',
      observedPattern: 'AI coding assistant is distributed through a VS Code extension manifest with activation events, extension entry point, and contributed workbench surfaces.',
    },
    {
      sourceProject: 'microsoft/vscode-docs',
      sourceUrl: 'https://code.visualstudio.com/api/references/extension-manifest',
      observedPattern: 'VS Code treats package.json extension manifest fields such as engines.vscode, main, contributes, and activationEvents as the authoritative extension surface.',
    },
    {
      sourceProject: 'microsoft/vscode-docs',
      sourceUrl: 'https://code.visualstudio.com/api/references/contribution-points',
      observedPattern: 'Contribution points are JSON declarations in package.json contributes, covering commands, configuration, views, menus, keybindings, languages, and related workbench integration.',
    },
  ]
  const minimumManifestRequirements = [
    'name',
    'displayName',
    'publisher',
    'version',
    'engines.vscode',
    'extensionKind',
    'main',
    'activationEvents',
    'contributes',
  ]
  const contributionPlan = {
    commands: [
      'openclaude.openChat',
      'openclaude.runSelection',
      'openclaude.explainSelection',
      'openclaude.openRuntimeDoctor',
    ],
    views: [
      'openclaude.chatView',
      'openclaude.traceEvidenceView',
    ],
    configurationKeys: [
      'openclaude.providerProfile',
      'openclaude.permissionMode',
      'openclaude.telemetryAllowed',
      'openclaude.traceCaptureEnabled',
    ],
    activationEvents: [
      'onCommand:openclaude.openChat',
      'onCommand:openclaude.runSelection',
      'onView:openclaude.chatView',
    ],
  }
  const validationRequiredBeforeAvailabilityClaim = [
    'Create the proposed manifest and extension entry point under packages/openclaude-vscode.',
    'Run a local manifest schema check for engines.vscode, activationEvents, contributes.commands, contributes.views, contributes.configuration, and extensionKind.',
    'Run a local extension package dry-run without publishing or marketplace upload.',
    'Run a no-phone-home check over the extension bundle and generated package.',
    'Run local command-contribution smoke tests for open chat, run selection, explain selection, and runtime doctor commands.',
    'Record provider/live/external call boundaries before any demo, marketplace, or public availability claim.',
  ]
  const protectedActions = {
    packagingAttempted: false,
    installAttempted: false,
    publishAttempted: false,
    providerCallsAllowed: false,
    externalCallsAllowed: false,
  } as const
  const scopeChecks = [
    check('source surface report exists and is bounded', surface.packagingAttempted === false && surface.installAttempted === false, surface.workspaceIdeExtensionStatus),
    check('primary source inputs cover competitor and official manifest evidence', primarySourceInputs.length >= 3, `${primarySourceInputs.length} sources`),
    check('manifest requirements include VS Code authority fields', ['engines.vscode', 'main', 'activationEvents', 'contributes', 'extensionKind'].every((item) => minimumManifestRequirements.includes(item)), minimumManifestRequirements.join(', ')),
    check('contribution plan covers commands, views, configuration, and activation', contributionPlan.commands.length >= 3 && contributionPlan.views.length >= 1 && contributionPlan.configurationKeys.length >= 3 && contributionPlan.activationEvents.length >= 2, 'commands/views/configuration/activation covered'),
    check('availability claim remains blocked until validation evidence exists', validationRequiredBeforeAvailabilityClaim.length >= 5, `${validationRequiredBeforeAvailabilityClaim.length} validation items`),
    check('protected actions were not attempted or authorized', Object.values(protectedActions).every((value) => value === false), 'all protected action flags false'),
  ]
  const report: IdeExtensionScopeReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_ide_extension_scope',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    sourceSurfaceStatus: surface.workspaceIdeExtensionStatus,
    scopeDecision,
    proposedManifestPath: 'packages/openclaude-vscode/package.json',
    primarySourceInputs,
    minimumManifestRequirements,
    contributionPlan,
    validationRequiredBeforeAvailabilityClaim,
    protectedActions,
    scopeChecks,
    claimBoundary: 'IDE extension scope evidence is internal and no-provider. It scopes a future VS Code extension surface but does not create, package, install, publish, launch, or claim extension availability.',
  }

  writeReports(report)

  for (const item of scopeChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!scopeChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`source_surface_status=${report.sourceSurfaceStatus}`)
  console.log(`scope_decision=${report.scopeDecision}`)
  console.log(`primary_source_inputs=${report.primarySourceInputs.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
