import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { scrubPublicArtifactText, scrubPublicArtifactValue } from './product-report-sanitizer'

type PackageJson = {
  name: string
  version: string
  bin?: Record<string, string>
  files?: string[]
  scripts?: Record<string, string>
  repository?: {
    type?: string
    url?: string
  }
  publishConfig?: {
    access?: string
  }
}

type GitCommand = {
  name: string
  command: string[]
  exitCode: number | null
  stdoutPreview: string[]
  stderrPreview: string[]
}

type HygieneCheck = {
  label: string
  ok: boolean
  detail: string
}

type GitReleaseHygieneReport = {
  generatedAt: string
  mode: 'local_no_provider_git_release_hygiene'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  workspaceGitStatus: 'git_repo_detected' | 'blocked_by_no_git_repo' | 'git_unavailable'
  repoRoot: string | null
  commitPushAttempted: false
  releaseActionPerformed: false
  protectedActionsPerformed: []
  gitCommands: GitCommand[]
  releaseHygieneChecks: HygieneCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function preview(text: string | Buffer | null | undefined): string[] {
  return String(text ?? '')
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .slice(0, 40)
}

function runGit(name: string, args: string[]): GitCommand {
  const result = spawnSync('git', args, {
    cwd: root,
    encoding: 'utf8',
    shell: true,
  })
  return {
    name,
    command: ['git', ...args],
    exitCode: result.status,
    stdoutPreview: preview(result.stdout),
    stderrPreview: preview(result.stderr),
  }
}

export function sanitizeGitCommandForPublicReport(command: GitCommand): GitCommand {
  if (command.name !== 'status_short') {
    return command
  }
  const entryCount = command.stdoutPreview.length
  return {
    ...command,
    stdoutPreview: entryCount > 0 ? [`<git-status-short: ${entryCount} entries>`] : [],
  }
}

function check(label: string, ok: boolean, detail: string): HygieneCheck {
  return { label, ok, detail }
}

function classifyGitStatus(revParse: GitCommand): GitReleaseHygieneReport['workspaceGitStatus'] {
  if (revParse.exitCode === 0 && revParse.stdoutPreview.length > 0) {
    return 'git_repo_detected'
  }
  const combined = [...revParse.stdoutPreview, ...revParse.stderrPreview].join('\n').toLowerCase()
  if (combined.includes('not a git repository')) {
    return 'blocked_by_no_git_repo'
  }
  return 'git_unavailable'
}

function writeReports(report: GitReleaseHygieneReport): void {
  mkdirSync(docsDir, { recursive: true })
  const publicReport = scrubPublicArtifactValue({
    ...report,
    gitCommands: report.gitCommands.map(sanitizeGitCommandForPublicReport),
  })
  writeFileSync(
    resolve(docsDir, 'git-release-hygiene-report.json'),
    `${JSON.stringify(publicReport, null, 2)}\n`,
  )

  const lines = [
    '# Git Release Hygiene Report',
    '',
    'Generated by: `bun run product:git-release-hygiene`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies local Git/release hygiene surfaces only.',
    '- It does not commit, push, publish, deploy, or launch.',
    '- It does not call providers, live models, or external services.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- workspace_git_status: \`${report.workspaceGitStatus}\``,
    `- repo_root: \`${report.repoRoot ?? 'null'}\``,
    `- commit_push_attempted: \`${report.commitPushAttempted}\``,
    `- release_action_performed: \`${report.releaseActionPerformed}\``,
    `- protected_actions_performed: \`${report.protectedActionsPerformed.length}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Git Commands',
    '',
    '| Command | Exit | Stdout | Stderr |',
    '| --- | ---: | --- | --- |',
    ...publicReport.gitCommands.map((item) => (
      `| \`${item.command.join(' ')}\` | ${item.exitCode ?? 'null'} | ${item.stdoutPreview.map((line) => `\`${line}\``).join('<br>') || '`none`'} | ${item.stderrPreview.map((line) => `\`${line}\``).join('<br>') || '`none`'} |`
    )),
    '',
    '## Hygiene Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.releaseHygieneChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'git-release-hygiene-report.md'), `${scrubPublicArtifactText(lines.join('\n'))}\n`)
}

function main(): void {
  const pkg = readJson<PackageJson>('package.json')
  const revParse = runGit('repo_root', ['rev-parse', '--show-toplevel'])
  const status = runGit('status_short', ['status', '--short'])
  const remote = runGit('remote_verbose', ['remote', '-v'])
  const workspaceGitStatus = classifyGitStatus(revParse)
  const repoRoot = workspaceGitStatus === 'git_repo_detected' ? revParse.stdoutPreview[0] ?? null : null
  const packageFiles = pkg.files ?? []
  const packageScripts = pkg.scripts ?? {}
  const releaseHygieneChecks = [
    check('git root command was classified', ['git_repo_detected', 'blocked_by_no_git_repo', 'git_unavailable'].includes(workspaceGitStatus), workspaceGitStatus),
    check('no commit or push was attempted', true, 'script only runs rev-parse, status, and remote inspection'),
    check('no release action was performed', true, 'script does not run npm publish, deploy, launch, commit, or push commands'),
    check('package repository metadata exists', pkg.repository?.type === 'git' && typeof pkg.repository.url === 'string', pkg.repository?.url ?? 'missing'),
    check('package bin exposes openclaude', typeof pkg.bin?.openclaude === 'string', pkg.bin?.openclaude ?? 'missing'),
    check('package file list includes built CLI', packageFiles.includes('dist/cli.mjs'), packageFiles.join(', ')),
    check('package file list includes Unix launcher', packageFiles.includes('bin/openclaude'), packageFiles.join(', ')),
    check('package file list includes Windows launcher', packageFiles.includes('bin/openclaude.cmd'), packageFiles.join(', ')),
    check('package file list includes README', packageFiles.includes('README.md'), packageFiles.join(', ')),
    check('prepack rebuilds package artifact', typeof packageScripts.prepack === 'string' && packageScripts.prepack.includes('build'), packageScripts.prepack ?? 'missing'),
    check('publish config is explicit', pkg.publishConfig?.access === 'public', pkg.publishConfig?.access ?? 'missing'),
    check('non-repo workspace is recorded as blocked instead of ignored', workspaceGitStatus !== 'git_unavailable', workspaceGitStatus),
  ]

  const report: GitReleaseHygieneReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_git_release_hygiene',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    workspaceGitStatus,
    repoRoot,
    commitPushAttempted: false,
    releaseActionPerformed: false,
    protectedActionsPerformed: [],
    gitCommands: [revParse, status, remote],
    releaseHygieneChecks,
    claimBoundary: 'Git release hygiene verifies local repo/package release surfaces only. It does not commit, push, publish, deploy, launch, or claim release readiness.',
  }

  writeReports(report)

  for (const item of releaseHygieneChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!releaseHygieneChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`workspace_git_status=${workspaceGitStatus}`)
  console.log(`repo_root=${repoRoot ?? 'null'}`)
  console.log(`commit_push_attempted=${report.commitPushAttempted}`)
  console.log(`release_action_performed=${report.releaseActionPerformed}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

if (import.meta.main) {
  main()
}
