import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type Check = {
  label: string
  ok: boolean
  detail: string
}

type SourceInput = {
  sourceProject: string
  sourceUrl: string
  observedPattern: string
  localAbsorption: string
}

type TemplateSummary = {
  path: string
  sha256: string
  requiredSectionsPresent: string[]
  requiredTermsPresent: string[]
}

type CommunityIntakeQualityReport = {
  generatedAt: string
  mode: 'local_no_provider_community_intake_quality'
  primarySourceInputs: SourceInput[]
  sourceTemplatePaths: string[]
  sourceTemplateSha256: Record<string, string>
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  externalTemplateValidationPerformed: false
  blankIssuesEnabled: boolean
  issueTemplateChooserConfigured: boolean
  bugReportTemplate: TemplateSummary
  featureRequestTemplate: TemplateSummary
  pullRequestTemplate: TemplateSummary
  securityPolicyLinkedOrPresent: boolean
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  claimBoundary: string
  communityIntakeChecks: Check[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const templatePaths = {
  bug: '.github/ISSUE_TEMPLATE/bug_report.md',
  feature: '.github/ISSUE_TEMPLATE/feature_request.md',
  config: '.github/ISSUE_TEMPLATE/config.yml',
  pr: '.github/pull_request_template.md',
  security: 'SECURITY.md',
}

function sha256(input: string | Buffer): string {
  return createHash('sha256').update(input).digest('hex')
}

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function fileSha256(path: string): string {
  return sha256(readFileSync(resolve(root, path)))
}

function check(label: string, ok: boolean, detail: string): Check {
  return { label, ok, detail }
}

function includesAll(text: string, terms: string[]): string[] {
  const lower = text.toLowerCase()
  return terms.filter((term) => lower.includes(term.toLowerCase()))
}

function markdownHeadings(text: string): string[] {
  return Array.from(text.matchAll(/^##\s+(.+)$/gm), (match) => match[1]?.trim() ?? '')
}

function templateSummary(path: string, requiredSections: string[], requiredTerms: string[]): TemplateSummary {
  const text = readText(path)
  const headings = markdownHeadings(text)
  const requiredSectionsPresent = requiredSections.filter((section) => headings.includes(section))
  const requiredTermsPresent = includesAll(text, requiredTerms)
  return {
    path,
    sha256: fileSha256(path),
    requiredSectionsPresent,
    requiredTermsPresent,
  }
}

function parseBlankIssuesEnabled(configText: string): boolean {
  const match = configText.match(/^blank_issues_enabled:\s*(true|false)\s*$/m)
  return match?.[1] === 'true'
}

function writeMarkdown(report: CommunityIntakeQualityReport): void {
  const sourceRows = report.primarySourceInputs
    .map((source) => `| ${source.sourceProject} | ${source.sourceUrl} | ${source.localAbsorption} |`)
    .join('\n')
  const templateRows = [
    report.bugReportTemplate,
    report.featureRequestTemplate,
    report.pullRequestTemplate,
  ]
    .map((template) => `| \`${template.path}\` | \`${template.sha256}\` | ${template.requiredSectionsPresent.join(', ')} | ${template.requiredTermsPresent.join(', ')} |`)
    .join('\n')
  const checkRows = report.communityIntakeChecks
    .map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`)
    .join('\n')

  const markdown = `# Community Intake Quality Report

Generated by: \`bun run product:community-intake-quality\`

## Claim Boundary

- This report verifies local GitHub issue and pull-request intake templates only.
- It uses official GitHub documentation patterns for issue templates, template chooser configuration, and pull request templates.
- It does not call providers, live models, external services, or GitHub APIs.
- It does not install dependencies, publish, deploy, launch, modify production systems, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.

## Summary

- mode: \`${report.mode}\`
- source_template_count: \`${report.sourceTemplatePaths.length}\`
- blank_issues_enabled: \`${report.blankIssuesEnabled}\`
- issue_template_chooser_configured: \`${report.issueTemplateChooserConfigured}\`
- security_policy_linked_or_present: \`${report.securityPolicyLinkedOrPresent}\`
- external_template_validation_performed: \`${report.externalTemplateValidationPerformed}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`
- release_readiness_claim_allowed: \`${report.releaseReadinessClaimAllowed}\`
- production_readiness_claim_allowed: \`${report.productionReadinessClaimAllowed}\`
- public_readiness_claim_allowed: \`${report.publicReadinessClaimAllowed}\`
- external_validation_claim_allowed: \`${report.externalValidationClaimAllowed}\`
- autonomous_reliability_claim_allowed: \`${report.autonomousReliabilityClaimAllowed}\`

## Primary Sources

| Source | URL | Local Absorption |
| --- | --- | --- |
${sourceRows}

## Template Evidence

| Template | SHA-256 | Required Sections Present | Required Terms Present |
| --- | --- | --- | --- |
${templateRows}

## Checks

| Check | Result | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'community-intake-quality-report.md'), markdown)
}

function main(): void {
  mkdirSync(docsDir, { recursive: true })

  const sourceTemplatePaths = Object.values(templatePaths)
  const sourceTemplateSha256: Record<string, string> = {}
  for (const path of sourceTemplatePaths) {
    if (existsSync(resolve(root, path))) {
      sourceTemplateSha256[path] = fileSha256(path)
    }
  }

  const bugReportTemplate = templateSummary(
    templatePaths.bug,
    ['Summary', 'Steps to Reproduce', 'Expected Behavior', 'Actual Behavior', 'Environment', 'Logs / Screenshots', 'Verification / Safety Boundary', 'Additional Context'],
    ['[Bug]:', 'bug, triage', 'redact', 'secrets', 'provider/live model calls', 'protected systems', 'readiness claim'],
  )
  const featureRequestTemplate = templateSummary(
    templatePaths.feature,
    ['Summary', 'Problem', 'Proposed Direction', 'Alternatives Considered', 'Prior Art / Primary Sources', 'Claim Boundary / Protected Actions', 'Additional Context'],
    ['[Feature]:', 'enhancement, triage', 'primary sources', 'official docs', 'protected actions', 'bounded internal no-provider planning'],
  )
  const pullRequestTemplate = templateSummary(
    templatePaths.pr,
    ['Summary', 'Impact', 'Testing', 'Evidence / Claim Boundary', 'Notes'],
    ['bun run build', 'bun run smoke', 'bun run product:quality', 'bun run verify:privacy', 'evidence files', 'release readiness', 'provider-backed execution', 'redacted credentials'],
  )
  const configText = readText(templatePaths.config)
  const blankIssuesEnabled = parseBlankIssuesEnabled(configText)
  const issueTemplateChooserConfigured = configText.includes('contact_links:') && !blankIssuesEnabled

  const report: CommunityIntakeQualityReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_community_intake_quality',
    primarySourceInputs: [
      {
        sourceProject: 'GitHub Docs issue templates',
        sourceUrl: 'https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository',
        observedPattern: 'Repositories can configure bug and feature templates plus a template chooser to encourage structured issues.',
        localAbsorption: 'OpenClaude bug and feature templates now require reproducibility, prior-art, secret-redaction, protected-action, and claim-boundary fields.',
      },
      {
        sourceProject: 'GitHub Docs pull request standardization',
        sourceUrl: 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/managing-and-standardizing-pull-requests',
        observedPattern: 'Pull request templates standardize the information contributors provide before maintainers review or merge changes.',
        localAbsorption: 'OpenClaude PR template now requires product-quality/privacy verification, evidence references, claim boundaries, protected-action non-execution, and redaction checks.',
      },
      {
        sourceProject: 'GitHub Docs issue forms syntax',
        sourceUrl: 'https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms',
        observedPattern: 'Structured issue forms turn contributor input into consistent markdown fields and are configured under .github/ISSUE_TEMPLATE.',
        localAbsorption: 'This local gate checks required intake sections even though OpenClaude currently uses markdown templates rather than YAML issue forms.',
      },
    ],
    sourceTemplatePaths,
    sourceTemplateSha256,
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    externalTemplateValidationPerformed: false,
    blankIssuesEnabled,
    issueTemplateChooserConfigured,
    bugReportTemplate,
    featureRequestTemplate,
    pullRequestTemplate,
    securityPolicyLinkedOrPresent: existsSync(resolve(root, templatePaths.security)),
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    claimBoundary: 'Community intake quality evidence only; this does not authorize release, production, public, external-validation, provider-backed, live-model, or autonomous-reliability claims.',
    communityIntakeChecks: [],
  }

  report.communityIntakeChecks = [
    check('all community intake templates exist', sourceTemplatePaths.every((path) => existsSync(resolve(root, path))), sourceTemplatePaths.join(',')),
    check('issue template chooser discourages blank issues', report.issueTemplateChooserConfigured && report.blankIssuesEnabled === false, `blank_issues_enabled=${report.blankIssuesEnabled}`),
    check('bug report template captures reproducible evidence and safety boundary', bugReportTemplate.requiredSectionsPresent.length === 8 && bugReportTemplate.requiredTermsPresent.length === 7, `${bugReportTemplate.requiredSectionsPresent.length}/8 sections, ${bugReportTemplate.requiredTermsPresent.length}/7 terms`),
    check('feature request template captures prior art and protected action boundary', featureRequestTemplate.requiredSectionsPresent.length === 7 && featureRequestTemplate.requiredTermsPresent.length === 6, `${featureRequestTemplate.requiredSectionsPresent.length}/7 sections, ${featureRequestTemplate.requiredTermsPresent.length}/6 terms`),
    check('pull request template requires product-quality privacy evidence and claim boundaries', pullRequestTemplate.requiredSectionsPresent.length === 5 && pullRequestTemplate.requiredTermsPresent.length === 8, `${pullRequestTemplate.requiredSectionsPresent.length}/5 sections, ${pullRequestTemplate.requiredTermsPresent.length}/8 terms`),
    check('security policy exists for sensitive reports', report.securityPolicyLinkedOrPresent, templatePaths.security),
    check('primary-source inputs are official GitHub documentation', report.primarySourceInputs.every((source) => source.sourceUrl.startsWith('https://docs.github.com/')), report.primarySourceInputs.map((source) => source.sourceUrl).join(',')),
    check('external template validation remains blocked', report.externalTemplateValidationPerformed === false, 'local file validation only'),
    check('provider live external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all call arrays empty'),
    check('protected actions remain absent', report.protectedActionsExecuted.length === 0, 'zero'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all false'),
  ]

  writeFileSync(resolve(docsDir, 'community-intake-quality-report.json'), `${JSON.stringify(report, null, 2)}\n`)
  writeMarkdown(report)

  for (const item of report.communityIntakeChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  const failed = report.communityIntakeChecks.filter((item) => !item.ok)
  if (failed.length > 0) {
    console.error(`RESULT: FAIL (${failed.length} failed checks)`)
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`source_template_count=${report.sourceTemplatePaths.length}`)
  console.log(`blank_issues_enabled=${report.blankIssuesEnabled}`)
  console.log(`issue_template_chooser_configured=${report.issueTemplateChooserConfigured}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
