import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type ScopeReport = {
  proposedManifestPath: string
  contributionPlan: {
    commands: string[]
    views: string[]
    configurationKeys: string[]
    activationEvents: string[]
  }
}

type Manifest = {
  name?: string
  displayName?: string
  publisher?: string
  engines?: {
    vscode?: string
  }
  extensionKind?: string[]
  main?: string
  activationEvents?: string[]
  contributes?: {
    commands?: Array<{ command?: string }>
    views?: Record<string, Array<{ id?: string; type?: string }>>
    configuration?: {
      properties?: Record<string, unknown>
    }
  }
}

type SmokeCheck = {
  label: string
  ok: boolean
  detail: string
}

type PackFile = {
  path?: string
}

type PackResult = {
  files?: PackFile[]
}

type SmokeReport = {
  generatedAt: string
  mode: 'local_no_provider_ide_extension_manifest_smoke'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  manifestPath: string
  entryPointPath: string
  packageDryRunExitCode: number | null
  installAttempted: false
  publishAttempted: false
  deployAttempted: false
  launchAttempted: false
  extensionAvailabilityClaimAllowed: false
  manifestSummary: {
    name: string
    displayName: string
    publisher: string
    enginesVscode: string
    extensionKind: string[]
    main: string
    activationEvents: string[]
    commandIds: string[]
    viewIds: string[]
    treeViewIds: string[]
    webviewViewIds: string[]
    configurationKeys: string[]
  }
  packageDryRunFiles: string[]
  manifestSmokeChecks: SmokeCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const extensionDir = resolve(root, 'packages/openclaude-vscode')
const manifestPath = 'packages/openclaude-vscode/package.json'
const entryPointPath = 'packages/openclaude-vscode/dist/extension.js'

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function check(label: string, ok: boolean, detail: string): SmokeCheck {
  return { label, ok, detail }
}

function flattenViewIds(views: Manifest['contributes'] extends object ? Manifest['contributes']['views'] : never): string[] {
  if (!views) {
    return []
  }

  return Object.values(views).flatMap((items) => items.map((item) => item.id).filter((id): id is string => typeof id === 'string'))
}

function flattenTreeViewIds(views: Manifest['contributes'] extends object ? Manifest['contributes']['views'] : never): string[] {
  if (!views) {
    return []
  }

  return Object.values(views)
    .flat()
    .filter((item) => item.type !== 'webview')
    .map((item) => item.id)
    .filter((id): id is string => typeof id === 'string')
}

function flattenWebviewViewIds(views: Manifest['contributes'] extends object ? Manifest['contributes']['views'] : never): string[] {
  if (!views) {
    return []
  }

  return Object.values(views)
    .flat()
    .filter((item) => item.type === 'webview')
    .map((item) => item.id)
    .filter((id): id is string => typeof id === 'string')
}

function parsePackFiles(stdout: string): string[] {
  const trimmed = stdout.trim()
  if (!trimmed) {
    return []
  }

  const jsonStart = trimmed.indexOf('[')
  const payload = jsonStart >= 0 ? trimmed.slice(jsonStart) : trimmed
  const parsed = JSON.parse(payload) as PackResult[]
  const files = parsed.flatMap((item) => item.files ?? [])
  return files.map((file) => file.path).filter((path): path is string => typeof path === 'string')
}

function runPackageDryRun(): { exitCode: number | null; files: string[]; parseError: string | null } {
  const npmCommand = process.platform === 'win32' ? 'npm.cmd' : 'npm'
  const result = spawnSync(npmCommand, ['pack', '--dry-run', '--json', '--ignore-scripts'], {
    cwd: extensionDir,
    encoding: 'utf8',
    shell: false,
  })

  let files: string[] = []
  let parseError: string | null = null
  try {
    files = parsePackFiles(result.stdout ?? '')
  } catch (error) {
    parseError = error instanceof Error ? error.message : String(error)
  }

  return {
    exitCode: result.status,
    files,
    parseError,
  }
}

function writeReports(report: SmokeReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(resolve(docsDir, 'ide-extension-manifest-smoke-report.json'), `${JSON.stringify(report, null, 2)}\n`)

  const lines = [
    '# IDE Extension Manifest Smoke Report',
    '',
    'Generated by: `bun run product:ide-extension-manifest-smoke`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies the local VS Code manifest surface and local package dry-run only.',
    '- It does not install, publish, deploy, launch, or claim extension availability.',
    '- It does not call providers, live models, or external services.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- manifest_path: \`${report.manifestPath}\``,
    `- entry_point_path: \`${report.entryPointPath}\``,
    `- package_dry_run_exit_code: \`${report.packageDryRunExitCode}\``,
    `- install_attempted: \`${report.installAttempted}\``,
    `- publish_attempted: \`${report.publishAttempted}\``,
    `- deploy_attempted: \`${report.deployAttempted}\``,
    `- launch_attempted: \`${report.launchAttempted}\``,
    `- extension_availability_claim_allowed: \`${report.extensionAvailabilityClaimAllowed}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Manifest Summary',
    '',
    `- name: \`${report.manifestSummary.name}\``,
    `- display_name: \`${report.manifestSummary.displayName}\``,
    `- publisher: \`${report.manifestSummary.publisher}\``,
    `- engines_vscode: \`${report.manifestSummary.enginesVscode}\``,
    `- extension_kind: ${report.manifestSummary.extensionKind.map((item) => `\`${item}\``).join(', ')}`,
    `- main: \`${report.manifestSummary.main}\``,
    `- activation_events: ${report.manifestSummary.activationEvents.map((item) => `\`${item}\``).join(', ')}`,
    `- command_ids: ${report.manifestSummary.commandIds.map((item) => `\`${item}\``).join(', ')}`,
    `- view_ids: ${report.manifestSummary.viewIds.map((item) => `\`${item}\``).join(', ')}`,
    `- tree_view_ids: ${report.manifestSummary.treeViewIds.map((item) => `\`${item}\``).join(', ')}`,
    `- webview_view_ids: ${report.manifestSummary.webviewViewIds.map((item) => `\`${item}\``).join(', ')}`,
    `- configuration_keys: ${report.manifestSummary.configurationKeys.map((item) => `\`${item}\``).join(', ')}`,
    '',
    '## Package Dry-Run Files',
    '',
    ...report.packageDryRunFiles.map((item) => `- \`${item}\``),
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.manifestSmokeChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'ide-extension-manifest-smoke-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const scope = readJson<ScopeReport>('docs/product-quality/ide-extension-scope-report.json')
  const manifest = readJson<Manifest>(manifestPath)
  const commandIds = manifest.contributes?.commands?.map((item) => item.command).filter((command): command is string => typeof command === 'string') ?? []
  const viewIds = flattenViewIds(manifest.contributes?.views)
  const treeViewIds = flattenTreeViewIds(manifest.contributes?.views)
  const webviewViewIds = flattenWebviewViewIds(manifest.contributes?.views)
  const configurationKeys = Object.keys(manifest.contributes?.configuration?.properties ?? {})
  const activationEvents = manifest.activationEvents ?? []
  const extensionKind = manifest.extensionKind ?? []
  const packageDryRun = runPackageDryRun()

  const manifestSummary = {
    name: manifest.name ?? '',
    displayName: manifest.displayName ?? '',
    publisher: manifest.publisher ?? '',
    enginesVscode: manifest.engines?.vscode ?? '',
    extensionKind,
    main: manifest.main ?? '',
    activationEvents,
    commandIds,
    viewIds,
    treeViewIds,
    webviewViewIds,
    configurationKeys,
  }

  const smokeChecks = [
    check('manifest exists at scoped path', existsSync(resolve(root, manifestPath)) && scope.proposedManifestPath === manifestPath, scope.proposedManifestPath),
    check('entry point exists at scoped path', existsSync(resolve(root, entryPointPath)), entryPointPath),
    check('manifest identity fields are present', manifestSummary.name === 'openclaude-vscode' && manifestSummary.displayName === 'OpenClaude' && manifestSummary.publisher === 'gitlawb', `${manifestSummary.name}/${manifestSummary.displayName}/${manifestSummary.publisher}`),
    check('manifest declares VS Code engine and entry point', manifestSummary.enginesVscode.length > 0 && manifestSummary.main === './dist/extension.js', `${manifestSummary.enginesVscode}/${manifestSummary.main}`),
    check('manifest declares UI and workspace extension kinds', extensionKind.includes('ui') && extensionKind.includes('workspace'), extensionKind.join(', ')),
    check('manifest includes scoped commands', scope.contributionPlan.commands.every((command) => commandIds.includes(command)), commandIds.join(', ')),
    check('manifest includes scoped views', scope.contributionPlan.views.every((view) => viewIds.includes(view)), viewIds.join(', ')),
    check('manifest includes scoped configuration keys', scope.contributionPlan.configurationKeys.every((key) => configurationKeys.includes(key)), configurationKeys.join(', ')),
    check('manifest includes scoped activation events', scope.contributionPlan.activationEvents.every((event) => activationEvents.includes(event)), activationEvents.join(', ')),
    check('manifest includes bounded webview render surface', webviewViewIds.includes('openclaude.controlCenterView') && activationEvents.includes('onView:openclaude.controlCenterView'), `${webviewViewIds.join(', ')} / ${activationEvents.join(', ')}`),
    check('package dry-run exits successfully', packageDryRun.exitCode === 0, String(packageDryRun.exitCode)),
    check('package dry-run output is parseable', packageDryRun.parseError === null, packageDryRun.parseError ?? 'ok'),
    check('package dry-run file list is bounded', packageDryRun.files.length >= 3 && packageDryRun.files.every((path) => !/node_modules|\.env|credential|secret|token/i.test(path)), packageDryRun.files.join(', ')),
    check('protected actions were not attempted', true, 'install/publish/deploy/launch/provider/live/external all false'),
  ]

  const report: SmokeReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_ide_extension_manifest_smoke',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    manifestPath,
    entryPointPath,
    packageDryRunExitCode: packageDryRun.exitCode,
    installAttempted: false,
    publishAttempted: false,
    deployAttempted: false,
    launchAttempted: false,
    extensionAvailabilityClaimAllowed: false,
    manifestSummary,
    packageDryRunFiles: packageDryRun.files,
    manifestSmokeChecks: smokeChecks,
    claimBoundary: 'Local VS Code manifest smoke evidence is internal and no-provider. It does not install, publish, deploy, launch, or claim extension availability.',
  }

  writeReports(report)

  for (const item of smokeChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!smokeChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`manifest_path=${report.manifestPath}`)
  console.log(`entry_point_path=${report.entryPointPath}`)
  console.log(`package_dry_run_exit_code=${report.packageDryRunExitCode}`)
  console.log(`package_dry_run_files=${report.packageDryRunFiles.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
  console.log(`extension_availability_claim_allowed=${report.extensionAvailabilityClaimAllowed}`)
}

main()
