import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type Check = {
  label: string
  ok: boolean
  detail: string
}

type SourceInput = {
  sourceProject: string
  sourceUrl: string
  observedPattern: string
  localAbsorption: string
}

type CommunityFileSummary = {
  path: string
  sha256: string
  requiredTermsPresent: string[]
}

type CommunityProfileQualityReport = {
  generatedAt: string
  mode: 'local_no_provider_community_profile_quality'
  primarySourceInputs: SourceInput[]
  sourceProfilePaths: string[]
  sourceProfileSha256: Record<string, string>
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  externalCommunityProfileCheckPerformed: false
  readmeLinksCommunityFiles: boolean
  contributing: CommunityFileSummary
  support: CommunityFileSummary
  codeOfConduct: CommunityFileSummary
  security: CommunityFileSummary
  license: CommunityFileSummary
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  claimBoundary: string
  communityProfileChecks: Check[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const profilePaths = {
  readme: 'README.md',
  contributing: 'CONTRIBUTING.md',
  support: 'SUPPORT.md',
  codeOfConduct: 'CODE_OF_CONDUCT.md',
  security: 'SECURITY.md',
  license: 'LICENSE',
}

function sha256(input: string | Buffer): string {
  return createHash('sha256').update(input).digest('hex')
}

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function fileSha256(path: string): string {
  return sha256(readFileSync(resolve(root, path)))
}

function check(label: string, ok: boolean, detail: string): Check {
  return { label, ok, detail }
}

function includesAll(text: string, terms: string[]): string[] {
  const lower = text.toLowerCase()
  return terms.filter((term) => lower.includes(term.toLowerCase()))
}

function summarize(path: string, requiredTerms: string[]): CommunityFileSummary {
  const text = readText(path)
  return {
    path,
    sha256: fileSha256(path),
    requiredTermsPresent: includesAll(text, requiredTerms),
  }
}

function writeMarkdown(report: CommunityProfileQualityReport): void {
  const sourceRows = report.primarySourceInputs
    .map((source) => `| ${source.sourceProject} | ${source.sourceUrl} | ${source.localAbsorption} |`)
    .join('\n')
  const fileRows = [
    report.contributing,
    report.support,
    report.codeOfConduct,
    report.security,
    report.license,
  ]
    .map((file) => `| \`${file.path}\` | \`${file.sha256}\` | ${file.requiredTermsPresent.join(', ')} |`)
    .join('\n')
  const checkRows = report.communityProfileChecks
    .map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`)
    .join('\n')

  const markdown = `# Community Profile Quality Report

Generated by: \`bun run product:community-profile-quality\`

## Claim Boundary

- This report verifies local community profile files only.
- It uses official GitHub documentation patterns for contributor guidelines, support resources, code of conduct, license, and healthy contribution surfaces.
- It does not call providers, live models, external services, GitHub APIs, or hosted community-profile checks.
- It does not install dependencies, publish, deploy, launch, modify production systems, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.

## Summary

- mode: \`${report.mode}\`
- source_profile_count: \`${report.sourceProfilePaths.length}\`
- readme_links_community_files: \`${report.readmeLinksCommunityFiles}\`
- external_community_profile_check_performed: \`${report.externalCommunityProfileCheckPerformed}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`
- release_readiness_claim_allowed: \`${report.releaseReadinessClaimAllowed}\`
- production_readiness_claim_allowed: \`${report.productionReadinessClaimAllowed}\`
- public_readiness_claim_allowed: \`${report.publicReadinessClaimAllowed}\`
- external_validation_claim_allowed: \`${report.externalValidationClaimAllowed}\`
- autonomous_reliability_claim_allowed: \`${report.autonomousReliabilityClaimAllowed}\`

## Primary Sources

| Source | URL | Local Absorption |
| --- | --- | --- |
${sourceRows}

## Community Profile Files

| File | SHA-256 | Required Terms Present |
| --- | --- | --- |
${fileRows}

## Checks

| Check | Result | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'community-profile-quality-report.md'), markdown)
}

function main(): void {
  mkdirSync(docsDir, { recursive: true })

  const sourceProfilePaths = Object.values(profilePaths)
  const sourceProfileSha256: Record<string, string> = {}
  for (const path of sourceProfilePaths) {
    if (existsSync(resolve(root, path))) {
      sourceProfileSha256[path] = fileSha256(path)
    }
  }

  const readme = readText(profilePaths.readme)
  const report: CommunityProfileQualityReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_community_profile_quality',
    primarySourceInputs: [
      {
        sourceProject: 'GitHub Docs healthy contributions',
        sourceUrl: 'https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions',
        observedPattern: 'Healthy open-source contribution surfaces include community profile files such as code of conduct, contributor guidelines, license, and support resources.',
        localAbsorption: 'OpenClaude now verifies community profile files as local no-provider product-quality evidence.',
      },
      {
        sourceProject: 'GitHub Docs contributor guidelines',
        sourceUrl: 'https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors',
        observedPattern: 'Contributor guidelines help contributors open useful issues and well-formed pull requests.',
        localAbsorption: 'CONTRIBUTING.md now includes support routing, code of conduct links, privacy, validation, product-quality, primary-source, and protected-claim expectations.',
      },
      {
        sourceProject: 'GitHub Docs support resources',
        sourceUrl: 'https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project',
        observedPattern: 'A SUPPORT file gives people a clear path for getting help and can be linked from the README.',
        localAbsorption: 'SUPPORT.md now routes discussions, issues, security reports, contribution guidance, and privacy/safety boundaries.',
      },
      {
        sourceProject: 'GitHub Docs code of conduct',
        sourceUrl: 'https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project',
        observedPattern: 'A code of conduct communicates community standards and enforcement expectations.',
        localAbsorption: 'OpenClaude verifies the existing Contributor Covenant code of conduct is present and linked into contributor/support flows.',
      },
      {
        sourceProject: 'GitHub Docs licensing',
        sourceUrl: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository',
        observedPattern: 'Public repositories should make license status clear so reuse and contribution boundaries are not implicit.',
        localAbsorption: 'OpenClaude verifies LICENSE exists and preserves the derivative-code notice boundary in local community-profile evidence.',
      },
    ],
    sourceProfilePaths,
    sourceProfileSha256,
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    externalCommunityProfileCheckPerformed: false,
    readmeLinksCommunityFiles: ['CONTRIBUTING.md', 'SUPPORT.md', 'CODE_OF_CONDUCT.md', 'SECURITY.md', 'LICENSE'].every((link) => readme.includes(link)),
    contributing: summarize(profilePaths.contributing, [
      'SUPPORT.md',
      'CODE_OF_CONDUCT.md',
      'bun run verify:privacy',
      'bun run product:quality',
      'primary sources',
      'claim boundaries',
      'provider-backed execution',
      'protected repo mutation',
    ]),
    support: summarize(profilePaths.support, [
      'GitHub Discussions',
      'GitHub Issues',
      'SECURITY.md',
      'CONTRIBUTING.md',
      'CODE_OF_CONDUCT.md',
      'redacted',
      'raw user/session payloads',
      'release readiness',
      'provider-backed execution claims',
    ]),
    codeOfConduct: summarize(profilePaths.codeOfConduct, [
      'Contributor Covenant',
      'Our Pledge',
      'Our Standards',
      'Enforcement',
      'Scope',
      'privacy and security',
    ]),
    security: summarize(profilePaths.security, [
      'Supported Versions',
      'Reporting a Vulnerability',
      'GitHub Security Advisories',
      'Response Process',
      'Disclosure and CVEs',
      'Scope',
    ]),
    license: summarize(profilePaths.license, [
      'NOTICE',
      'MIT License',
      'Anthropic',
      'modifications only',
      'underlying derived code remains subject',
    ]),
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    claimBoundary: 'Community profile quality evidence only; this does not authorize release, production, public, external-validation, provider-backed, live-model, or autonomous-reliability claims.',
    communityProfileChecks: [],
  }

  report.communityProfileChecks = [
    check('all community profile files exist', sourceProfilePaths.every((path) => existsSync(resolve(root, path))), sourceProfilePaths.join(',')),
    check('README links community profile files', report.readmeLinksCommunityFiles, 'CONTRIBUTING.md,SUPPORT.md,CODE_OF_CONDUCT.md,SECURITY.md,LICENSE'),
    check('contributing guidelines cover validation evidence and claim boundaries', report.contributing.requiredTermsPresent.length === 8, `${report.contributing.requiredTermsPresent.length}/8 terms`),
    check('support resources route help security contribution and privacy boundaries', report.support.requiredTermsPresent.length === 9, `${report.support.requiredTermsPresent.length}/9 terms`),
    check('code of conduct includes standards scope enforcement and privacy', report.codeOfConduct.requiredTermsPresent.length === 6, `${report.codeOfConduct.requiredTermsPresent.length}/6 terms`),
    check('security policy covers version reporting response disclosure and scope', report.security.requiredTermsPresent.length === 6, `${report.security.requiredTermsPresent.length}/6 terms`),
    check('license notice preserves modification and derivative-code boundary', report.license.requiredTermsPresent.length === 5, `${report.license.requiredTermsPresent.length}/5 terms`),
    check('primary-source inputs are official GitHub documentation', report.primarySourceInputs.every((source) => source.sourceUrl.startsWith('https://docs.github.com/')), report.primarySourceInputs.map((source) => source.sourceUrl).join(',')),
    check('external community profile check remains blocked', report.externalCommunityProfileCheckPerformed === false, 'local file validation only'),
    check('provider live external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all call arrays empty'),
    check('protected actions remain absent', report.protectedActionsExecuted.length === 0, 'zero'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all false'),
  ]

  writeFileSync(resolve(docsDir, 'community-profile-quality-report.json'), `${JSON.stringify(report, null, 2)}\n`)
  writeMarkdown(report)

  for (const item of report.communityProfileChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  const failed = report.communityProfileChecks.filter((item) => !item.ok)
  if (failed.length > 0) {
    console.error(`RESULT: FAIL (${failed.length} failed checks)`)
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`source_profile_count=${report.sourceProfilePaths.length}`)
  console.log(`readme_links_community_files=${report.readmeLinksCommunityFiles}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
