import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type RegressionFixture = {
  id: string
  title: string
  ok: boolean
  sources: string[]
  invariant: string
  evidence: string[]
}

type PermissionRegressionReport = {
  generatedAt: string
  mode: 'local_no_provider_permission_regression'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedPermissionSurfaces: string[]
  targetedTestFiles: string[]
  behavioralTestCommands: BehavioralTestCommand[]
  regressionFixtures: RegressionFixture[]
  claimBoundary: string
}

type BehavioralTestCommand = {
  name: string
  command: string[]
  exitCode: number | null
  passed: boolean
  requiredSubstrings: string[]
  missingSubstrings: string[]
  stdoutPreview: string[]
  stderrPreview: string[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function sourceExists(path: string): boolean {
  return existsSync(resolve(root, path))
}

function normalize(text: string | Buffer | null | undefined): string {
  return String(text ?? '').replace(/\r\n/g, '\n')
}

function preview(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .slice(0, 80)
}

function noProviderEnv(): NodeJS.ProcessEnv {
  return {
    ...process.env,
    CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST: '1',
    CLAUDE_CODE_USE_OPENAI: '0',
    CLAUDE_CODE_USE_GEMINI: '0',
    CLAUDE_CODE_USE_GITHUB: '0',
    CLAUDE_CODE_USE_MISTRAL: '0',
    OPENAI_API_KEY: '',
    CODEX_API_KEY: '',
    GEMINI_API_KEY: '',
    GOOGLE_API_KEY: '',
    MISTRAL_API_KEY: '',
    GITHUB_TOKEN: '',
    GH_TOKEN: '',
    ANTHROPIC_API_KEY: '',
    OPENCLAUDE_PRODUCT_PERMISSION_REGRESSION_NO_PROVIDER: '1',
  }
}

function runBehavioralTestCommand(
  name: string,
  files: string[],
  requiredSubstrings: string[],
): BehavioralTestCommand {
  const command = ['bun', 'test', ...files]
  const result = spawnSync(process.execPath, ['test', ...files], {
    cwd: root,
    encoding: 'utf8',
    env: noProviderEnv(),
    shell: false,
  })
  const stdout = normalize(result.stdout)
  const stderr = normalize(result.stderr)
  const combined = `${stdout}\n${stderr}`
  const missingSubstrings = requiredSubstrings.filter((substring) => !combined.includes(substring))

  return {
    name,
    command,
    exitCode: result.status,
    passed: result.status === 0 && missingSubstrings.length === 0,
    requiredSubstrings,
    missingSubstrings,
    stdoutPreview: preview(stdout),
    stderrPreview: preview(stderr),
  }
}

function containsAll(path: string, snippets: string[]): boolean {
  if (!sourceExists(path)) {
    return false
  }
  const content = readText(path)
  return snippets.every((snippet) => content.includes(snippet))
}

function containsNone(path: string, snippets: string[]): boolean {
  if (!sourceExists(path)) {
    return false
  }
  const content = readText(path)
  return snippets.every((snippet) => !content.includes(snippet))
}

function fixture(
  id: string,
  title: string,
  sources: string[],
  invariant: string,
  ok: boolean,
  evidence: string[],
): RegressionFixture {
  return { id, title, ok, sources, invariant, evidence }
}

function writeReports(report: PermissionRegressionReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'permission-regression-fixtures.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const lines = [
    '# Permission Regression Fixtures',
    '',
    'Generated by: `bun run product:permission-regression`',
    '',
    '## Claim Boundary',
    '',
    '- These fixtures verify local permission and security-regression source surfaces only.',
    '- They do not execute shell commands through OpenClaude tools.',
    '- They do not call providers, live models, or external services.',
    '- They do not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- regression_fixture_count: \`${report.regressionFixtures.length}\``,
    `- all_regression_fixtures_passed: \`${report.regressionFixtures.every((item) => item.ok)}\``,
    `- protected_permission_surfaces: \`${report.protectedPermissionSurfaces.length}\``,
    `- targeted_test_files: \`${report.targetedTestFiles.length}\``,
    `- behavioral_test_commands: \`${report.behavioralTestCommands.length}\``,
    `- behavioral_test_commands_passed: \`${report.behavioralTestCommands.every((item) => item.passed)}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Protected Permission Surfaces',
    '',
    ...report.protectedPermissionSurfaces.map((surface) => `- ${surface}`),
    '',
    '## Targeted Test Files',
    '',
    ...report.targetedTestFiles.map((path) => `- \`${path}\``),
    '',
    '## Behavioral Test Commands',
    '',
    '| Command | Result | Exit | Missing Substrings |',
    '| --- | --- | ---: | --- |',
    ...report.behavioralTestCommands.map((item) => (
      `| \`${item.command.join(' ')}\` | \`${item.passed}\` | \`${item.exitCode ?? 'null'}\` | ${item.missingSubstrings.length === 0 ? 'none' : item.missingSubstrings.map((value) => `\`${value}\``).join('<br>')} |`
    )),
    '',
    '## Fixtures',
    '',
    '| Fixture | Result | Invariant | Sources |',
    '| --- | --- | --- | --- |',
    ...report.regressionFixtures.map((item) => (
      `| \`${item.id}\` | \`${item.ok}\` | ${item.invariant} | ${item.sources.map((source) => `\`${source}\``).join('<br>')} |`
    )),
    '',
  ]

  writeFileSync(resolve(docsDir, 'permission-regression-fixtures.md'), `${lines.join('\n')}\n`)
}

function buildFixtures(): RegressionFixture[] {
  return [
    fixture(
      'private_vulnerability_reporting',
      'Private vulnerability reporting is documented',
      ['SECURITY.md'],
      'Security reports should be routed privately instead of public issue disclosure.',
      containsAll('SECURITY.md', [
        'GitHub Security Advisories',
        'Please do **not** open a public issue',
      ]),
      ['private reporting channel', 'public issue warning'],
    ),
    fixture(
      'bypass_mode_requires_explicit_enable',
      'Bypass mode requires explicit enablement',
      ['src/cli/print.ts'],
      'Runtime permission mode changes to bypassPermissions must remain gated by explicit flag or settings.',
      containsAll('src/cli/print.ts', [
        'Cannot set permission mode to bypassPermissions',
        '--allow-dangerously-skip-permissions',
        'permissions.allowBypassPermissionsMode',
      ]),
      ['runtime rejection message', 'explicit flag text', 'settings path text'],
    ),
    fixture(
      'bypass_setting_schema_is_boolean',
      'Bypass setting schema rejects non-boolean values',
      ['src/utils/settings/allowBypassPermissionsMode.test.ts'],
      'The allowBypassPermissionsMode setting must accept booleans and reject string-like truthy values.',
      containsAll('src/utils/settings/allowBypassPermissionsMode.test.ts', [
        'accepts allowBypassPermissionsMode: true',
        'accepts allowBypassPermissionsMode: false',
        'rejects non-boolean allowBypassPermissionsMode',
      ]),
      ['true accepted', 'false accepted', 'non-boolean rejected'],
    ),
    fixture(
      'model_cannot_disable_sandbox',
      'Model-facing shell schemas reject sandbox disable requests',
      ['src/tools/BashTool/shouldUseSandbox.test.ts'],
      'Model-controlled shell input must not disable sandboxing; only trusted internal approval can do so when policy allows.',
      containsAll('src/tools/BashTool/shouldUseSandbox.test.ts', [
        'model-facing Bash schema rejects dangerouslyDisableSandbox',
        'model-facing PowerShell schema rejects dangerouslyDisableSandbox',
        'model-controlled dangerouslyDisableSandbox does not bypass sandbox',
        'trusted internal approval cannot disable sandbox when policy forbids it',
      ]),
      ['Bash schema rejection', 'PowerShell schema rejection', 'model-controlled bypass rejection', 'policy-forbidden trusted rejection'],
    ),
    fixture(
      'sandbox_auto_allow_preserves_path_constraints',
      'Sandbox auto-allow preserves Bash path constraints',
      ['src/tools/BashTool/bashPermissions.test.ts'],
      'Sandbox auto-allow must still ask when path constraints block sensitive filesystem access.',
      containsAll('src/tools/BashTool/bashPermissions.test.ts', [
        'sandbox auto-allow still enforces Bash path constraints',
        'cat ../../../../../etc/passwd',
        "expect(result.behavior).toBe('ask')",
        'const message = (result as { message: string }).message',
        "expect(message).toContain('was blocked')",
        "expect(message).toContain('passwd')",
      ]),
      ['path traversal command fixture', 'ask decision assertion', 'blocked message assertion'],
    ),
    fixture(
      'sandbox_settings_trust_boundary',
      'Sandbox settings source filtering is covered',
      ['src/__tests__/security-hardening.test.ts'],
      'Sandbox enablement must not trust project settings when the trusted-source test fixture is present.',
      containsAll('src/__tests__/security-hardening.test.ts', [
        'Sandbox settings trust boundary',
        'getSandboxEnabledSetting does not use getSettings_DEPRECATED',
        "expect(fnBody).not.toContain(\"'projectSettings'\")",
      ]),
      ['trust-boundary regression', 'deprecated settings rejection', 'project settings rejection'],
    ),
    fixture(
      'plugin_git_hooks_disabled',
      'Plugin git operations disable hooks',
      [
        'src/__tests__/security-hardening.test.ts',
        'src/utils/plugins/marketplaceManager.ts',
      ],
      'Plugin clone, pull, and submodule operations must keep hooks disabled.',
      containsAll('src/__tests__/security-hardening.test.ts', [
        'Plugin git operations disable hooks',
        'gitClone includes core.hooksPath=/dev/null',
        'gitPull includes core.hooksPath=/dev/null',
        'gitSubmoduleUpdate includes core.hooksPath=/dev/null',
      ]) &&
        containsAll('src/utils/plugins/marketplaceManager.ts', [
          'core.hooksPath=/dev/null',
        ]),
      ['clone hook disable regression', 'pull hook disable regression', 'submodule hook disable regression'],
    ),
    fixture(
      'webfetch_ssrf_guard',
      'WebFetch redirect path keeps SSRF guard',
      [
        'src/__tests__/security-hardening.test.ts',
        'src/tools/WebFetchTool/utils.ts',
      ],
      'WebFetch permitted redirects must continue using the guarded lookup helper.',
      containsAll('src/__tests__/security-hardening.test.ts', [
        'WebFetch SSRF guard',
        'getWithPermittedRedirects uses ssrfGuardedLookup',
      ]) &&
        containsAll('src/tools/WebFetchTool/utils.ts', [
          'ssrfGuardedLookup',
          'lookup: ssrfGuardedLookup',
        ]),
      ['redirect test fixture', 'guarded lookup import/use'],
    ),
    fixture(
      'swarm_file_permission_polling_removed',
      'Swarm file-based permission polling remains removed',
      [
        'src/__tests__/security-hardening.test.ts',
        'src/hooks/useSwarmPermissionPoller.ts',
        'src/utils/swarm/permissionSync.ts',
      ],
      'Unauthenticated file-based swarm permission polling must stay removed or explicitly deprecated.',
      containsAll('src/__tests__/security-hardening.test.ts', [
        'Swarm permission file polling removed',
        'file-based permission functions are marked deprecated',
      ]) &&
        containsNone('src/hooks/useSwarmPermissionPoller.ts', [
          'function useSwarmPermissionPoller(',
          'function processResponse(',
        ]) &&
        containsAll('src/utils/swarm/permissionSync.ts', [
          '@deprecated',
          'sendPermissionRequestViaMailbox',
          'sendPermissionResponseViaMailbox',
        ]),
      ['poller removal test', 'deprecated file-path functions', 'mailbox active path'],
    ),
    fixture(
      'permission_rule_validation',
      'Permission rule validation covers common unsafe rule mistakes',
      ['src/utils/settings/permissionValidation.ts'],
      'Permission rule validation must reject empty rules, mismatched parentheses, MCP pattern misuse, and shell/file-pattern mistakes.',
      containsAll('src/utils/settings/permissionValidation.ts', [
        'Permission rule cannot be empty',
        'Mismatched parentheses',
        'MCP rules do not support patterns in parentheses',
        'The :* pattern must be at the end',
        'The ":*" syntax is only for Bash prefix rules',
      ]),
      ['empty rule rejection', 'paren validation', 'MCP pattern rejection', 'Bash pattern rejection', 'file pattern rejection'],
    ),
    fixture(
      'auto_classifier_transcript_bounded',
      'Auto classifier transcript construction remains bounded',
      ['src/utils/permissions/yoloClassifier.test.ts'],
      'Auto-permission classifier transcript construction must retain recent context and truncate oversized user blocks.',
      containsAll('src/utils/permissions/yoloClassifier.test.ts', [
        'keeps the most recent transcript entries within budget',
        'truncates oversized user blocks before serialization',
        "expect(transcript).toContain('new-user')",
        'expect(transcript.length).toBeLessThan(33_000)',
      ]),
      ['recent context retained', 'old context dropped', 'oversized user block bounded'],
    ),
  ]
}

function main(): void {
  const targetedTestFiles = [
    'src/__tests__/security-hardening.test.ts',
    'src/tools/BashTool/bashPermissions.test.ts',
    'src/tools/BashTool/shouldUseSandbox.test.ts',
    'src/utils/settings/allowBypassPermissionsMode.test.ts',
    'src/utils/permissions/yoloClassifier.test.ts',
  ]
  const protectedPermissionSurfaces = [
    'bypass permission mode activation',
    'sandbox enablement trusted-source boundary',
    'model-facing shell sandbox disable input',
    'Bash path constraints under sandbox auto-allow',
    'plugin git hook execution',
    'WebFetch redirect SSRF guard',
    'swarm permission response path',
    'permission rule parsing and validation',
    'auto-mode classifier transcript bounds',
  ]
  const regressionFixtures = buildFixtures()
  const behavioralTestCommands = [
    runBehavioralTestCommand(
      'targeted_permission_security_tests',
      targetedTestFiles,
      ['pass', '0 fail'],
    ),
  ]
  const report: PermissionRegressionReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_permission_regression',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedPermissionSurfaces,
    targetedTestFiles,
    behavioralTestCommands,
    regressionFixtures,
    claimBoundary: 'Permission regression fixtures and behavioral command evidence are local no-provider permission/security checks only, not external security validation or release readiness.',
  }

  writeReports(report)

  for (const item of regressionFixtures) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.id}`)
  }

  console.log('')
  if (!regressionFixtures.every((item) => item.ok) || !behavioralTestCommands.every((item) => item.passed)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`regression_fixture_count=${regressionFixtures.length}`)
  console.log(`behavioral_test_commands=${behavioralTestCommands.length}`)
  console.log(`protected_permission_surfaces=${protectedPermissionSurfaces.length}`)
  console.log(`targeted_test_files=${targetedTestFiles.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
