import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { check, fileSha256, readText, type Check } from './quality-report-helpers'

type TypecheckHealthReport = {
  strictPass: boolean
  totalDiagnostics: number
  diagnosticBudget: number
}

type VerificationReportConsistencyReport = {
  generatedAt: string
  mode: 'local_no_provider_verification_report_consistency'
  sourceVerificationReportPath: string
  sourceVerificationReportSha256: string
  sourceTypecheckHealthReportPath: string
  sourceTypecheckHealthReportSha256: string
  sourceTerminalReportPath: string
  sourceTerminalReportSha256: string
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  sourceTypecheckStrictPass: boolean
  sourceTypecheckTotalDiagnostics: number
  sourceTypecheckDiagnosticBudget: number
  sourceTerminalCondition: string
  obsoleteBlockerPhrasesFound: string[]
  currentBlockerPhrasesFound: string[]
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  reportConsistencyChecks: Check[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const sourceVerificationReportPath = 'docs/product-quality/verification-report-2026-05-17.md'
const sourceTypecheckHealthReportPath = 'docs/product-quality/typecheck-health-report.json'
const sourceTerminalReportPath = 'docs/product-quality/terminal-report.md'

const obsoleteBlockerPhrases = [
  'Repo-wide `bun run typecheck` currently fails',
  'implicit-any-strictness 938',
  'narrowing-or-unknown-state 210',
  'pre-existing broad TypeScript diagnostics',
]

const requiredProtectedBoundaryPhrases = [
  'blocked_by_no_git_repo',
  'external benchmark',
]

function readJson<T>(path: string): T {
  return JSON.parse(readText(path)) as T
}

function extractSection(markdown: string, heading: string): string {
  const start = markdown.indexOf(`## ${heading}`)
  if (start === -1) {
    return ''
  }

  const next = markdown.indexOf('\n## ', start + 1)
  return next === -1 ? markdown.slice(start) : markdown.slice(start, next)
}

function terminalConditionFrom(markdown: string): string {
  const match = markdown.match(/terminal_condition:\s*`([^`]+)`/)
  return match?.[1] ?? 'missing'
}

function writeMarkdown(report: VerificationReportConsistencyReport): void {
  const checkRows = report.reportConsistencyChecks
    .map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`)
    .join('\n')
  const obsoleteRows = report.obsoleteBlockerPhrasesFound.length === 0
    ? '- none'
    : report.obsoleteBlockerPhrasesFound.map((item) => `- \`${item}\``).join('\n')
  const currentRows = report.currentBlockerPhrasesFound.map((item) => `- \`${item}\``).join('\n')

  const markdown = `# Verification Report Consistency Report

Generated by: \`bun run product:verification-report-consistency\`

## Claim Boundary

- This is a local no-provider consistency check for product-quality documentation.
- It does not call providers, call live models, call external services, install dependencies, publish, deploy, launch, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.

## Summary

- mode: \`${report.mode}\`
- source_verification_report: \`${report.sourceVerificationReportPath}\`
- source_typecheck_health_report: \`${report.sourceTypecheckHealthReportPath}\`
- source_terminal_report: \`${report.sourceTerminalReportPath}\`
- source_typecheck_strict_pass: \`${report.sourceTypecheckStrictPass}\`
- source_typecheck_total_diagnostics: \`${report.sourceTypecheckTotalDiagnostics}\`
- source_typecheck_diagnostic_budget: \`${report.sourceTypecheckDiagnosticBudget}\`
- source_terminal_condition: \`${report.sourceTerminalCondition}\`
- obsolete_blocker_phrase_count: \`${report.obsoleteBlockerPhrasesFound.length}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`
- release_readiness_claim_allowed: \`${report.releaseReadinessClaimAllowed}\`
- production_readiness_claim_allowed: \`${report.productionReadinessClaimAllowed}\`
- public_readiness_claim_allowed: \`${report.publicReadinessClaimAllowed}\`
- external_validation_claim_allowed: \`${report.externalValidationClaimAllowed}\`
- autonomous_reliability_claim_allowed: \`${report.autonomousReliabilityClaimAllowed}\`

## Obsolete Blocker Phrases

${obsoleteRows}

## Current Blocker Phrases Found

${currentRows}

## Checks

| Check | Result | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'verification-report-consistency-report.md'), markdown)
}

function main(): void {
  mkdirSync(docsDir, { recursive: true })

  const verificationReport = readText(sourceVerificationReportPath)
  const typecheckHealth = readJson<TypecheckHealthReport>(sourceTypecheckHealthReportPath)
  const terminalReport = readText(sourceTerminalReportPath)
  const blockerSection = extractSection(verificationReport, 'Productization Blockers')
  const obsoleteBlockerPhrasesFound = obsoleteBlockerPhrases.filter((phrase) => blockerSection.includes(phrase))
  const sourceTerminalCondition = terminalConditionFrom(terminalReport)
  const requiredCurrentBlockerPhrases = sourceTerminalCondition === 'PRODUCT_QUALITY_GATE_READY'
    ? requiredProtectedBoundaryPhrases
    : sourceTerminalCondition === 'PRODUCT_QUALITY_GATE_BLOCKED_BY_LOCAL_VSCODE_CLI_UNAVAILABLE'
    ? ['vscode_cli_unavailable', ...requiredProtectedBoundaryPhrases]
    : ['vscode_update_in_progress', ...requiredProtectedBoundaryPhrases]
  const currentBlockerPhrasesFound = requiredCurrentBlockerPhrases.filter((phrase) => verificationReport.toLowerCase().includes(phrase.toLowerCase()))

  const report: VerificationReportConsistencyReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_verification_report_consistency',
    sourceVerificationReportPath,
    sourceVerificationReportSha256: fileSha256(sourceVerificationReportPath),
    sourceTypecheckHealthReportPath,
    sourceTypecheckHealthReportSha256: fileSha256(sourceTypecheckHealthReportPath),
    sourceTerminalReportPath,
    sourceTerminalReportSha256: fileSha256(sourceTerminalReportPath),
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    sourceTypecheckStrictPass: typecheckHealth.strictPass,
    sourceTypecheckTotalDiagnostics: typecheckHealth.totalDiagnostics,
    sourceTypecheckDiagnosticBudget: typecheckHealth.diagnosticBudget,
    sourceTerminalCondition,
    obsoleteBlockerPhrasesFound,
    currentBlockerPhrasesFound,
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    reportConsistencyChecks: [],
    claimBoundary: 'Local documentation consistency evidence only; no release, public, production, external-validation, or autonomous-reliability claim is authorized.',
  }

  report.reportConsistencyChecks = [
    check('verification report imported', report.sourceVerificationReportSha256.length === 64, report.sourceVerificationReportPath),
    check('typecheck health imported', report.sourceTypecheckHealthReportSha256.length === 64, report.sourceTypecheckHealthReportPath),
    check('terminal report imported', report.sourceTerminalReportSha256.length === 64, report.sourceTerminalReportPath),
    check('typecheck health remains zero-diagnostic', report.sourceTypecheckStrictPass && report.sourceTypecheckTotalDiagnostics === 0 && report.sourceTypecheckDiagnosticBudget === 0, `${report.sourceTypecheckTotalDiagnostics}/${report.sourceTypecheckDiagnosticBudget}`),
    check('terminal condition is current product-quality state', ['PRODUCT_QUALITY_GATE_READY', 'PRODUCT_QUALITY_GATE_BLOCKED_BY_LOCAL_VSCODE_UPDATE', 'PRODUCT_QUALITY_GATE_BLOCKED_BY_LOCAL_VSCODE_CLI_UNAVAILABLE'].includes(report.sourceTerminalCondition), report.sourceTerminalCondition),
    check('obsolete typecheck blocker phrases are absent from blocker section', report.obsoleteBlockerPhrasesFound.length === 0, report.obsoleteBlockerPhrasesFound.join(',') || 'none'),
    check('current blocker phrases are present', report.currentBlockerPhrasesFound.length === requiredCurrentBlockerPhrases.length, `${report.currentBlockerPhrasesFound.length}/${requiredCurrentBlockerPhrases.length}`),
    check('provider/live/external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all zero'),
    check('protected actions remain absent', report.protectedActionsExecuted.length === 0, 'zero'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all false'),
  ]

  writeFileSync(resolve(docsDir, 'verification-report-consistency-report.json'), `${JSON.stringify(report, null, 2)}\n`)
  writeMarkdown(report)

  for (const item of report.reportConsistencyChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  const failed = report.reportConsistencyChecks.filter((item) => !item.ok)
  if (failed.length > 0) {
    console.error(`RESULT: FAIL (${failed.length} failed checks)`)
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`obsolete_blocker_phrase_count=${report.obsoleteBlockerPhrasesFound.length}`)
  console.log(`source_typecheck_total_diagnostics=${report.sourceTypecheckTotalDiagnostics}`)
  console.log(`source_typecheck_diagnostic_budget=${report.sourceTypecheckDiagnosticBudget}`)
  console.log(`source_terminal_condition=${report.sourceTerminalCondition}`)
}

main()
