import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { scrubPublicArtifactText, scrubPublicArtifactValue } from './product-report-sanitizer'

type SourceInput = {
  sourceProject: string
  sourceUrl: string
  appliedPattern: string
}

type DocCheck = {
  label: string
  ok: boolean
  detail: string
}

type CommandCheck = {
  name: string
  command: string[]
  exitCode: number | null
  passed: boolean
  requiredSubstrings: string[]
  missingSubstrings: string[]
  stdoutPreview: string[]
  stderrPreview: string[]
}

type OnboardingSmokeReport = {
  generatedAt: string
  mode: 'local_no_provider_onboarding_smoke'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  primarySourceInputs: SourceInput[]
  readmePath: string
  windowsQuickStartPath: string
  macLinuxQuickStartPath: string
  readmeLinksWindowsQuickStart: boolean
  readmeLinksMacLinuxQuickStart: boolean
  windowsQuickStartPresent: boolean
  macLinuxQuickStartPresent: boolean
  installCommandDocumented: boolean
  startCommandDocumented: boolean
  nodeVersionCheckDocumented: boolean
  providerSetupDocumented: boolean
  providerFailureTroubleshootingDocumented: boolean
  updateAndUninstallDocumented: boolean
  advancedSetupLinked: boolean
  localRuntimeSmokePerformed: boolean
  crossPlatformRuntimeClaimAllowed: false
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  localSmokeCommands: CommandCheck[]
  onboardingChecks: DocCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const readmePath = 'README.md'
const windowsQuickStartPath = 'docs/quick-start-windows.md'
const macLinuxQuickStartPath = 'docs/quick-start-mac-linux.md'
const cliPath = resolve(root, 'dist/cli.mjs')

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function normalize(text: string | Buffer | null | undefined): string {
  return String(text ?? '').replace(/\r\n/g, '\n')
}

function preview(text: string): string[] {
  return text
    .split('\n')
    .map((line) => line.trimEnd())
    .filter((line) => line.length > 0)
    .slice(0, 80)
}

function safeEnv(): NodeJS.ProcessEnv {
  return {
    ...process.env,
    CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST: '1',
    CLAUDE_CODE_USE_OPENAI: '0',
    CLAUDE_CODE_USE_GEMINI: '0',
    CLAUDE_CODE_USE_GITHUB: '0',
    CLAUDE_CODE_USE_MISTRAL: '0',
    OPENAI_API_KEY: '',
    CODEX_API_KEY: '',
    GEMINI_API_KEY: '',
    GOOGLE_API_KEY: '',
    MISTRAL_API_KEY: '',
    GITHUB_TOKEN: '',
    GH_TOKEN: '',
    ANTHROPIC_API_KEY: '',
    OPENCLAUDE_PRODUCT_ONBOARDING_NO_PROVIDER: '1',
  }
}

function runLocalSmoke(name: string, args: string[], requiredSubstrings: string[]): CommandCheck {
  const command = [process.execPath, cliPath, ...args]
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    cwd: root,
    encoding: 'utf8',
    env: safeEnv(),
  })
  const stdout = normalize(result.stdout)
  const stderr = normalize(result.stderr)
  const combined = `${stdout}\n${stderr}`
  const missingSubstrings = requiredSubstrings.filter((substring) => !combined.includes(substring))
  return {
    name,
    command,
    exitCode: result.status,
    passed: result.status === 0 && missingSubstrings.length === 0,
    requiredSubstrings,
    missingSubstrings,
    stdoutPreview: preview(stdout),
    stderrPreview: preview(stderr),
  }
}

function check(label: string, ok: boolean, detail: string): DocCheck {
  return { label, ok, detail }
}

function hasAll(text: string, needles: string[]): boolean {
  return needles.every((needle) => text.includes(needle))
}

function writeReports(report: OnboardingSmokeReport): void {
  mkdirSync(docsDir, { recursive: true })
  const publicReport = scrubPublicArtifactValue(report)
  writeFileSync(resolve(docsDir, 'onboarding-smoke-report.json'), `${JSON.stringify(publicReport, null, 2)}\n`)

  const lines = [
    '# Onboarding Smoke Report',
    '',
    'Generated by: `bun run product:onboarding-smoke`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies local onboarding documentation structure and local CLI smoke commands only.',
    '- It does not install global packages, call providers, call live models, call external services, publish, deploy, launch, or claim release readiness.',
    '- macOS/Linux runtime execution is not claimed from this Windows-local run; only documented commands are checked for those platforms.',
    '',
    '## Summary',
    '',
    `- readme_links_windows_quick_start: \`${report.readmeLinksWindowsQuickStart}\``,
    `- readme_links_mac_linux_quick_start: \`${report.readmeLinksMacLinuxQuickStart}\``,
    `- windows_quick_start_present: \`${report.windowsQuickStartPresent}\``,
    `- mac_linux_quick_start_present: \`${report.macLinuxQuickStartPresent}\``,
    `- install_command_documented: \`${report.installCommandDocumented}\``,
    `- start_command_documented: \`${report.startCommandDocumented}\``,
    `- node_version_check_documented: \`${report.nodeVersionCheckDocumented}\``,
    `- provider_setup_documented: \`${report.providerSetupDocumented}\``,
    `- provider_failure_troubleshooting_documented: \`${report.providerFailureTroubleshootingDocumented}\``,
    `- update_and_uninstall_documented: \`${report.updateAndUninstallDocumented}\``,
    `- advanced_setup_linked: \`${report.advancedSetupLinked}\``,
    `- local_runtime_smoke_performed: \`${report.localRuntimeSmokePerformed}\``,
    `- local_smoke_commands_passed: \`${report.localSmokeCommands.every((item) => item.passed)}\``,
    `- onboarding_checks_passed: \`${report.onboardingChecks.every((item) => item.ok)}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Primary Source Inputs',
    '',
    '| Source | Applied Pattern |',
    '| --- | --- |',
    ...report.primarySourceInputs.map((item) => `| [${item.sourceProject}](${item.sourceUrl}) | ${item.appliedPattern} |`),
    '',
    '## Documentation Checks',
    '',
    '| Check | OK | Detail |',
    '| --- | --- | --- |',
    ...report.onboardingChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
    '## Local Smoke Commands',
    '',
  ]

  for (const command of report.localSmokeCommands) {
    lines.push(`### ${command.name}`)
    lines.push('')
    lines.push(`- command: \`${command.command.join(' ')}\``)
    lines.push(`- exit_code: \`${command.exitCode}\``)
    lines.push(`- passed: \`${command.passed}\``)
    if (command.missingSubstrings.length > 0) {
      lines.push(`- missing_substrings: \`${command.missingSubstrings.join(', ')}\``)
    }
    lines.push('')
    lines.push('```text')
    lines.push(...command.stdoutPreview)
    if (command.stderrPreview.length > 0) {
      lines.push('--- stderr ---')
      lines.push(...command.stderrPreview)
    }
    lines.push('```')
    lines.push('')
  }

  writeFileSync(resolve(docsDir, 'onboarding-smoke-report.md'), `${scrubPublicArtifactText(lines.join('\n'))}\n`)
}

function main(): void {
  const readmeExists = existsSync(resolve(root, readmePath))
  const windowsExists = existsSync(resolve(root, windowsQuickStartPath))
  const macLinuxExists = existsSync(resolve(root, macLinuxQuickStartPath))
  const readme = readmeExists ? readText(readmePath) : ''
  const windows = windowsExists ? readText(windowsQuickStartPath) : ''
  const macLinux = macLinuxExists ? readText(macLinuxQuickStartPath) : ''
  const combinedDocs = `${readme}\n${windows}\n${macLinux}`

  const localSmokeCommands = existsSync(cliPath)
    ? [
      runLocalSmoke('version', ['--version'], ['Open Claude']),
      runLocalSmoke('help', ['--help'], ['Usage: claude', '--provider <provider>', 'doctor']),
      runLocalSmoke('doctor_help', ['doctor', '--help'], ['Usage: claude doctor', 'health', '-h, --help']),
    ]
    : []

  const report: OnboardingSmokeReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_onboarding_smoke',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    primarySourceInputs: [
      {
        sourceProject: 'openai/codex',
        sourceUrl: 'https://github.com/openai/codex',
        appliedPattern: 'Treat first-run CLI documentation, local command probes, and clear claim boundaries as part of product quality.',
      },
      {
        sourceProject: 'Aider-AI/aider',
        sourceUrl: 'https://github.com/Aider-AI/aider',
        appliedPattern: 'Keep installation/start paths explicit and test the local CLI surface before making user-facing onboarding claims.',
      },
      {
        sourceProject: 'opencode-ai/opencode',
        sourceUrl: 'https://github.com/opencode-ai/opencode',
        appliedPattern: 'Use platform-aware quick-start paths and local command evidence without turning docs into unsupported runtime claims.',
      },
    ],
    readmePath,
    windowsQuickStartPath,
    macLinuxQuickStartPath,
    readmeLinksWindowsQuickStart: /\[Windows Quick Start\]\(docs\/quick-start-windows\.md\)/.test(readme),
    readmeLinksMacLinuxQuickStart: /\[macOS \/ Linux Quick Start\]\(docs\/quick-start-mac-linux\.md\)/.test(readme),
    windowsQuickStartPresent: windowsExists && /Windows PowerShell/.test(windows) && /```powershell/.test(windows),
    macLinuxQuickStartPresent: macLinuxExists && /macOS and Linux/.test(macLinux) && /```bash/.test(macLinux),
    installCommandDocumented: /npm install -g @gitlawb\/openclaude/.test(combinedDocs),
    startCommandDocumented: /(^|\n)openclaude(\n|$)/.test(combinedDocs),
    nodeVersionCheckDocumented: hasAll(combinedDocs, ['node --version', 'npm --version']),
    providerSetupDocumented: hasAll(combinedDocs, ['OpenAI', 'DeepSeek', 'Ollama', 'LM Studio']),
    providerFailureTroubleshootingDocumented: hasAll(combinedDocs, ['If Your Provider Fails', 'make sure the key is real', 'make sure Ollama is running']),
    updateAndUninstallDocumented: hasAll(combinedDocs, ['npm install -g @gitlawb/openclaude@latest', 'npm uninstall -g @gitlawb/openclaude']),
    advancedSetupLinked: hasAll(combinedDocs, ['Advanced Setup', 'advanced-setup.md']),
    localRuntimeSmokePerformed: localSmokeCommands.length === 3,
    crossPlatformRuntimeClaimAllowed: false,
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    localSmokeCommands,
    onboardingChecks: [],
    claimBoundary: 'This report verifies local onboarding documentation and built CLI smoke commands only; it does not install global packages, execute providers, run macOS/Linux, publish, deploy, launch, or make release/readiness/external/autonomous reliability claims.',
  }

  report.onboardingChecks = [
    check('README links Windows quick start', report.readmeLinksWindowsQuickStart, windowsQuickStartPath),
    check('README links macOS/Linux quick start', report.readmeLinksMacLinuxQuickStart, macLinuxQuickStartPath),
    check('Windows quick start is present and PowerShell-scoped', report.windowsQuickStartPresent, windowsQuickStartPath),
    check('macOS/Linux quick start is present and shell-scoped', report.macLinuxQuickStartPresent, macLinuxQuickStartPath),
    check('global install command is documented', report.installCommandDocumented, 'npm install -g @gitlawb/openclaude'),
    check('start command is documented', report.startCommandDocumented, 'openclaude'),
    check('Node/npm version checks are documented', report.nodeVersionCheckDocumented, 'node --version / npm --version'),
    check('provider setup options are documented', report.providerSetupDocumented, 'OpenAI, DeepSeek, Ollama, LM Studio'),
    check('provider failure troubleshooting is documented', report.providerFailureTroubleshootingDocumented, 'provider failure basics'),
    check('update and uninstall commands are documented', report.updateAndUninstallDocumented, 'latest/uninstall commands'),
    check('advanced setup is linked', report.advancedSetupLinked, 'advanced-setup.md'),
    check('local CLI smoke commands are performed', report.localRuntimeSmokePerformed, 'version/help/doctor_help'),
    check('local CLI smoke commands pass', report.localSmokeCommands.every((item) => item.passed), report.localSmokeCommands.map((item) => `${item.name}:${item.passed}`).join(',')),
    check('cross-platform runtime claims remain blocked', report.crossPlatformRuntimeClaimAllowed === false, 'macOS/Linux runtime not executed in this local run'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all claim booleans false'),
  ]

  writeReports(report)

  for (const item of report.onboardingChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!report.onboardingChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`local_runtime_smoke_performed=${report.localRuntimeSmokePerformed}`)
  console.log(`local_smoke_command_count=${report.localSmokeCommands.length}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
  console.log(`cross_platform_runtime_claim_allowed=${report.crossPlatformRuntimeClaimAllowed}`)
}

main()
