import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type Check = {
  label: string
  ok: boolean
  detail: string
}

type SourceInput = {
  sourceProject: string
  sourceUrl: string
  observedPattern: string
  localAbsorption: string
}

type CodeownerRule = {
  line: number
  pattern: string
  owners: string[]
}

type MaintainerOwnershipQualityReport = {
  generatedAt: string
  mode: 'local_no_provider_maintainer_ownership_quality'
  primarySourceInputs: SourceInput[]
  codeownersPath: string
  codeownersSha256: string
  codeownersSizeBytes: number
  codeownersPreferredLocation: boolean
  codeownersUnderGithubLimit: boolean
  codeownerRules: CodeownerRule[]
  requiredPatterns: string[]
  missingRequiredPatterns: string[]
  ownerTokens: string[]
  invalidSyntaxLines: Array<{ line: number; reason: string }>
  hostedCodeownerResolutionPerformed: false
  branchProtectionQueryPerformed: false
  codeOwnerReviewRequiredClaimAllowed: false
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  claimBoundary: string
  ownershipChecks: Check[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const codeownersPath = '.github/CODEOWNERS'
const githubCodeownersSizeLimitBytes = 3 * 1024 * 1024
const requiredPatterns = [
  '*',
  '/.github/',
  '/src/',
  '/scripts/',
  '/packages/openclaude-vscode/',
  '/docs/product-quality/',
  '/reports/',
  '/package.json',
  '/README.md',
  '/CONTRIBUTING.md',
  '/SUPPORT.md',
  '/CODE_OF_CONDUCT.md',
  '/SECURITY.md',
  '/LICENSE',
]

function sha256(input: string | Buffer): string {
  return createHash('sha256').update(input).digest('hex')
}

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function fileSha256(path: string): string {
  return sha256(readFileSync(resolve(root, path)))
}

function check(label: string, ok: boolean, detail: string): Check {
  return { label, ok, detail }
}

function parseCodeowners(text: string): { rules: CodeownerRule[]; invalidSyntaxLines: Array<{ line: number; reason: string }> } {
  const rules: CodeownerRule[] = []
  const invalidSyntaxLines: Array<{ line: number; reason: string }> = []
  const lines = text.split(/\r?\n/)

  lines.forEach((rawLine, index) => {
    const lineNumber = index + 1
    const line = rawLine.trim()
    if (line.length === 0 || line.startsWith('#')) {
      return
    }

    const parts = line.split(/\s+/)
    const [pattern, ...owners] = parts
    if (!pattern || owners.length === 0) {
      invalidSyntaxLines.push({ line: lineNumber, reason: 'missing_pattern_or_owner' })
      return
    }

    if (pattern.startsWith('!')) {
      invalidSyntaxLines.push({ line: lineNumber, reason: 'negation_pattern_not_supported_by_codeowners' })
    }
    if (/\\#/.test(pattern)) {
      invalidSyntaxLines.push({ line: lineNumber, reason: 'escaped_hash_pattern_not_supported_by_codeowners' })
    }
    if (/\[[^\]]+\]/.test(pattern)) {
      invalidSyntaxLines.push({ line: lineNumber, reason: 'character_range_pattern_not_supported_by_codeowners' })
    }

    const invalidOwners = owners.filter((owner) => !/^@[A-Za-z0-9-]+(?:\/[A-Za-z0-9._-]+)?$/.test(owner))
    if (invalidOwners.length > 0) {
      invalidSyntaxLines.push({ line: lineNumber, reason: `invalid_owner_token:${invalidOwners.join(',')}` })
    }

    rules.push({ line: lineNumber, pattern, owners })
  })

  return { rules, invalidSyntaxLines }
}

function writeMarkdown(report: MaintainerOwnershipQualityReport): void {
  const sourceRows = report.primarySourceInputs
    .map((source) => `| ${source.sourceProject} | ${source.sourceUrl} | ${source.localAbsorption} |`)
    .join('\n')
  const ruleRows = report.codeownerRules
    .map((rule) => `| ${rule.line} | \`${rule.pattern}\` | ${rule.owners.map((owner) => `\`${owner}\``).join(', ')} |`)
    .join('\n')
  const requiredRows = report.requiredPatterns
    .map((pattern) => `| \`${pattern}\` | \`${!report.missingRequiredPatterns.includes(pattern)}\` |`)
    .join('\n')
  const checkRows = report.ownershipChecks
    .map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`)
    .join('\n')

  const markdown = `# Maintainer Ownership Quality Report

Generated by: \`bun run product:maintainer-ownership-quality\`

## Claim Boundary

- This report verifies local source-controlled ownership and review-routing evidence only.
- It does not call GitHub APIs, providers, live models, or external services.
- It does not query hosted branch protection, enable required code-owner review, mutate repository settings, publish, deploy, launch, or claim release readiness.
- Hosted branch protection and actual owner write-permission resolution remain external protected evidence gaps.

## Summary

- mode: \`${report.mode}\`
- codeowners_path: \`${report.codeownersPath}\`
- codeowners_sha256: \`${report.codeownersSha256}\`
- codeowners_size_bytes: \`${report.codeownersSizeBytes}\`
- codeowners_preferred_location: \`${report.codeownersPreferredLocation}\`
- codeowners_under_github_limit: \`${report.codeownersUnderGithubLimit}\`
- required_pattern_count: \`${report.requiredPatterns.length}\`
- missing_required_pattern_count: \`${report.missingRequiredPatterns.length}\`
- owner_token_count: \`${report.ownerTokens.length}\`
- invalid_syntax_line_count: \`${report.invalidSyntaxLines.length}\`
- hosted_codeowner_resolution_performed: \`${report.hostedCodeownerResolutionPerformed}\`
- branch_protection_query_performed: \`${report.branchProtectionQueryPerformed}\`
- code_owner_review_required_claim_allowed: \`${report.codeOwnerReviewRequiredClaimAllowed}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`

## Primary Sources

| Source | URL | Local Absorption |
| --- | --- | --- |
${sourceRows}

## CODEOWNERS Rules

| Line | Pattern | Owners |
| ---: | --- | --- |
${ruleRows}

## Required Pattern Coverage

| Pattern | Present |
| --- | --- |
${requiredRows}

## Checks

| Check | Result | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'maintainer-ownership-quality-report.md'), markdown)
}

function main(): void {
  mkdirSync(docsDir, { recursive: true })

  const codeownersExists = existsSync(resolve(root, codeownersPath))
  const codeownersText = codeownersExists ? readText(codeownersPath) : ''
  const codeownersSha256 = codeownersExists ? fileSha256(codeownersPath) : 'missing'
  const codeownersSizeBytes = codeownersExists ? statSync(resolve(root, codeownersPath)).size : 0
  const { rules, invalidSyntaxLines } = parseCodeowners(codeownersText)
  const presentPatterns = new Set(rules.map((rule) => rule.pattern))
  const missingRequiredPatterns = requiredPatterns.filter((pattern) => !presentPatterns.has(pattern))
  const ownerTokens = [...new Set(rules.flatMap((rule) => rule.owners))].sort((left, right) => left.localeCompare(right))

  const report: MaintainerOwnershipQualityReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_maintainer_ownership_quality',
    primarySourceInputs: [
      {
        sourceProject: 'GitHub Docs CODEOWNERS',
        sourceUrl: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners',
        observedPattern: 'CODEOWNERS defines repository file owners, triggers review routing for pull requests, has supported locations and syntax limits, and should protect the CODEOWNERS file or .github directory itself.',
        localAbsorption: 'OpenClaude now keeps a source-controlled .github/CODEOWNERS map and verifies required ownership patterns without claiming hosted enforcement.',
      },
      {
        sourceProject: 'GitHub Docs protected branches',
        sourceUrl: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches',
        observedPattern: 'Required reviews and protected branches are repository settings, so local source evidence must not be treated as hosted enforcement.',
        localAbsorption: 'OpenClaude records branch-protection/query enforcement as not performed and keeps required code-owner review claims blocked.',
      },
      {
        sourceProject: 'OpenSSF Scorecard checks',
        sourceUrl: 'https://github.com/ossf/scorecard/blob/main/docs/checks.md',
        observedPattern: 'Open-source security posture improves when review, branch protection, maintained status, packaging, and release practices are auditable instead of implicit.',
        localAbsorption: 'OpenClaude adds local ownership-routing evidence as another product-quality axis while leaving hosted review enforcement as an unresolved protected gap.',
      },
    ],
    codeownersPath,
    codeownersSha256,
    codeownersSizeBytes,
    codeownersPreferredLocation: codeownersPath === '.github/CODEOWNERS',
    codeownersUnderGithubLimit: codeownersSizeBytes > 0 && codeownersSizeBytes < githubCodeownersSizeLimitBytes,
    codeownerRules: rules,
    requiredPatterns,
    missingRequiredPatterns,
    ownerTokens,
    invalidSyntaxLines,
    hostedCodeownerResolutionPerformed: false,
    branchProtectionQueryPerformed: false,
    codeOwnerReviewRequiredClaimAllowed: false,
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    claimBoundary: 'Maintainer ownership quality is local source-controlled review-routing evidence only. It does not prove hosted CODEOWNERS resolution, branch protection, required review enforcement, release readiness, public readiness, production readiness, external validation, or autonomous reliability.',
    ownershipChecks: [],
  }

  report.ownershipChecks = [
    check('CODEOWNERS exists in preferred .github location', codeownersExists && report.codeownersPreferredLocation, codeownersPath),
    check('CODEOWNERS is below GitHub size limit', report.codeownersUnderGithubLimit, `${codeownersSizeBytes}/${githubCodeownersSizeLimitBytes} bytes`),
    check('CODEOWNERS has parseable ownership rules', rules.length >= requiredPatterns.length && invalidSyntaxLines.length === 0, `${rules.length} rules; ${invalidSyntaxLines.length} invalid lines`),
    check('required ownership patterns are covered', missingRequiredPatterns.length === 0, missingRequiredPatterns.join(',') || 'all present'),
    check('default owner and protected surfaces are explicit', presentPatterns.has('*') && presentPatterns.has('/.github/') && presentPatterns.has('/src/') && presentPatterns.has('/scripts/') && presentPatterns.has('/packages/openclaude-vscode/'), ownerTokens.join(',')),
    check('owner tokens use GitHub user or team syntax', ownerTokens.length > 0 && ownerTokens.every((owner) => /^@[A-Za-z0-9-]+(?:\/[A-Za-z0-9._-]+)?$/.test(owner)), ownerTokens.join(',')),
    check('primary-source inputs are official or maintained source references', report.primarySourceInputs.every((source) => source.sourceUrl.startsWith('https://docs.github.com/') || source.sourceUrl.startsWith('https://github.com/ossf/scorecard/')), report.primarySourceInputs.map((source) => source.sourceProject).join(',')),
    check('hosted CODEOWNERS and branch protection enforcement remain unclaimed', report.hostedCodeownerResolutionPerformed === false && report.branchProtectionQueryPerformed === false && report.codeOwnerReviewRequiredClaimAllowed === false, 'local source evidence only'),
    check('provider live external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all call arrays empty'),
    check('protected actions remain absent', report.protectedActionsExecuted.length === 0, 'zero'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all false'),
  ]

  writeFileSync(resolve(docsDir, 'maintainer-ownership-quality-report.json'), `${JSON.stringify(report, null, 2)}\n`)
  writeMarkdown(report)

  for (const item of report.ownershipChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  const failed = report.ownershipChecks.filter((item) => !item.ok)
  if (failed.length > 0) {
    console.error(`RESULT: FAIL (${failed.length} failed checks)`)
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`codeowners_path=${report.codeownersPath}`)
  console.log(`codeowner_rule_count=${report.codeownerRules.length}`)
  console.log(`owner_token_count=${report.ownerTokens.length}`)
  console.log(`hosted_codeowner_resolution_performed=${report.hostedCodeownerResolutionPerformed}`)
  console.log(`branch_protection_query_performed=${report.branchProtectionQueryPerformed}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
