import { spawnSync } from 'node:child_process'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

type PackageJson = {
  name: string
  version: string
  files?: string[]
  bin?: Record<string, string>
}

type PackFile = {
  path: string
  size: number
  mode: number
}

type PackArtifact = {
  id: string
  name: string
  version: string
  filename: string
  files: PackFile[]
  entryCount: number
  size: number
  unpackedSize: number
}

type ArtifactCheck = {
  label: string
  ok: boolean
  detail: string
}

type ReleaseArtifactFileListReport = {
  generatedAt: string
  mode: 'local_no_provider_release_artifact_file_list'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  packCommand: string[]
  packDryRunExitCode: number | null
  publishAttempted: false
  deployAttempted: false
  launchAttempted: false
  packageFilesField: string[]
  expectedPackageFiles: string[]
  actualPackageFiles: string[]
  forbiddenPackageFilePatterns: string[]
  forbiddenPackageFiles: string[]
  artifactSizeBytes: number
  artifactUnpackedSizeBytes: number
  releaseArtifactChecks: ArtifactCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const expectedPackageFiles = [
  'LICENSE',
  'README.md',
  'package.json',
  'bin/openclaude',
  'bin/openclaude.cmd',
  'dist/cli.mjs',
]
const forbiddenPackageFilePatterns = [
  'bin/.openclaude/',
  'bin/.playwright-mcp/',
  'bin/*.png',
  'bin/*.test.*',
  'bin/import-specifier.mjs',
  'bin/nodeHeapBootstrap.mjs',
  '*.map',
  '.env',
  'docs/product-quality/',
]

function readJson<T>(path: string): T {
  return JSON.parse(readFileSync(resolve(root, path), 'utf8')) as T
}

function parsePackJson(stdout: string): PackArtifact | null {
  const start = stdout.indexOf('[')
  const end = stdout.lastIndexOf(']')
  if (start < 0 || end < start) {
    return null
  }
  try {
    const payload = JSON.parse(stdout.slice(start, end + 1)) as PackArtifact[]
    return payload[0] ?? null
  } catch {
    return null
  }
}

function matchesForbiddenPattern(path: string, pattern: string): boolean {
  if (pattern.endsWith('/')) {
    return path.startsWith(pattern)
  }
  if (pattern === 'bin/*.png') {
    return path.startsWith('bin/') && path.endsWith('.png')
  }
  if (pattern === 'bin/*.test.*') {
    return path.startsWith('bin/') && path.includes('.test.')
  }
  if (pattern === '*.map') {
    return path.endsWith('.map')
  }
  return path === pattern
}

function check(label: string, ok: boolean, detail: string): ArtifactCheck {
  return { label, ok, detail }
}

function writeReports(report: ReleaseArtifactFileListReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'release-artifact-file-list-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const lines = [
    '# Release Artifact File List Report',
    '',
    'Generated by: `bun run product:release-artifact`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies local npm pack dry-run file-list behavior only.',
    '- It does not publish, deploy, launch, commit, push, call providers, call live models, or call external services.',
    '- It does not claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- pack_dry_run_exit_code: \`${report.packDryRunExitCode}\``,
    `- publish_attempted: \`${report.publishAttempted}\``,
    `- deploy_attempted: \`${report.deployAttempted}\``,
    `- launch_attempted: \`${report.launchAttempted}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    `- artifact_file_count: \`${report.actualPackageFiles.length}\``,
    `- forbidden_package_file_count: \`${report.forbiddenPackageFiles.length}\``,
    `- artifact_size_bytes: \`${report.artifactSizeBytes}\``,
    `- artifact_unpacked_size_bytes: \`${report.artifactUnpackedSizeBytes}\``,
    '',
    '## Expected Package Files',
    '',
    ...report.expectedPackageFiles.map((path) => `- \`${path}\``),
    '',
    '## Actual Package Files',
    '',
    ...report.actualPackageFiles.map((path) => `- \`${path}\``),
    '',
    '## Forbidden Package Files',
    '',
    report.forbiddenPackageFiles.length > 0
      ? report.forbiddenPackageFiles.map((path) => `- \`${path}\``).join('\n')
      : '- `none`',
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.releaseArtifactChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'release-artifact-file-list-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const pkg = readJson<PackageJson>('package.json')
  const packCommand = ['npm', 'pack', '--dry-run', '--json', '--ignore-scripts']
  const result = spawnSync('npm', ['pack', '--dry-run', '--json', '--ignore-scripts'], {
    cwd: root,
    encoding: 'utf8',
    shell: true,
  })
  const artifact = parsePackJson(String(result.stdout ?? ''))
  const actualPackageFiles = artifact?.files.map((file) => file.path).sort((left, right) => left.localeCompare(right)) ?? []
  const forbiddenPackageFiles = actualPackageFiles.filter((path) =>
    forbiddenPackageFilePatterns.some((pattern) => matchesForbiddenPattern(path, pattern)),
  )
  const missingExpectedFiles = expectedPackageFiles.filter((path) => !actualPackageFiles.includes(path))
  const unexpectedTopLevelProductDocs = actualPackageFiles.filter((path) => path.startsWith('docs/product-quality/'))
  const releaseArtifactChecks = [
    check('npm pack dry-run succeeded', result.status === 0 && artifact !== null, `exit=${result.status}`),
    check('package name matches manifest', artifact?.name === pkg.name, artifact?.name ?? 'missing'),
    check('package version matches manifest', artifact?.version === pkg.version, artifact?.version ?? 'missing'),
    check('package files field is explicit', Array.isArray(pkg.files) && pkg.files.length > 0, (pkg.files ?? []).join(', ')),
    check('expected files are present', missingExpectedFiles.length === 0, missingExpectedFiles.join(', ') || 'none'),
    check('forbidden package files are absent', forbiddenPackageFiles.length === 0, forbiddenPackageFiles.join(', ') || 'none'),
    check('product-quality docs are not packed', unexpectedTopLevelProductDocs.length === 0, unexpectedTopLevelProductDocs.join(', ') || 'none'),
    check('artifact file count is bounded', actualPackageFiles.length <= 12, String(actualPackageFiles.length)),
    check('artifact unpacked size is bounded', (artifact?.unpackedSize ?? Number.POSITIVE_INFINITY) < 25_000_000, String(artifact?.unpackedSize ?? 'missing')),
    check('publish was not attempted', true, 'dry-run file list only'),
    check('deploy was not attempted', true, 'dry-run file list only'),
    check('launch was not attempted', true, 'dry-run file list only'),
  ]

  const report: ReleaseArtifactFileListReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_release_artifact_file_list',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    packCommand,
    packDryRunExitCode: result.status,
    publishAttempted: false,
    deployAttempted: false,
    launchAttempted: false,
    packageFilesField: pkg.files ?? [],
    expectedPackageFiles,
    actualPackageFiles,
    forbiddenPackageFilePatterns,
    forbiddenPackageFiles,
    artifactSizeBytes: artifact?.size ?? 0,
    artifactUnpackedSizeBytes: artifact?.unpackedSize ?? 0,
    releaseArtifactChecks,
    claimBoundary: 'Release artifact file-list verification uses local npm pack dry-run only. It does not publish, deploy, launch, commit, push, call providers, or claim release readiness.',
  }

  writeReports(report)

  for (const item of releaseArtifactChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!releaseArtifactChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`pack_dry_run_exit_code=${report.packDryRunExitCode}`)
  console.log(`artifact_file_count=${report.actualPackageFiles.length}`)
  console.log(`forbidden_package_file_count=${report.forbiddenPackageFiles.length}`)
  console.log(`publish_attempted=${report.publishAttempted}`)
  console.log(`deploy_attempted=${report.deployAttempted}`)
  console.log(`launch_attempted=${report.launchAttempted}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
