import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, isAbsolute, normalize, relative, resolve } from 'node:path'

type SourceInput = {
  sourceProject: string
  sourceUrl: string
  appliedPattern: string
}

type LinkCheck = {
  sourcePath: string
  linkText: string
  href: string
  resolvedPath: string
  ok: boolean
}

type IntegrityCheck = {
  label: string
  ok: boolean
  detail: string
}

type DocLinkIntegrityReport = {
  generatedAt: string
  mode: 'local_no_provider_doc_link_integrity'
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  externalLinkFetchPerformed: false
  primarySourceInputs: SourceInput[]
  scannedMarkdownFiles: string[]
  canonicalVsCodeExtensionPath: string
  legacyVsCodeExtensionPath: string
  relativeLinksChecked: LinkCheck[]
  allRelativeLinksResolve: boolean
  readmeUsesCanonicalVsCodeExtensionPath: boolean
  readmeLegacyVsCodeExtensionPathAbsent: boolean
  packageExtensionSurfaceExists: boolean
  claimBoundary: string
  integrityChecks: IntegrityCheck[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const canonicalVsCodeExtensionPath = 'packages/openclaude-vscode'
const legacyVsCodeExtensionPath = 'vscode-extension/openclaude-vscode'
const scannedMarkdownFiles = [
  'README.md',
  'docs/quick-start-windows.md',
  'docs/quick-start-mac-linux.md',
  'docs/product-quality/product-quality-gate.md',
  'docs/product-quality/competitive-scorecard.md',
  'docs/MIMESIS_ENGINEERING.md',
  'docs/marketing/README.md',
  'docs/marketing/metaforge-public-proof-pack-2026-06-18.md',
  'docs/marketing/metaforge-public-proof-pack-2026-06-14.md',
  'docs/research/public-proof-pack-source-ledger-2026-06-18.md',
  'docs/research/public-proof-pack-source-ledger-2026-06-14.md',
]

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function stripAnchor(href: string): string {
  return href.split('#')[0]
}

function isExternalOrAnchor(href: string): boolean {
  return (
    href.startsWith('#') ||
    /^[a-z][a-z0-9+.-]*:/i.test(href) ||
    href.startsWith('//')
  )
}

function decodeHref(href: string): string {
  try {
    return decodeURIComponent(href)
  } catch {
    return href
  }
}

function resolveLocalHref(sourcePath: string, href: string): string {
  const withoutAnchor = stripAnchor(href)
  const decoded = decodeHref(withoutAnchor)
  if (decoded.startsWith('/')) {
    return normalize(resolve(root, `.${decoded}`))
  }
  return normalize(resolve(root, dirname(sourcePath), decoded))
}

function toReportPath(path: string): string {
  const relativePath = relative(root, path)
  if (relativePath === '') {
    return '<repo>'
  }
  if (!relativePath.startsWith('..') && !isAbsolute(relativePath)) {
    return `<repo>/${relativePath.replace(/\\/g, '/')}`
  }
  return '<outside-repo>'
}

function extractRelativeLinks(sourcePath: string): LinkCheck[] {
  const text = readText(sourcePath)
  const checks: LinkCheck[] = []
  const linkPattern = /!?\[([^\]]*)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g
  for (const match of text.matchAll(linkPattern)) {
    const linkText = match[1] ?? ''
    const href = match[2] ?? ''
    if (isExternalOrAnchor(href)) {
      continue
    }
    const resolvedPath = resolveLocalHref(sourcePath, href)
    checks.push({
      sourcePath,
      linkText,
      href,
      resolvedPath: toReportPath(resolvedPath),
      ok: existsSync(resolvedPath),
    })
  }
  return checks
}

function check(label: string, ok: boolean, detail: string): IntegrityCheck {
  return { label, ok, detail }
}

function writeReports(report: DocLinkIntegrityReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(resolve(docsDir, 'doc-link-integrity-report.json'), `${JSON.stringify(report, null, 2)}\n`)

  const lines = [
    '# Documentation Link Integrity Report',
    '',
    'Generated by: `bun run product:doc-link-integrity`',
    '',
    '## Claim Boundary',
    '',
    '- This report verifies local documentation links and canonical product-surface paths only.',
    '- It does not fetch external links, call providers, call live models, call external services, publish, deploy, launch, or claim release readiness.',
    '',
    '## Summary',
    '',
    `- scanned_markdown_file_count: \`${report.scannedMarkdownFiles.length}\``,
    `- relative_links_checked: \`${report.relativeLinksChecked.length}\``,
    `- all_relative_links_resolve: \`${report.allRelativeLinksResolve}\``,
    `- readme_uses_canonical_vscode_extension_path: \`${report.readmeUsesCanonicalVsCodeExtensionPath}\``,
    `- readme_legacy_vscode_extension_path_absent: \`${report.readmeLegacyVsCodeExtensionPathAbsent}\``,
    `- package_extension_surface_exists: \`${report.packageExtensionSurfaceExists}\``,
    `- external_link_fetch_performed: \`${report.externalLinkFetchPerformed}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Primary Source Inputs',
    '',
    '| Source | Applied Pattern |',
    '| --- | --- |',
    ...report.primarySourceInputs.map((item) => `| [${item.sourceProject}](${item.sourceUrl}) | ${item.appliedPattern} |`),
    '',
    '## Integrity Checks',
    '',
    '| Check | OK | Detail |',
    '| --- | --- | --- |',
    ...report.integrityChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
    '## Relative Links',
    '',
    '| Source | Link | Target | OK |',
    '| --- | --- | --- | --- |',
    ...report.relativeLinksChecked.map((item) => `| ${item.sourcePath} | ${item.linkText} | ${item.href} | \`${item.ok}\` |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'doc-link-integrity-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const readme = readText('README.md')
  const relativeLinksChecked = scannedMarkdownFiles.flatMap((path) => extractRelativeLinks(path))
  const allRelativeLinksResolve = relativeLinksChecked.every((item) => item.ok)
  const readmeUsesCanonicalVsCodeExtensionPath = readme.includes(canonicalVsCodeExtensionPath)
  const readmeLegacyVsCodeExtensionPathAbsent = !readme.includes(legacyVsCodeExtensionPath)
  const packageExtensionSurfaceExists = [
    `${canonicalVsCodeExtensionPath}/package.json`,
    `${canonicalVsCodeExtensionPath}/README.md`,
    `${canonicalVsCodeExtensionPath}/dist/extension.js`,
  ].every((path) => existsSync(resolve(root, path)) && statSync(resolve(root, path)).isFile())

  const report: DocLinkIntegrityReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_doc_link_integrity',
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    externalLinkFetchPerformed: false,
    primarySourceInputs: [
      {
        sourceProject: 'github/docs',
        sourceUrl: 'https://docs.github.com/articles/relative-links-in-readmes',
        appliedPattern: 'Treat relative README and documentation links as repository-local navigation that should resolve from the current branch.',
      },
      {
        sourceProject: 'openai/codex',
        sourceUrl: 'https://github.com/openai/codex',
        appliedPattern: 'Keep user-facing setup and product-surface documentation aligned with the actual package layout.',
      },
      {
        sourceProject: 'continuedev/continue',
        sourceUrl: 'https://github.com/continuedev/continue',
        appliedPattern: 'Make documentation/source-control quality checks executable instead of relying on manual review.',
      },
    ],
    scannedMarkdownFiles,
    canonicalVsCodeExtensionPath,
    legacyVsCodeExtensionPath,
    relativeLinksChecked,
    allRelativeLinksResolve,
    readmeUsesCanonicalVsCodeExtensionPath,
    readmeLegacyVsCodeExtensionPathAbsent,
    packageExtensionSurfaceExists,
    claimBoundary: 'This local report verifies markdown link resolution and canonical product-surface paths only; it does not fetch external URLs, publish, deploy, launch, or make release/readiness/external/autonomous reliability claims.',
    integrityChecks: [],
  }

  report.integrityChecks = [
    check('scanned markdown files exist', scannedMarkdownFiles.every((path) => existsSync(resolve(root, path))), scannedMarkdownFiles.join(',')),
    check('all local relative links resolve', allRelativeLinksResolve, relativeLinksChecked.filter((item) => !item.ok).map((item) => `${item.sourcePath}:${item.href}`).join(',') || 'all resolved'),
    check('README uses canonical VS Code extension path', readmeUsesCanonicalVsCodeExtensionPath, canonicalVsCodeExtensionPath),
    check('README omits legacy VS Code extension path', readmeLegacyVsCodeExtensionPathAbsent, legacyVsCodeExtensionPath),
    check('canonical VS Code extension package surface exists', packageExtensionSurfaceExists, `${canonicalVsCodeExtensionPath}/package.json, README.md, dist/extension.js`),
    check('external link fetch remains blocked', report.externalLinkFetchPerformed === false, 'external links are not fetched in this local gate'),
    check('provider/live/external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all call arrays empty'),
  ]

  writeReports(report)

  for (const item of report.integrityChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!report.integrityChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`scanned_markdown_files=${report.scannedMarkdownFiles.length}`)
  console.log(`relative_links_checked=${report.relativeLinksChecked.length}`)
  console.log(`all_relative_links_resolve=${report.allRelativeLinksResolve}`)
  console.log(`external_link_fetch_performed=${report.externalLinkFetchPerformed}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
