import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { check, fileSha256, includesAll, readText, type Check } from './quality-report-helpers'

type PackageJson = {
  scripts?: Record<string, string>
}

type AgentInstructionsQualityReport = {
  generatedAt: string
  mode: 'local_no_provider_agent_instructions_quality'
  sourceAgentInstructionsPath: string
  sourceAgentInstructionsSha256: string
  sourcePackageJsonPath: string
  sourcePackageJsonSha256: string
  sourceWorkflowPaths: string[]
  sourceWorkflowSha256: Record<string, string>
  primarySourceInputs: Array<{
    sourceProject: string
    sourceUrl: string
    observedPattern: string
    localAbsorption: string
  }>
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  protectedActionsExecuted: []
  purposeSectionPresent: boolean
  setupVerificationCommandsPresent: string[]
  repositoryStructureSectionsPresent: string[]
  workflowEvidencePresent: boolean
  agentStackBoundariesPresent: string[]
  primarySourceRulePresent: boolean
  verificationStandardPresent: boolean
  protectedBoundaryLanguagePresent: boolean
  publicInstructionLineCount: number
  publicInstructionMaxLines: number
  privateMemoryDumpPresent: boolean
  stalePublicModelLockPresent: boolean
  localPathLeakPresent: boolean
  claimBoundary: string
  releaseReadinessClaimAllowed: false
  productionReadinessClaimAllowed: false
  publicReadinessClaimAllowed: false
  externalValidationClaimAllowed: false
  autonomousReliabilityClaimAllowed: false
  instructionQualityChecks: Check[]
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const agentInstructionsPath = 'AGENTS.md'
const packageJsonPath = 'package.json'
const workflowPaths = [
  '.github/workflows/pr-checks.yml',
  '.github/workflows/codeql.yml',
  '.github/dependabot.yml',
]

function privateLocalPathNeedles(): string[] {
  return [
    `C:${'\\\\'}Users`,
    `C:${'/'}Users`,
    ['내 순수', ' 재미'].join(''),
  ]
}

function writeMarkdown(report: AgentInstructionsQualityReport): void {
  const checkRows = report.instructionQualityChecks
    .map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`)
    .join('\n')
  const sourceRows = report.primarySourceInputs
    .map((source) => `| ${source.sourceProject} | ${source.sourceUrl} | ${source.localAbsorption} |`)
    .join('\n')
  const workflowRows = report.sourceWorkflowPaths
    .map((path) => `| \`${path}\` | \`${report.sourceWorkflowSha256[path] ?? 'missing'}\` |`)
    .join('\n')

  const markdown = `# Agent Instructions Quality Report

Generated by: \`bun run product:agent-instructions-quality\`

## Claim Boundary

- This is a local no-provider quality report for repository agent instructions.
- It uses primary-source guidance from OpenHands repository-agent and skill documentation as a local product-quality pattern.
- It does not call providers, live models, or external services.
- It does not install dependencies, publish, deploy, launch, modify production systems, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.

## Summary

- mode: \`${report.mode}\`
- source_agent_instructions: \`${report.sourceAgentInstructionsPath}\`
- purpose_section_present: \`${report.purposeSectionPresent}\`
- setup_verification_commands_present: \`${report.setupVerificationCommandsPresent.join(',')}\`
- repository_structure_sections_present: \`${report.repositoryStructureSectionsPresent.join(',')}\`
- workflow_evidence_present: \`${report.workflowEvidencePresent}\`
- agent_stack_boundaries_present: \`${report.agentStackBoundariesPresent.join(',')}\`
- primary_source_rule_present: \`${report.primarySourceRulePresent}\`
- verification_standard_present: \`${report.verificationStandardPresent}\`
- protected_boundary_language_present: \`${report.protectedBoundaryLanguagePresent}\`
- public_instruction_line_count: \`${report.publicInstructionLineCount}\`
- public_instruction_max_lines: \`${report.publicInstructionMaxLines}\`
- private_memory_dump_present: \`${report.privateMemoryDumpPresent}\`
- stale_public_model_lock_present: \`${report.stalePublicModelLockPresent}\`
- local_path_leak_present: \`${report.localPathLeakPresent}\`
- provider_calls_performed: \`${report.providerCallsPerformed.length}\`
- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\`
- external_calls_performed: \`${report.externalCallsPerformed.length}\`
- protected_actions_executed: \`${report.protectedActionsExecuted.length}\`
- release_readiness_claim_allowed: \`${report.releaseReadinessClaimAllowed}\`
- production_readiness_claim_allowed: \`${report.productionReadinessClaimAllowed}\`
- public_readiness_claim_allowed: \`${report.publicReadinessClaimAllowed}\`
- external_validation_claim_allowed: \`${report.externalValidationClaimAllowed}\`
- autonomous_reliability_claim_allowed: \`${report.autonomousReliabilityClaimAllowed}\`

## Primary Sources

| Source | URL | Local Absorption |
| --- | --- | --- |
${sourceRows}

## Workflow Evidence Inputs

| Path | SHA-256 |
| --- | --- |
${workflowRows}

## Checks

| Check | Result | Detail |
| --- | --- | --- |
${checkRows}
`

  writeFileSync(resolve(docsDir, 'agent-instructions-quality-report.md'), markdown)
}

function main(): void {
  mkdirSync(docsDir, { recursive: true })

  const agentInstructions = readText(agentInstructionsPath)
  const packageJson = JSON.parse(readText(packageJsonPath)) as PackageJson
  const workflowSha256: Record<string, string> = {}
  for (const path of workflowPaths) {
    if (existsSync(resolve(root, path))) {
      workflowSha256[path] = fileSha256(path)
    }
  }

  const setupVerificationCommandsPresent = includesAll(agentInstructions, [
    'bun run build',
    'bun run typecheck',
    'bun run product:quality',
    'bun run verify:privacy',
  ])
  const repositoryStructureSectionsPresent = includesAll(agentInstructions, [
    'src/',
    'scripts/',
    'docs/',
    'reports/',
    'packages/openclaude-vscode/',
    '.github/',
  ])
  const agentStackBoundariesPresent = includesAll(agentInstructions, [
    'GStack',
    'GSD',
    'Superpowers',
  ])
  const publicInstructionLineCount = agentInstructions.split(/\r?\n/).length
  const privateMemoryDumpPresent = /OpenClaude Orchestrator Memory|User's intent|Diagnostic finding:/.test(agentInstructions)
  const stalePublicModelLockPresent = /\b(gpt-5\.1|sonnet 4\.5|Opus 4\.7)\b/i.test(agentInstructions)
  const localPathLeakPresent = privateLocalPathNeedles().some((needle) => agentInstructions.includes(needle))

  const productQualityScript = packageJson.scripts?.['product:quality'] ?? ''
  const report: AgentInstructionsQualityReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_agent_instructions_quality',
    sourceAgentInstructionsPath: agentInstructionsPath,
    sourceAgentInstructionsSha256: fileSha256(agentInstructionsPath),
    sourcePackageJsonPath: packageJsonPath,
    sourcePackageJsonSha256: fileSha256(packageJsonPath),
    sourceWorkflowPaths: workflowPaths,
    sourceWorkflowSha256: workflowSha256,
    primarySourceInputs: [
      {
        sourceProject: 'OpenHands Repository Agent guidance',
        sourceUrl: 'https://docs.openhands.dev/overview/skills/repo',
        observedPattern: 'Repository-wide agent instructions are stronger when they summarize repository purpose, setup, structure, and CI workflow context.',
        localAbsorption: 'AGENTS.md now includes a Repository Orientation section, and this report verifies that orientation as product-quality evidence.',
      },
      {
        sourceProject: 'OpenHands Skills overview',
        sourceUrl: 'https://docs.openhands.dev/overview/skills',
        observedPattern: 'Always-on repository context and on-demand skills should be separated so agents can load durable instructions without wasting context.',
        localAbsorption: 'AGENTS.md preserves always-on GStack/GSD/Superpowers routing while this gate keeps those boundaries checkable.',
      },
    ],
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    protectedActionsExecuted: [],
    purposeSectionPresent: /## Repository Orientation[\s\S]*### Repository Purpose/.test(agentInstructions),
    setupVerificationCommandsPresent,
    repositoryStructureSectionsPresent,
    workflowEvidencePresent: workflowPaths.every((path) => existsSync(resolve(root, path))) && productQualityScript.includes('product:agent-instructions-quality'),
    agentStackBoundariesPresent,
    primarySourceRulePresent: /primary sources/i.test(agentInstructions) && /blogs only as pointers/i.test(agentInstructions),
    verificationStandardPresent: /Verification Standard/.test(agentInstructions) && /file presence/i.test(agentInstructions) && /Verify by running/i.test(agentInstructions),
    protectedBoundaryLanguagePresent: /protected/i.test(agentInstructions) && /readiness claim/i.test(agentInstructions),
    publicInstructionLineCount,
    publicInstructionMaxLines: 220,
    privateMemoryDumpPresent,
    stalePublicModelLockPresent,
    localPathLeakPresent,
    claimBoundary: 'Agent instruction quality evidence only; this does not authorize release, production, public, external-validation, or autonomous-reliability claims.',
    releaseReadinessClaimAllowed: false,
    productionReadinessClaimAllowed: false,
    publicReadinessClaimAllowed: false,
    externalValidationClaimAllowed: false,
    autonomousReliabilityClaimAllowed: false,
    instructionQualityChecks: [],
  }

  report.instructionQualityChecks = [
    check('AGENTS.md imported', report.sourceAgentInstructionsSha256.length === 64, report.sourceAgentInstructionsPath),
    check('package.json imported', report.sourcePackageJsonSha256.length === 64, report.sourcePackageJsonPath),
    check('primary-source inputs are official project sources', report.primarySourceInputs.every((source) => source.sourceUrl.startsWith('https://docs.openhands.dev/')), report.primarySourceInputs.map((source) => source.sourceUrl).join(',')),
    check('repository purpose is explicit', report.purposeSectionPresent, 'Repository Orientation / Repository Purpose'),
    check('setup and verification commands are explicit', report.setupVerificationCommandsPresent.length === 4, report.setupVerificationCommandsPresent.join(',')),
    check('repository structure is explicit', report.repositoryStructureSectionsPresent.length === 6, report.repositoryStructureSectionsPresent.join(',')),
    check('workflow evidence is wired', report.workflowEvidencePresent, workflowPaths.join(',')),
    check('agent-stack boundaries remain explicit', report.agentStackBoundariesPresent.length === 3, report.agentStackBoundariesPresent.join(',')),
    check('primary-source research rule remains explicit', report.primarySourceRulePresent, 'primary sources / blogs only as pointers'),
    check('verification standard remains explicit', report.verificationStandardPresent, 'verification by command, not file presence'),
    check('protected boundary language remains explicit', report.protectedBoundaryLanguagePresent, 'protected boundary / readiness claim'),
    check('AGENTS.md stays concise for public readers', report.publicInstructionLineCount <= report.publicInstructionMaxLines, `${report.publicInstructionLineCount}/${report.publicInstructionMaxLines} lines`),
    check('AGENTS.md excludes private memory dumps', report.privateMemoryDumpPresent === false, `present=${report.privateMemoryDumpPresent}`),
    check('AGENTS.md excludes stale public model-lock lines', report.stalePublicModelLockPresent === false, `present=${report.stalePublicModelLockPresent}`),
    check('AGENTS.md excludes local user paths', report.localPathLeakPresent === false, `present=${report.localPathLeakPresent}`),
    check('provider live external calls remain absent', report.providerCallsPerformed.length === 0 && report.liveModelCallsPerformed.length === 0 && report.externalCallsPerformed.length === 0, 'all call arrays empty'),
    check('protected actions remain absent', report.protectedActionsExecuted.length === 0, 'zero'),
    check('readiness and reliability claims remain blocked', report.releaseReadinessClaimAllowed === false && report.productionReadinessClaimAllowed === false && report.publicReadinessClaimAllowed === false && report.externalValidationClaimAllowed === false && report.autonomousReliabilityClaimAllowed === false, 'all false'),
  ]

  writeFileSync(resolve(docsDir, 'agent-instructions-quality-report.json'), `${JSON.stringify(report, null, 2)}\n`)
  writeMarkdown(report)

  for (const item of report.instructionQualityChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  const failed = report.instructionQualityChecks.filter((item) => !item.ok)
  if (failed.length > 0) {
    console.error(`RESULT: FAIL (${failed.length} failed checks)`)
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`setup_verification_command_count=${report.setupVerificationCommandsPresent.length}`)
  console.log(`repository_structure_section_count=${report.repositoryStructureSectionsPresent.length}`)
  console.log(`workflow_evidence_present=${report.workflowEvidencePresent}`)
  console.log(`agent_stack_boundary_count=${report.agentStackBoundariesPresent.length}`)
}

main()
