import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { discoverPublishableTraceFiles } from './product-trace-discovery'

type BasicCheck = {
  label: string
  ok: boolean
  detail: string
}

type RealTraceEvalReport = {
  mode: string
  traceFileCount: number
  providerCallsPerformed: unknown[]
  liveModelCallsPerformed: unknown[]
  externalCallsPerformed: unknown[]
  traces: Array<{
    path: string
    sha256: string
    traceKind: string
    eventCount: number
    statusSequence: string[]
    roles: string[]
    models: string[]
    querySources: string[]
    passed: boolean
    credentialPatternFound: boolean
  }>
  coverageSummary: {
    traceKinds: string[]
    terminalOutcomes: string[]
    roles: string[]
    models: string[]
    querySources: string[]
    classifiedCoverageGaps: Array<{
      id: string
      status: string
      protectedActionRequired: boolean
    }>
  }
}

type RedactionRule = {
  id: string
  action: 'omit' | 'hash' | 'count_only' | 'bounded_label_only'
  appliesTo: string
  reason: string
}

type TraceCaptureRedactionPolicyReport = {
  generatedAt: string
  mode: 'local_no_provider_trace_capture_redaction_policy'
  sourceTraceReportPath: string
  sourceTraceReportSha256: string
  rawTraceDirectory: string
  rawTraceFileCount: number
  providerCallsPerformed: []
  liveModelCallsPerformed: []
  externalCallsPerformed: []
  nonSyntheticRealSessionCapture: {
    performed: false
    requiredBeforeStrongerReliabilityClaims: true
    currentStatus: 'policy_ready_capture_not_performed'
    detail: string
  }
  publishableSummaryFields: string[]
  forbiddenRawFields: string[]
  redactionRules: RedactionRule[]
  captureWorkflow: string[]
  scannedRawTraceFiles: Array<{
    path: string
    sha256: string
    lineCount: number
    credentialPatternFound: boolean
    providerRequestIdPatternFound: boolean
  }>
  policyChecks: BasicCheck[]
  claimBoundary: string
}

const root = process.cwd()
const docsDir = resolve(root, 'docs/product-quality')
const traceDirectory = 'reports'
const sourceTraceReportPath = 'docs/product-quality/real-session-trace-evals-report.json'
const credentialPatterns = [
  /AKIA[0-9A-Z]{16}/,
  /ASIA[0-9A-Z]{16}/,
  /sk-[A-Za-z0-9_-]{20,}/,
  /xox[baprs]-[A-Za-z0-9-]{10,}/,
  /gh[pousr]_[A-Za-z0-9_]{30,}/,
  /-----BEGIN (RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY-----/,
]
const providerRequestIdPattern = /(?:\\?"(?:request_id|providerRequestId|message_id|run_id|id)\\?"\s*:\s*\\?"(?:req|msg|run)_[A-Za-z0-9_-]{10,}\\?"|\breq_[A-Za-z0-9_-]{10,}\b)/

function readText(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function readJson<T>(path: string): T {
  return JSON.parse(readText(path)) as T
}

function sha256(text: string): string {
  return createHash('sha256').update(text).digest('hex')
}

function check(label: string, ok: boolean, detail: string): BasicCheck {
  return { label, ok, detail }
}

function hasCredentialPattern(text: string): boolean {
  return credentialPatterns.some((pattern) => pattern.test(text))
}

function scanRawTrace(path: string): TraceCaptureRedactionPolicyReport['scannedRawTraceFiles'][number] {
  const text = readText(path)
  return {
    path,
    sha256: sha256(text),
    lineCount: text.split(/\r?\n/).filter((line) => line.trim().length > 0).length,
    credentialPatternFound: hasCredentialPattern(text),
    providerRequestIdPatternFound: providerRequestIdPattern.test(text),
  }
}

function writeReports(report: TraceCaptureRedactionPolicyReport): void {
  mkdirSync(docsDir, { recursive: true })
  writeFileSync(
    resolve(docsDir, 'trace-capture-redaction-policy-report.json'),
    `${JSON.stringify(report, null, 2)}\n`,
  )

  const lines = [
    '# Trace Capture Redaction Policy Report',
    '',
    'Generated by: `bun run product:trace-redaction-policy`',
    '',
    '## Claim Boundary',
    '',
    '- This report defines and checks the local trace capture/redaction workflow only.',
    '- It does not capture a new non-synthetic user session.',
    '- It does not call providers, live models, or external services.',
    '- It does not publish, deploy, launch, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
    '',
    '## Summary',
    '',
    `- source_trace_report: \`${report.sourceTraceReportPath}\``,
    `- raw_trace_file_count: \`${report.rawTraceFileCount}\``,
    `- non_synthetic_real_session_capture_performed: \`${report.nonSyntheticRealSessionCapture.performed}\``,
    `- non_synthetic_real_session_capture_status: \`${report.nonSyntheticRealSessionCapture.currentStatus}\``,
    `- provider_calls_performed: \`${report.providerCallsPerformed.length}\``,
    `- live_model_calls_performed: \`${report.liveModelCallsPerformed.length}\``,
    `- external_calls_performed: \`${report.externalCallsPerformed.length}\``,
    '',
    '## Publishable Summary Fields',
    '',
    ...report.publishableSummaryFields.map((field) => `- \`${field}\``),
    '',
    '## Forbidden Raw Fields',
    '',
    ...report.forbiddenRawFields.map((field) => `- \`${field}\``),
    '',
    '## Redaction Rules',
    '',
    '| Rule | Action | Applies To | Reason |',
    '| --- | --- | --- | --- |',
    ...report.redactionRules.map((rule) => (
      `| \`${rule.id}\` | \`${rule.action}\` | ${rule.appliesTo} | ${rule.reason} |`
    )),
    '',
    '## Capture Workflow',
    '',
    ...report.captureWorkflow.map((step, index) => `${index + 1}. ${step}`),
    '',
    '## Raw Trace Scan',
    '',
    '| Trace | Lines | Credential Pattern | Provider Request ID Pattern | SHA-256 |',
    '| --- | ---: | --- | --- | --- |',
    ...report.scannedRawTraceFiles.map((trace) => (
      `| \`${trace.path}\` | ${trace.lineCount} | \`${trace.credentialPatternFound}\` | \`${trace.providerRequestIdPatternFound}\` | \`${trace.sha256}\` |`
    )),
    '',
    '## Checks',
    '',
    '| Check | Result | Detail |',
    '| --- | --- | --- |',
    ...report.policyChecks.map((item) => `| ${item.label} | \`${item.ok}\` | ${item.detail} |`),
    '',
  ]

  writeFileSync(resolve(docsDir, 'trace-capture-redaction-policy-report.md'), `${lines.join('\n')}\n`)
}

function main(): void {
  const traceReportText = readText(sourceTraceReportPath)
  const traceReport = JSON.parse(traceReportText) as RealTraceEvalReport
  const rawTraceFiles = discoverPublishableTraceFiles({ root, traceDirectory })
  const scannedRawTraceFiles = rawTraceFiles.map((path) => scanRawTrace(path))
  const publishableSummaryFields = [
    'path',
    'sha256',
    'traceKind',
    'lineCount',
    'eventCount',
    'statusSequence',
    'roles',
    'models',
    'querySources',
    'firstStatus',
    'lastStatus',
    'coverageSummary',
  ]
  const forbiddenRawFields = [
    'api_key',
    'authorization',
    'cookie',
    'set-cookie',
    'rawPrompt',
    'rawCompletion',
    'rawProviderPayload',
    'providerRequestId',
    'environment',
    'homeDirectory',
    'profilePath',
  ]
  const redactionRules: RedactionRule[] = [
    {
      id: 'credentials_and_tokens',
      action: 'omit',
      appliesTo: 'API keys, OAuth tokens, cookies, private keys, authorization headers',
      reason: 'Trace reports must never become credential stores.',
    },
    {
      id: 'provider_request_identifiers',
      action: 'omit',
      appliesTo: 'Provider request IDs, message IDs, run IDs, and raw error correlation IDs',
      reason: 'Provider correlation identifiers are unnecessary for product-quality summaries.',
    },
    {
      id: 'raw_prompt_and_completion_payloads',
      action: 'count_only',
      appliesTo: 'Raw prompt text, raw completion text, raw tool observations, and raw provider errors',
      reason: 'Quality gates need counts, roles, status transitions, and hashes rather than sensitive payload bodies.',
    },
    {
      id: 'local_path_and_environment_details',
      action: 'bounded_label_only',
      appliesTo: 'Home directories, profile paths, environment variables, and machine-specific runtime details',
      reason: 'Reports should preserve reproducibility without leaking local operator context.',
    },
    {
      id: 'raw_trace_identity',
      action: 'hash',
      appliesTo: 'Raw local trace files',
      reason: 'SHA-256 preserves artifact identity while avoiding raw-line publication.',
    },
  ]
  const captureWorkflow = [
    'Capture non-synthetic user/session traces only after an explicit operator action selects the session and local file path.',
    'Store raw JSONL only under the local reports/orchestra-*.jsonl pattern; do not copy credentials, provider configs, profiles, caches, databases, cookies, or environment files.',
    'Run bun run product:real-trace-evals to produce structured summaries with hashes, counts, roles, models, query sources, and status transitions.',
    'Run bun run product:trace-redaction-policy to scan raw traces for credential and provider-request-id patterns before any report is treated as publishable evidence.',
    'Publish only docs/product-quality summary reports; keep raw provider payloads, raw prompt/completion text, authorization data, and local environment details out of reports.',
    'If any credential or provider request-id pattern is detected, stop the product-quality gate and quarantine the trace outside publishable evidence until the operator resolves it.',
  ]
  const nonSyntheticRealSessionCapture: TraceCaptureRedactionPolicyReport['nonSyntheticRealSessionCapture'] = {
    performed: false,
    requiredBeforeStrongerReliabilityClaims: true,
    currentStatus: 'policy_ready_capture_not_performed',
    detail: 'This gate defines and verifies the redaction workflow. It does not claim that a new non-synthetic user session was captured in this run.',
  }
  const policyChecks = [
    check('source real trace report is local no-provider', traceReport.mode === 'local_no_provider_real_session_jsonl_trace_grading', traceReport.mode),
    check('source real trace report performed no provider calls', traceReport.providerCallsPerformed.length === 0, `${traceReport.providerCallsPerformed.length}`),
    check('source real trace report performed no live model calls', traceReport.liveModelCallsPerformed.length === 0, `${traceReport.liveModelCallsPerformed.length}`),
    check('source real trace report performed no external calls', traceReport.externalCallsPerformed.length === 0, `${traceReport.externalCallsPerformed.length}`),
    check('raw trace files match source report count', rawTraceFiles.length === traceReport.traceFileCount, `${rawTraceFiles.length}/${traceReport.traceFileCount}`),
    check('raw trace hashes match source report', traceReport.traces.every((trace) => scannedRawTraceFiles.some((raw) => raw.path === trace.path && raw.sha256 === trace.sha256)), `${traceReport.traces.length} summarized traces`),
    check('raw trace credential patterns absent', scannedRawTraceFiles.every((trace) => !trace.credentialPatternFound), `${scannedRawTraceFiles.filter((trace) => trace.credentialPatternFound).length} matches`),
    check('raw trace provider request id patterns absent', scannedRawTraceFiles.every((trace) => !trace.providerRequestIdPatternFound), `${scannedRawTraceFiles.filter((trace) => trace.providerRequestIdPatternFound).length} matches`),
    check('publishable fields are summary-only', publishableSummaryFields.every((field) => !forbiddenRawFields.includes(field)), publishableSummaryFields.join(', ')),
    check('forbidden raw fields cover credentials and provider payloads', ['api_key', 'authorization', 'rawPrompt', 'rawCompletion', 'rawProviderPayload', 'providerRequestId'].every((field) => forbiddenRawFields.includes(field)), forbiddenRawFields.join(', ')),
    check('redaction rules cover credential, provider id, raw payload, path, and trace identity', redactionRules.length >= 5, `${redactionRules.length} rules`),
    check('capture workflow has explicit operator and quarantine steps', captureWorkflow.some((step) => step.includes('explicit operator')) && captureWorkflow.some((step) => step.includes('quarantine')), `${captureWorkflow.length} steps`),
    check('non-synthetic capture is not falsely claimed', nonSyntheticRealSessionCapture.performed === false && nonSyntheticRealSessionCapture.requiredBeforeStrongerReliabilityClaims === true, 'policy ready; capture not performed by this script'),
    check('coverage summary keeps role and model evidence', traceReport.coverageSummary.roles.length >= 2 && traceReport.coverageSummary.models.length >= 2, `${traceReport.coverageSummary.roles.length} roles, ${traceReport.coverageSummary.models.length} models`),
  ]

  const report: TraceCaptureRedactionPolicyReport = {
    generatedAt: new Date().toISOString(),
    mode: 'local_no_provider_trace_capture_redaction_policy',
    sourceTraceReportPath,
    sourceTraceReportSha256: sha256(traceReportText),
    rawTraceDirectory: traceDirectory,
    rawTraceFileCount: rawTraceFiles.length,
    providerCallsPerformed: [],
    liveModelCallsPerformed: [],
    externalCallsPerformed: [],
    nonSyntheticRealSessionCapture,
    publishableSummaryFields,
    forbiddenRawFields,
    redactionRules,
    captureWorkflow,
    scannedRawTraceFiles,
    policyChecks,
    claimBoundary: 'Trace capture redaction policy evidence is local, no-provider, and summary-only. It does not capture a new non-synthetic session, call providers, publish raw traces, or claim release readiness, production readiness, public readiness, external validation, or autonomous reliability.',
  }

  writeReports(report)

  for (const item of policyChecks) {
    console.log(`${item.ok ? 'PASS' : 'FAIL'}: ${item.label} (${item.detail})`)
  }

  console.log('')
  if (!policyChecks.every((item) => item.ok)) {
    console.error('RESULT: FAIL')
    process.exit(1)
  }

  console.log('RESULT: PASS')
  console.log(`raw_trace_file_count=${report.rawTraceFileCount}`)
  console.log(`redaction_rule_count=${report.redactionRules.length}`)
  console.log(`capture_workflow_steps=${report.captureWorkflow.length}`)
  console.log(`non_synthetic_real_session_capture_performed=${report.nonSyntheticRealSessionCapture.performed}`)
  console.log(`provider_calls_performed=${report.providerCallsPerformed.length}`)
  console.log(`live_model_calls_performed=${report.liveModelCallsPerformed.length}`)
  console.log(`external_calls_performed=${report.externalCallsPerformed.length}`)
}

main()
