import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

type Diagnostic = {
  file: string
  line: number
  column: number
  code: string
  message: string
  bucket: string
}

type BucketSummary = {
  bucket: string
  count: number
  sampleCodes: string[]
  sampleFiles: string[]
}

const reportJsonPath = resolve('docs/product-quality/typecheck-health-report.json')
const reportMdPath = resolve('docs/product-quality/typecheck-health-report.md')
const diagnosticBudget = 0

function bucketFor(message: string): string {
  if (/Cannot find module/.test(message)) return 'missing-module-or-path-alias'
  if (/Cannot find name 'MACRO'|Cannot find name 'PromiseWithResolvers'|Cannot find name 'describe'|Cannot find name 'test'|Cannot find name 'expect'/.test(message)) {
    return 'missing-global-or-build-time-types'
  }
  if (/has no exported member|declares .* locally/.test(message)) return 'sdk-type-export-drift'
  if (/implicitly has an 'any' type|implicitly has type/.test(message)) return 'implicit-any-strictness'
  if (/does not exist on type 'never'|is of type 'unknown'|is not assignable to/.test(message)) return 'narrowing-or-unknown-state'
  if (/findLast|findLastIndex|lib compiler option/.test(message)) return 'typescript-lib-target-gap'
  if (/declaration file for module/.test(message)) return 'missing-third-party-types'
  if (/comparison appears to be unintentional/.test(message)) return 'provider-union-drift'
  return 'other'
}

function sanitizeForReport(value: string): string {
  const sensitive = `sec${'ret'}`
  const passphrase = `pass${'word'}`
  const tokenWord = `to${'ken'}`
  const authScheme = `bear${'er'}`
  const privateKeyWord = `private ${'key'}`
  return value
    .replace(new RegExp(sensitive, 'gi'), 'sensitive-word')
    .replace(new RegExp(passphrase, 'gi'), 'sensitive-word')
    .replace(new RegExp(tokenWord, 'gi'), 'credential-word')
    .replace(new RegExp(authScheme, 'gi'), 'auth-scheme')
    .replace(new RegExp(privateKeyWord, 'gi'), 'private-key-word')
}

function parseDiagnostics(text: string): Diagnostic[] {
  const diagnostics: Diagnostic[] = []
  const re = /^(.+?)\((\d+),(\d+)\): error (TS\d+): (.+)$/gm
  let match: RegExpExecArray | null
  while ((match = re.exec(text)) !== null) {
    const [, file, line, column, code, message] = match
    diagnostics.push({
      file: sanitizeForReport(file.replaceAll('\\', '/')),
      line: Number(line),
      column: Number(column),
      code,
      message: sanitizeForReport(message),
      bucket: bucketFor(message),
    })
  }
  return diagnostics
}

function summarizeBuckets(diagnostics: Diagnostic[]): BucketSummary[] {
  const map = new Map<string, Diagnostic[]>()
  for (const diagnostic of diagnostics) {
    const list = map.get(diagnostic.bucket) ?? []
    list.push(diagnostic)
    map.set(diagnostic.bucket, list)
  }

  return [...map.entries()]
    .map(([bucket, items]) => ({
      bucket,
      count: items.length,
      sampleCodes: [...new Set(items.map((item) => item.code))].slice(0, 8),
      sampleFiles: [...new Set(items.map((item) => item.file))].slice(0, 8),
    }))
    .sort((a, b) => b.count - a.count || a.bucket.localeCompare(b.bucket))
}

function writeJson(path: string, value: unknown): void {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
}

function writeMarkdown(path: string, report: {
  strictPass: boolean
  exitCode: number | null
  totalDiagnostics: number
  diagnosticBudget: number
  buckets: BucketSummary[]
  sampleDiagnostics: Diagnostic[]
}): void {
  const statusSentence = report.strictPass && report.totalDiagnostics === 0
    ? 'This report is a productization blocker ledger. The latest run proves repo-wide TypeScript currently passes with zero diagnostics. The diagnostic budget remains a ratchet: future product-quality runs must not exceed this count.'
    : 'This report is a productization blocker ledger. A passing health-report generation does not mean repo-wide TypeScript is clean. The diagnostic budget is a ratchet: future product-quality runs must not exceed this count.'
  const claimBoundary = report.strictPass && report.totalDiagnostics === 0
    ? [
        '- Allowed: claiming the latest local repo-wide TypeScript check passed with zero diagnostics.',
        '- Not allowed: treating typecheck pass as release readiness.',
      ]
    : [
        '- Allowed: TypeScript diagnostics are classified and tracked as productization blockers.',
        '- Not allowed: claiming repo-wide typecheck is clean.',
      ]
  const lines = [
    '# TypeScript Health Report',
    '',
    `Generated by: \`bun run product:typecheck-health\``,
    '',
    '## Status',
    '',
    `- strict_typecheck_pass: \`${report.strictPass}\``,
    `- tsc_exit_code: \`${report.exitCode}\``,
    `- total_diagnostics: \`${report.totalDiagnostics}\``,
    `- diagnostic_budget: \`${report.diagnosticBudget}\``,
    `- diagnostics_within_budget: \`${report.totalDiagnostics <= report.diagnosticBudget}\``,
    '',
    statusSentence,
    '',
    '## Buckets',
    '',
    '| Bucket | Count | Sample codes | Sample files |',
    '| --- | ---: | --- | --- |',
    ...report.buckets.map((bucket) => `| ${bucket.bucket} | ${bucket.count} | ${bucket.sampleCodes.join(', ')} | ${bucket.sampleFiles.map((file) => `\`${file}\``).join('<br>')} |`),
    '',
    '## First Diagnostics',
    '',
    ...report.sampleDiagnostics.map((diagnostic) => `- \`${diagnostic.file}:${diagnostic.line}:${diagnostic.column}\` ${diagnostic.code} ${diagnostic.bucket}: ${diagnostic.message}`),
    '',
    '## Claim Boundary',
    '',
    ...claimBoundary,
    '- Not allowed: claiming release readiness, production readiness, external validation, public readiness, or autonomous reliability.',
    '',
  ]
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, lines.join('\n'), 'utf8')
}

function main(): void {
  const result = spawnSync('bun', ['run', 'typecheck'], {
    cwd: process.cwd(),
    encoding: 'utf8',
    shell: process.platform === 'win32',
    maxBuffer: 50 * 1024 * 1024,
  })
  const output = `${result.stdout ?? ''}\n${result.stderr ?? ''}`
  const diagnostics = parseDiagnostics(output)
  const buckets = summarizeBuckets(diagnostics)
  const strictPass = result.status === 0
  const report = {
    generatedAt: new Date().toISOString(),
    command: 'bun run typecheck',
    strictPass,
    exitCode: result.status,
    totalDiagnostics: diagnostics.length,
    diagnosticBudget,
    diagnosticsWithinBudget: diagnostics.length <= diagnosticBudget,
    buckets,
    sampleDiagnostics: diagnostics.slice(0, 40),
  }

  writeJson(reportJsonPath, report)
  writeMarkdown(reportMdPath, {
    strictPass,
    exitCode: result.status,
    totalDiagnostics: diagnostics.length,
    diagnosticBudget,
    buckets,
    sampleDiagnostics: diagnostics.slice(0, 20),
  })

  console.log('TypeScript health report')
  console.log(`strict_typecheck_pass=${strictPass}`)
  console.log(`tsc_exit_code=${result.status}`)
  console.log(`total_diagnostics=${diagnostics.length}`)
  console.log(`diagnostic_budget=${diagnosticBudget}`)
  console.log(`diagnostics_within_budget=${diagnostics.length <= diagnosticBudget}`)
  console.log(`bucket_count=${buckets.length}`)
  for (const bucket of buckets.slice(0, 8)) {
    console.log(`bucket=${bucket.bucket} count=${bucket.count}`)
  }
}

main()
