name: OpenSSF Scorecard

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "41 4 * * 2"

permissions:
  contents: read

jobs:
  scorecard:
    name: OpenSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
